@file:Suppress("NOTHING_TO_INLINE", "MemberVisibilityCanBePrivate", "unused", "SpellCheckingInspection")

package io.github.aecsocket.klam

private const val AS_STRING_FORMAT = "%f"
private const val TO_STRING_FORMAT = DECIMAL_FORMAT
private inline fun typeArrayOf(vararg elements: Float) = floatArrayOf(*elements)

data class FVec2(@JvmField var x: Float, @JvmField var y: Float) {
    constructor(v: FVec2) : this(v.x, v.y)
    constructor(s: Float) : this(s, s)

    fun from(x: Float, y: Float) { this.x = x; this.y = y }
    fun from(v: FVec2) = from(v.x, v.y)

    operator fun get(idx: Index) = when (idx) {
        0 -> x
        1 -> y
        else -> throw IndexOutOfBoundsException(idx)
    }

    operator fun set(idx: Index, s: Float) = when (idx) {
        0 -> x = s
        1 -> y = s
        else -> throw IndexOutOfBoundsException(idx)
    }

    inline operator fun unaryMinus() = FVec2(-x, -y)
    inline operator fun inc()        = FVec2(x + 1, y + 1)
    inline operator fun dec()        = FVec2(x - 1, y - 1)

    inline operator fun plus(s: Float)  = FVec2(x + s, y + s)
    inline operator fun minus(s: Float) = FVec2(x - s, y - s)
    inline operator fun times(s: Float) = FVec2(x * s, y * s)
    inline operator fun div(s: Float)   = FVec2(x / s, y / s)
    inline operator fun rem(s: Float)   = FVec2(x % s, y % s)

    inline operator fun plus(v: FVec2)  = FVec2(x + v.x, y + v.y)
    inline operator fun minus(v: FVec2) = FVec2(x - v.x, y - v.y)
    inline operator fun times(v: FVec2) = FVec2(x * v.x, y * v.y)
    inline operator fun div(v: FVec2)   = FVec2(x / v.x, y / v.y)
    inline operator fun rem(v: FVec2)   = FVec2(x % v.x, y % v.y)

    inline operator fun plusAssign(s: Float)  { x += s; y += s }
    inline operator fun minusAssign(s: Float) { x -= s; y -= s }
    inline operator fun timesAssign(s: Float) { x *= s; y *= s }
    inline operator fun divAssign(s: Float)   { x /= s; y /= s }
    inline operator fun remAssign(s: Float)   { x %= s; y %= s }

    inline operator fun plusAssign(s: FVec2)  { x += s.x; y += s.y }
    inline operator fun minusAssign(s: FVec2) { x -= s.x; y -= s.y }
    inline operator fun timesAssign(s: FVec2) { x *= s.x; y *= s.y }
    inline operator fun divAssign(s: FVec2)   { x /= s.x; y /= s.y }
    inline operator fun remAssign(s: FVec2)   { x %= s.x; y %= s.y }

    inline fun compareTo(v: FVec2) = IVec2(x.compareTo(v.x), y.compareTo(v.y))
    inline fun equalTo(v: FVec2) = x.compareTo(v.x) == 0 && y.compareTo(v.y) == 0

    inline fun map(block: (Float) -> Float) = FVec2(block(x), block(y))
    fun toArray() = typeArrayOf(x, y)

    fun asString(fmt: String = AS_STRING_FORMAT) = "($fmt, $fmt)".format(x, y)
    override fun toString() = asString(TO_STRING_FORMAT)
}

data class FVec3(@JvmField var x: Float, @JvmField var y: Float, @JvmField var z: Float) {
    constructor(v: FVec3) : this(v.x, v.y, v.z)
    constructor(v: FVec2, z: Float) : this(v.x, v.y, z)
    constructor(s: Float) : this(s, s, s)

    fun from(x: Float, y: Float, z: Float) { this.x = x; this.y = y; this.z = z }
    fun from(v: FVec3) = from(v.x, v.y, v.z)

    operator fun get(idx: Index) = when (idx) {
        0 -> x
        1 -> y
        2 -> z
        else -> throw IndexOutOfBoundsException(idx)
    }

    operator fun set(idx: Index, s: Float) = when (idx) {
        0 -> x = s
        1 -> y = s
        2 -> z = s
        else -> throw IndexOutOfBoundsException(idx)
    }

    inline operator fun unaryMinus() = FVec3(-x, -y, -z)
    inline operator fun inc()        = FVec3(x + 1, y + 1, z + 1)
    inline operator fun dec()        = FVec3(x - 1, y - 1, z - 1)

    inline operator fun plus(s: Float)  = FVec3(x + s, y + s, z + s)
    inline operator fun minus(s: Float) = FVec3(x - s, y - s, z - s)
    inline operator fun times(s: Float) = FVec3(x * s, y * s, z * s)
    inline operator fun div(s: Float)   = FVec3(x / s, y / s, z / s)
    inline operator fun rem(s: Float)   = FVec3(x % s, y % s, z % s)

    inline operator fun plus(v: FVec3)  = FVec3(x + v.x, y + v.y, z + v.z)
    inline operator fun minus(v: FVec3) = FVec3(x - v.x, y - v.y, z - v.z)
    inline operator fun times(v: FVec3) = FVec3(x * v.x, y * v.y, z * v.z)
    inline operator fun div(v: FVec3)   = FVec3(x / v.x, y / v.y, z / v.z)
    inline operator fun rem(v: FVec3)   = FVec3(x % v.x, y % v.y, z % v.z)

    inline operator fun plusAssign(s: Float)  { x += s; y += s; z += s }
    inline operator fun minusAssign(s: Float) { x -= s; y -= s; z -= s }
    inline operator fun timesAssign(s: Float) { x *= s; y *= s; z *= s }
    inline operator fun divAssign(s: Float)   { x /= s; y /= s; z /= s }
    inline operator fun remAssign(s: Float)   { x %= s; y %= s; z %= s }

    inline operator fun plusAssign(s: FVec3)  { x += s.x; y += s.y; z += s.z }
    inline operator fun minusAssign(s: FVec3) { x -= s.x; y -= s.y; z -= s.z }
    inline operator fun timesAssign(s: FVec3) { x *= s.x; y *= s.y; z *= s.z }
    inline operator fun divAssign(s: FVec3)   { x /= s.x; y /= s.y; z /= s.z }
    inline operator fun remAssign(s: FVec3)   { x %= s.x; y %= s.y; z %= s.z }

    inline fun compareTo(v: FVec3) = IVec3(x.compareTo(v.x), y.compareTo(v.y), z.compareTo(v.z))
    inline fun equalTo(v: FVec3) = x.compareTo(v.x) == 0 && y.compareTo(v.y) == 0 && z.compareTo(v.z) == 0

    inline fun map(block: (Float) -> Float) = FVec3(block(x), block(y), block(z))
    fun toArray() = typeArrayOf(x, y, z)

    fun asString(fmt: String = AS_STRING_FORMAT) = "($fmt, $fmt, $fmt)".format(x, y, z)
    override fun toString() = asString(TO_STRING_FORMAT)
}

data class FVec4(@JvmField var x: Float, @JvmField var y: Float, @JvmField var z: Float, @JvmField var w: Float) {
    constructor(v: FVec4) : this(v.x, v.y, v.z, v.w)
    constructor(v: FVec3, w: Float) : this(v.x, v.y, v.z, w)
    constructor(v: FVec2, z: Float, w: Float) : this(v.x, v.y, z, w)
    constructor(s: Float) : this(s, s, s, s)

    fun from(x: Float, y: Float, z: Float, w: Float) { this.x = x; this.y = y; this.z = z; this.w = w }
    fun from(v: FVec4) = from(v.x, v.y, v.z, v.w)

    operator fun get(idx: Index) = when (idx) {
        0 -> x
        1 -> y
        2 -> z
        3 -> w
        else -> throw IndexOutOfBoundsException(idx)
    }

    operator fun set(idx: Index, s: Float) = when (idx) {
        0 -> x = s
        1 -> y = s
        2 -> z = s
        3 -> w = s
        else -> throw IndexOutOfBoundsException(idx)
    }

    inline operator fun unaryMinus() = FVec4(-x, -y, -z, -w)
    inline operator fun inc()        = FVec4(x + 1, y + 1, z + 1, w + 1)
    inline operator fun dec()        = FVec4(x - 1, y - 1, z - 1, w - 1)

    inline operator fun plus(s: Float)  = FVec4(x + s, y + s, z + s, w + s)
    inline operator fun minus(s: Float) = FVec4(x - s, y - s, z - s, w - s)
    inline operator fun times(s: Float) = FVec4(x * s, y * s, z * s, w * s)
    inline operator fun div(s: Float)   = FVec4(x / s, y / s, z / s, w / s)
    inline operator fun rem(s: Float)   = FVec4(x % s, y % s, z % s, w % s)

    inline operator fun plus(v: FVec4)  = FVec4(x + v.x, y + v.y, z + v.z, w + v.w)
    inline operator fun minus(v: FVec4) = FVec4(x - v.x, y - v.y, z - v.z, w - v.w)
    inline operator fun times(v: FVec4) = FVec4(x * v.x, y * v.y, z * v.z, w * v.w)
    inline operator fun div(v: FVec4)   = FVec4(x / v.x, y / v.y, z / v.z, w / v.w)
    inline operator fun rem(v: FVec4)   = FVec4(x % v.x, y % v.y, z % v.z, w % v.w)

    inline operator fun plusAssign(s: Float)  { x += s; y += s; z += s; w += s }
    inline operator fun minusAssign(s: Float) { x -= s; y -= s; z -= s; w -= s }
    inline operator fun timesAssign(s: Float) { x *= s; y *= s; z *= s; w *= s }
    inline operator fun divAssign(s: Float)   { x /= s; y /= s; z /= s; w /= s }
    inline operator fun remAssign(s: Float)   { x %= s; y %= s; z %= s; w %= s }

    inline operator fun plusAssign(s: FVec4)  { x += s.x; y += s.y; z += s.z; w += s.w }
    inline operator fun minusAssign(s: FVec4) { x -= s.x; y -= s.y; z -= s.z; w -= s.w }
    inline operator fun timesAssign(s: FVec4) { x *= s.x; y *= s.y; z *= s.z; w *= s.w }
    inline operator fun divAssign(s: FVec4)   { x /= s.x; y /= s.y; z /= s.z; w /= s.w }
    inline operator fun remAssign(s: FVec4)   { x %= s.x; y %= s.y; z %= s.z; w %= s.w }

    inline fun compareTo(v: FVec4) = IVec4(x.compareTo(v.x), y.compareTo(v.y), z.compareTo(v.z), w.compareTo(v.w))
    inline fun equalTo(v: FVec4) = x.compareTo(v.x) == 0 && y.compareTo(v.y) == 0 && z.compareTo(v.z) == 0 && w.compareTo(v.w) == 0

    inline fun map(block: (Float) -> Float) = FVec4(block(x), block(y), block(z), block(w))
    fun toArray() = typeArrayOf(x, y, z, w)

    fun asString(fmt: String = AS_STRING_FORMAT) = "($fmt, $fmt, $fmt, $fmt)".format(x, y, z, w)
    override fun toString() = asString(TO_STRING_FORMAT)
}

//region Alternate accessors
inline var FVec2.r get() = x; set(value) { x = value }
inline var FVec2.g get() = y; set(value) { y = value }

inline var FVec2.s get() = x; set(value) { x = value }
inline var FVec2.t get() = y; set(value) { y = value}

inline var FVec3.r get() = x; set(value) { x = value }
inline var FVec3.g get() = y; set(value) { y = value }
inline var FVec3.b get() = z; set(value) { z = value }

inline var FVec3.s get() = x; set(value) { x = value}
inline var FVec3.t get() = y; set(value) { y = value }
inline var FVec3.p get() = z; set(value) { z = value }

inline var FVec4.r get() = x; set(value) { x = value }
inline var FVec4.g get() = y; set(value) { y = value }
inline var FVec4.b get() = z; set(value) { z = value }
inline var FVec4.a get() = w; set(value) { w = value }

inline var FVec4.s get() = x; set(value) { x = value }
inline var FVec4.t get() = y; set(value) { y = value }
inline var FVec4.p get() = z; set(value) { z = value }
inline var FVec4.q get() = w; set(value) { w = value }
//endregion

//region Swizzling Vec2
inline val FVec2.xx get() = FVec2(x, x)
inline val FVec2.xy get() = FVec2(x, y)
inline val FVec2.yx get() = FVec2(y, x)
inline val FVec2.yy get() = FVec2(y, y)

inline val FVec2.rr get() = FVec2(r, r)
inline val FVec2.rg get() = FVec2(r, g)
inline val FVec2.gr get() = FVec2(g, r)
inline val FVec2.gg get() = FVec2(g, g)

inline val FVec2.ss get() = FVec2(s, s)
inline val FVec2.st get() = FVec2(s, t)
inline val FVec2.ts get() = FVec2(t, s)
inline val FVec2.tt get() = FVec2(t, t)

inline val FVec2.xxx get() = FVec3(x, x, x)
inline val FVec2.xxy get() = FVec3(x, x, y)
inline val FVec2.xyx get() = FVec3(x, y, x)
inline val FVec2.xyy get() = FVec3(x, y, y)
inline val FVec2.yxx get() = FVec3(y, x, x)
inline val FVec2.yxy get() = FVec3(y, x, y)
inline val FVec2.yyx get() = FVec3(y, y, x)
inline val FVec2.yyy get() = FVec3(y, y, y)

inline val FVec2.rrr get() = FVec3(r, r, r)
inline val FVec2.rrg get() = FVec3(r, r, g)
inline val FVec2.rgr get() = FVec3(r, g, r)
inline val FVec2.rgg get() = FVec3(r, g, g)
inline val FVec2.grr get() = FVec3(g, r, r)
inline val FVec2.grg get() = FVec3(g, r, g)
inline val FVec2.ggr get() = FVec3(g, g, r)
inline val FVec2.ggg get() = FVec3(g, g, g)

inline val FVec2.sss get() = FVec3(s, s, s)
inline val FVec2.sst get() = FVec3(s, s, t)
inline val FVec2.sts get() = FVec3(s, t, s)
inline val FVec2.stt get() = FVec3(s, t, t)
inline val FVec2.tss get() = FVec3(t, s, s)
inline val FVec2.tst get() = FVec3(t, s, t)
inline val FVec2.tts get() = FVec3(t, t, s)
inline val FVec2.ttt get() = FVec3(t, t, t)

inline val FVec2.xxxx get() = FVec4(x, x, x, x)
inline val FVec2.xxxy get() = FVec4(x, x, x, y)
inline val FVec2.xxyx get() = FVec4(x, x, y, x)
inline val FVec2.xxyy get() = FVec4(x, x, y, y)
inline val FVec2.xyxx get() = FVec4(x, y, x, x)
inline val FVec2.xyxy get() = FVec4(x, y, x, y)
inline val FVec2.xyyx get() = FVec4(x, y, y, x)
inline val FVec2.xyyy get() = FVec4(x, y, y, y)
inline val FVec2.yxxx get() = FVec4(y, x, x, x)
inline val FVec2.yxxy get() = FVec4(y, x, x, y)
inline val FVec2.yxyx get() = FVec4(y, x, y, x)
inline val FVec2.yxyy get() = FVec4(y, x, y, y)
inline val FVec2.yyxx get() = FVec4(y, y, x, x)
inline val FVec2.yyxy get() = FVec4(y, y, x, y)
inline val FVec2.yyyx get() = FVec4(y, y, y, x)
inline val FVec2.yyyy get() = FVec4(y, y, y, y)

inline val FVec2.rrrr get() = FVec4(r, r, r, r)
inline val FVec2.rrrg get() = FVec4(r, r, r, g)
inline val FVec2.rrgr get() = FVec4(r, r, g, r)
inline val FVec2.rrgg get() = FVec4(r, r, g, g)
inline val FVec2.rgrr get() = FVec4(r, g, r, r)
inline val FVec2.rgrg get() = FVec4(r, g, r, g)
inline val FVec2.rggr get() = FVec4(r, g, g, r)
inline val FVec2.rggg get() = FVec4(r, g, g, g)
inline val FVec2.grrr get() = FVec4(g, r, r, r)
inline val FVec2.grrg get() = FVec4(g, r, r, g)
inline val FVec2.grgr get() = FVec4(g, r, g, r)
inline val FVec2.grgg get() = FVec4(g, r, g, g)
inline val FVec2.ggrr get() = FVec4(g, g, r, r)
inline val FVec2.ggrg get() = FVec4(g, g, r, g)
inline val FVec2.gggr get() = FVec4(g, g, g, r)
inline val FVec2.gggg get() = FVec4(g, g, g, g)

inline val FVec2.ssss get() = FVec4(s, s, s, s)
inline val FVec2.ssst get() = FVec4(s, s, s, t)
inline val FVec2.ssts get() = FVec4(s, s, t, s)
inline val FVec2.sstt get() = FVec4(s, s, t, t)
inline val FVec2.stss get() = FVec4(s, t, s, s)
inline val FVec2.stst get() = FVec4(s, t, s, t)
inline val FVec2.stts get() = FVec4(s, t, t, s)
inline val FVec2.sttt get() = FVec4(s, t, t, t)
inline val FVec2.tsss get() = FVec4(t, s, s, s)
inline val FVec2.tsst get() = FVec4(t, s, s, t)
inline val FVec2.tsts get() = FVec4(t, s, t, s)
inline val FVec2.tstt get() = FVec4(t, s, t, t)
inline val FVec2.ttss get() = FVec4(t, t, s, s)
inline val FVec2.ttst get() = FVec4(t, t, s, t)
inline val FVec2.ttts get() = FVec4(t, t, t, s)
inline val FVec2.tttt get() = FVec4(t, t, t, t)
//endregion

//region Swizzling Vec3
inline val FVec3.xx get() = FVec2(x, x)
inline val FVec3.xy get() = FVec2(x, y)
inline val FVec3.xz get() = FVec2(x, z)
inline val FVec3.yx get() = FVec2(y, x)
inline val FVec3.yy get() = FVec2(y, y)
inline val FVec3.yz get() = FVec2(y, z)
inline val FVec3.zx get() = FVec2(z, x)
inline val FVec3.zy get() = FVec2(z, y)
inline val FVec3.zz get() = FVec2(z, z)

inline val FVec3.rr get() = FVec2(r, r)
inline val FVec3.rg get() = FVec2(r, g)
inline val FVec3.rb get() = FVec2(r, b)
inline val FVec3.gr get() = FVec2(g, r)
inline val FVec3.gg get() = FVec2(g, g)
inline val FVec3.gb get() = FVec2(g, b)
inline val FVec3.br get() = FVec2(b, r)
inline val FVec3.bg get() = FVec2(b, g)
inline val FVec3.bb get() = FVec2(b, b)

inline val FVec3.ss get() = FVec2(s, s)
inline val FVec3.st get() = FVec2(s, t)
inline val FVec3.sp get() = FVec2(s, p)
inline val FVec3.ts get() = FVec2(t, s)
inline val FVec3.tt get() = FVec2(t, t)
inline val FVec3.tp get() = FVec2(t, p)
inline val FVec3.ps get() = FVec2(p, s)
inline val FVec3.pt get() = FVec2(p, t)
inline val FVec3.pp get() = FVec2(p, p)

inline val FVec3.xxx get() = FVec3(x, x, x)
inline val FVec3.xxy get() = FVec3(x, x, y)
inline val FVec3.xxz get() = FVec3(x, x, z)
inline val FVec3.xyx get() = FVec3(x, y, x)
inline val FVec3.xyy get() = FVec3(x, y, y)
inline val FVec3.xyz get() = FVec3(x, y, z)
inline val FVec3.xzx get() = FVec3(x, z, x)
inline val FVec3.xzy get() = FVec3(x, z, y)
inline val FVec3.xzz get() = FVec3(x, z, z)
inline val FVec3.yxx get() = FVec3(y, x, x)
inline val FVec3.yxy get() = FVec3(y, x, y)
inline val FVec3.yxz get() = FVec3(y, x, z)
inline val FVec3.yyx get() = FVec3(y, y, x)
inline val FVec3.yyy get() = FVec3(y, y, y)
inline val FVec3.yyz get() = FVec3(y, y, z)
inline val FVec3.yzx get() = FVec3(y, z, x)
inline val FVec3.yzy get() = FVec3(y, z, y)
inline val FVec3.yzz get() = FVec3(y, z, z)
inline val FVec3.zxx get() = FVec3(z, x, x)
inline val FVec3.zxy get() = FVec3(z, x, y)
inline val FVec3.zxz get() = FVec3(z, x, z)
inline val FVec3.zyx get() = FVec3(z, y, x)
inline val FVec3.zyy get() = FVec3(z, y, y)
inline val FVec3.zyz get() = FVec3(z, y, z)
inline val FVec3.zzx get() = FVec3(z, z, x)
inline val FVec3.zzy get() = FVec3(z, z, y)
inline val FVec3.zzz get() = FVec3(z, z, z)

inline val FVec3.rrr get() = FVec3(r, r, r)
inline val FVec3.rrg get() = FVec3(r, r, g)
inline val FVec3.rrb get() = FVec3(r, r, b)
inline val FVec3.rgr get() = FVec3(r, g, r)
inline val FVec3.rgg get() = FVec3(r, g, g)
inline val FVec3.rgb get() = FVec3(r, g, b)
inline val FVec3.rbr get() = FVec3(r, b, r)
inline val FVec3.rbg get() = FVec3(r, b, g)
inline val FVec3.rbb get() = FVec3(r, b, b)
inline val FVec3.grr get() = FVec3(g, r, r)
inline val FVec3.grg get() = FVec3(g, r, g)
inline val FVec3.grb get() = FVec3(g, r, b)
inline val FVec3.ggr get() = FVec3(g, g, r)
inline val FVec3.ggg get() = FVec3(g, g, g)
inline val FVec3.ggb get() = FVec3(g, g, b)
inline val FVec3.gbr get() = FVec3(g, b, r)
inline val FVec3.gbg get() = FVec3(g, b, g)
inline val FVec3.gbb get() = FVec3(g, b, b)
inline val FVec3.brr get() = FVec3(b, r, r)
inline val FVec3.brg get() = FVec3(b, r, g)
inline val FVec3.brb get() = FVec3(b, r, b)
inline val FVec3.bgr get() = FVec3(b, g, r)
inline val FVec3.bgg get() = FVec3(b, g, g)
inline val FVec3.bgb get() = FVec3(b, g, b)
inline val FVec3.bbr get() = FVec3(b, b, r)
inline val FVec3.bbg get() = FVec3(b, b, g)
inline val FVec3.bbb get() = FVec3(b, b, b)

inline val FVec3.sss get() = FVec3(s, s, s)
inline val FVec3.sst get() = FVec3(s, s, t)
inline val FVec3.ssp get() = FVec3(s, s, p)
inline val FVec3.sts get() = FVec3(s, t, s)
inline val FVec3.stt get() = FVec3(s, t, t)
inline val FVec3.stp get() = FVec3(s, t, p)
inline val FVec3.sps get() = FVec3(s, p, s)
inline val FVec3.spt get() = FVec3(s, p, t)
inline val FVec3.spp get() = FVec3(s, p, p)
inline val FVec3.tss get() = FVec3(t, s, s)
inline val FVec3.tst get() = FVec3(t, s, t)
inline val FVec3.tsp get() = FVec3(t, s, p)
inline val FVec3.tts get() = FVec3(t, t, s)
inline val FVec3.ttt get() = FVec3(t, t, t)
inline val FVec3.ttp get() = FVec3(t, t, p)
inline val FVec3.tps get() = FVec3(t, p, s)
inline val FVec3.tpt get() = FVec3(t, p, t)
inline val FVec3.tpp get() = FVec3(t, p, p)
inline val FVec3.pss get() = FVec3(p, s, s)
inline val FVec3.pst get() = FVec3(p, s, t)
inline val FVec3.psp get() = FVec3(p, s, p)
inline val FVec3.pts get() = FVec3(p, t, s)
inline val FVec3.ptt get() = FVec3(p, t, t)
inline val FVec3.ptp get() = FVec3(p, t, p)
inline val FVec3.pps get() = FVec3(p, p, s)
inline val FVec3.ppt get() = FVec3(p, p, t)
inline val FVec3.ppp get() = FVec3(p, p, p)

inline val FVec3.xxxx get() = FVec4(x, x, x, x)
inline val FVec3.xxxy get() = FVec4(x, x, x, y)
inline val FVec3.xxxz get() = FVec4(x, x, x, z)
inline val FVec3.xxyx get() = FVec4(x, x, y, x)
inline val FVec3.xxyy get() = FVec4(x, x, y, y)
inline val FVec3.xxyz get() = FVec4(x, x, y, z)
inline val FVec3.xxzx get() = FVec4(x, x, z, x)
inline val FVec3.xxzy get() = FVec4(x, x, z, y)
inline val FVec3.xxzz get() = FVec4(x, x, z, z)
inline val FVec3.xyxx get() = FVec4(x, y, x, x)
inline val FVec3.xyxy get() = FVec4(x, y, x, y)
inline val FVec3.xyxz get() = FVec4(x, y, x, z)
inline val FVec3.xyyx get() = FVec4(x, y, y, x)
inline val FVec3.xyyy get() = FVec4(x, y, y, y)
inline val FVec3.xyyz get() = FVec4(x, y, y, z)
inline val FVec3.xyzx get() = FVec4(x, y, z, x)
inline val FVec3.xyzy get() = FVec4(x, y, z, y)
inline val FVec3.xyzz get() = FVec4(x, y, z, z)
inline val FVec3.xzxx get() = FVec4(x, z, x, x)
inline val FVec3.xzxy get() = FVec4(x, z, x, y)
inline val FVec3.xzxz get() = FVec4(x, z, x, z)
inline val FVec3.xzyx get() = FVec4(x, z, y, x)
inline val FVec3.xzyy get() = FVec4(x, z, y, y)
inline val FVec3.xzyz get() = FVec4(x, z, y, z)
inline val FVec3.xzzx get() = FVec4(x, z, z, x)
inline val FVec3.xzzy get() = FVec4(x, z, z, y)
inline val FVec3.xzzz get() = FVec4(x, z, z, z)
inline val FVec3.yxxx get() = FVec4(y, x, x, x)
inline val FVec3.yxxy get() = FVec4(y, x, x, y)
inline val FVec3.yxxz get() = FVec4(y, x, x, z)
inline val FVec3.yxyx get() = FVec4(y, x, y, x)
inline val FVec3.yxyy get() = FVec4(y, x, y, y)
inline val FVec3.yxyz get() = FVec4(y, x, y, z)
inline val FVec3.yxzx get() = FVec4(y, x, z, x)
inline val FVec3.yxzy get() = FVec4(y, x, z, y)
inline val FVec3.yxzz get() = FVec4(y, x, z, z)
inline val FVec3.yyxx get() = FVec4(y, y, x, x)
inline val FVec3.yyxy get() = FVec4(y, y, x, y)
inline val FVec3.yyxz get() = FVec4(y, y, x, z)
inline val FVec3.yyyx get() = FVec4(y, y, y, x)
inline val FVec3.yyyy get() = FVec4(y, y, y, y)
inline val FVec3.yyyz get() = FVec4(y, y, y, z)
inline val FVec3.yyzx get() = FVec4(y, y, z, x)
inline val FVec3.yyzy get() = FVec4(y, y, z, y)
inline val FVec3.yyzz get() = FVec4(y, y, z, z)
inline val FVec3.yzxx get() = FVec4(y, z, x, x)
inline val FVec3.yzxy get() = FVec4(y, z, x, y)
inline val FVec3.yzxz get() = FVec4(y, z, x, z)
inline val FVec3.yzyx get() = FVec4(y, z, y, x)
inline val FVec3.yzyy get() = FVec4(y, z, y, y)
inline val FVec3.yzyz get() = FVec4(y, z, y, z)
inline val FVec3.yzzx get() = FVec4(y, z, z, x)
inline val FVec3.yzzy get() = FVec4(y, z, z, y)
inline val FVec3.yzzz get() = FVec4(y, z, z, z)
inline val FVec3.zxxx get() = FVec4(z, x, x, x)
inline val FVec3.zxxy get() = FVec4(z, x, x, y)
inline val FVec3.zxxz get() = FVec4(z, x, x, z)
inline val FVec3.zxyx get() = FVec4(z, x, y, x)
inline val FVec3.zxyy get() = FVec4(z, x, y, y)
inline val FVec3.zxyz get() = FVec4(z, x, y, z)
inline val FVec3.zxzx get() = FVec4(z, x, z, x)
inline val FVec3.zxzy get() = FVec4(z, x, z, y)
inline val FVec3.zxzz get() = FVec4(z, x, z, z)
inline val FVec3.zyxx get() = FVec4(z, y, x, x)
inline val FVec3.zyxy get() = FVec4(z, y, x, y)
inline val FVec3.zyxz get() = FVec4(z, y, x, z)
inline val FVec3.zyyx get() = FVec4(z, y, y, x)
inline val FVec3.zyyy get() = FVec4(z, y, y, y)
inline val FVec3.zyyz get() = FVec4(z, y, y, z)
inline val FVec3.zyzx get() = FVec4(z, y, z, x)
inline val FVec3.zyzy get() = FVec4(z, y, z, y)
inline val FVec3.zyzz get() = FVec4(z, y, z, z)
inline val FVec3.zzxx get() = FVec4(z, z, x, x)
inline val FVec3.zzxy get() = FVec4(z, z, x, y)
inline val FVec3.zzxz get() = FVec4(z, z, x, z)
inline val FVec3.zzyx get() = FVec4(z, z, y, x)
inline val FVec3.zzyy get() = FVec4(z, z, y, y)
inline val FVec3.zzyz get() = FVec4(z, z, y, z)
inline val FVec3.zzzx get() = FVec4(z, z, z, x)
inline val FVec3.zzzy get() = FVec4(z, z, z, y)
inline val FVec3.zzzz get() = FVec4(z, z, z, z)

inline val FVec3.rrrr get() = FVec4(r, r, r, r)
inline val FVec3.rrrg get() = FVec4(r, r, r, g)
inline val FVec3.rrrb get() = FVec4(r, r, r, b)
inline val FVec3.rrgr get() = FVec4(r, r, g, r)
inline val FVec3.rrgg get() = FVec4(r, r, g, g)
inline val FVec3.rrgb get() = FVec4(r, r, g, b)
inline val FVec3.rrbr get() = FVec4(r, r, b, r)
inline val FVec3.rrbg get() = FVec4(r, r, b, g)
inline val FVec3.rrbb get() = FVec4(r, r, b, b)
inline val FVec3.rgrr get() = FVec4(r, g, r, r)
inline val FVec3.rgrg get() = FVec4(r, g, r, g)
inline val FVec3.rgrb get() = FVec4(r, g, r, b)
inline val FVec3.rggr get() = FVec4(r, g, g, r)
inline val FVec3.rggg get() = FVec4(r, g, g, g)
inline val FVec3.rggb get() = FVec4(r, g, g, b)
inline val FVec3.rgbr get() = FVec4(r, g, b, r)
inline val FVec3.rgbg get() = FVec4(r, g, b, g)
inline val FVec3.rgbb get() = FVec4(r, g, b, b)
inline val FVec3.rbrr get() = FVec4(r, b, r, r)
inline val FVec3.rbrg get() = FVec4(r, b, r, g)
inline val FVec3.rbrb get() = FVec4(r, b, r, b)
inline val FVec3.rbgr get() = FVec4(r, b, g, r)
inline val FVec3.rbgg get() = FVec4(r, b, g, g)
inline val FVec3.rbgb get() = FVec4(r, b, g, b)
inline val FVec3.rbbr get() = FVec4(r, b, b, r)
inline val FVec3.rbbg get() = FVec4(r, b, b, g)
inline val FVec3.rbbb get() = FVec4(r, b, b, b)
inline val FVec3.grrr get() = FVec4(g, r, r, r)
inline val FVec3.grrg get() = FVec4(g, r, r, g)
inline val FVec3.grrb get() = FVec4(g, r, r, b)
inline val FVec3.grgr get() = FVec4(g, r, g, r)
inline val FVec3.grgg get() = FVec4(g, r, g, g)
inline val FVec3.grgb get() = FVec4(g, r, g, b)
inline val FVec3.grbr get() = FVec4(g, r, b, r)
inline val FVec3.grbg get() = FVec4(g, r, b, g)
inline val FVec3.grbb get() = FVec4(g, r, b, b)
inline val FVec3.ggrr get() = FVec4(g, g, r, r)
inline val FVec3.ggrg get() = FVec4(g, g, r, g)
inline val FVec3.ggrb get() = FVec4(g, g, r, b)
inline val FVec3.gggr get() = FVec4(g, g, g, r)
inline val FVec3.gggg get() = FVec4(g, g, g, g)
inline val FVec3.gggb get() = FVec4(g, g, g, b)
inline val FVec3.ggbr get() = FVec4(g, g, b, r)
inline val FVec3.ggbg get() = FVec4(g, g, b, g)
inline val FVec3.ggbb get() = FVec4(g, g, b, b)
inline val FVec3.gbrr get() = FVec4(g, b, r, r)
inline val FVec3.gbrg get() = FVec4(g, b, r, g)
inline val FVec3.gbrb get() = FVec4(g, b, r, b)
inline val FVec3.gbgr get() = FVec4(g, b, g, r)
inline val FVec3.gbgg get() = FVec4(g, b, g, g)
inline val FVec3.gbgb get() = FVec4(g, b, g, b)
inline val FVec3.gbbr get() = FVec4(g, b, b, r)
inline val FVec3.gbbg get() = FVec4(g, b, b, g)
inline val FVec3.gbbb get() = FVec4(g, b, b, b)
inline val FVec3.brrr get() = FVec4(b, r, r, r)
inline val FVec3.brrg get() = FVec4(b, r, r, g)
inline val FVec3.brrb get() = FVec4(b, r, r, b)
inline val FVec3.brgr get() = FVec4(b, r, g, r)
inline val FVec3.brgg get() = FVec4(b, r, g, g)
inline val FVec3.brgb get() = FVec4(b, r, g, b)
inline val FVec3.brbr get() = FVec4(b, r, b, r)
inline val FVec3.brbg get() = FVec4(b, r, b, g)
inline val FVec3.brbb get() = FVec4(b, r, b, b)
inline val FVec3.bgrr get() = FVec4(b, g, r, r)
inline val FVec3.bgrg get() = FVec4(b, g, r, g)
inline val FVec3.bgrb get() = FVec4(b, g, r, b)
inline val FVec3.bggr get() = FVec4(b, g, g, r)
inline val FVec3.bggg get() = FVec4(b, g, g, g)
inline val FVec3.bggb get() = FVec4(b, g, g, b)
inline val FVec3.bgbr get() = FVec4(b, g, b, r)
inline val FVec3.bgbg get() = FVec4(b, g, b, g)
inline val FVec3.bgbb get() = FVec4(b, g, b, b)
inline val FVec3.bbrr get() = FVec4(b, b, r, r)
inline val FVec3.bbrg get() = FVec4(b, b, r, g)
inline val FVec3.bbrb get() = FVec4(b, b, r, b)
inline val FVec3.bbgr get() = FVec4(b, b, g, r)
inline val FVec3.bbgg get() = FVec4(b, b, g, g)
inline val FVec3.bbgb get() = FVec4(b, b, g, b)
inline val FVec3.bbbr get() = FVec4(b, b, b, r)
inline val FVec3.bbbg get() = FVec4(b, b, b, g)
inline val FVec3.bbbb get() = FVec4(b, b, b, b)

inline val FVec3.ssss get() = FVec4(s, s, s, s)
inline val FVec3.ssst get() = FVec4(s, s, s, t)
inline val FVec3.sssp get() = FVec4(s, s, s, p)
inline val FVec3.ssts get() = FVec4(s, s, t, s)
inline val FVec3.sstt get() = FVec4(s, s, t, t)
inline val FVec3.sstp get() = FVec4(s, s, t, p)
inline val FVec3.ssps get() = FVec4(s, s, p, s)
inline val FVec3.sspt get() = FVec4(s, s, p, t)
inline val FVec3.sspp get() = FVec4(s, s, p, p)
inline val FVec3.stss get() = FVec4(s, t, s, s)
inline val FVec3.stst get() = FVec4(s, t, s, t)
inline val FVec3.stsp get() = FVec4(s, t, s, p)
inline val FVec3.stts get() = FVec4(s, t, t, s)
inline val FVec3.sttt get() = FVec4(s, t, t, t)
inline val FVec3.sttp get() = FVec4(s, t, t, p)
inline val FVec3.stps get() = FVec4(s, t, p, s)
inline val FVec3.stpt get() = FVec4(s, t, p, t)
inline val FVec3.stpp get() = FVec4(s, t, p, p)
inline val FVec3.spss get() = FVec4(s, p, s, s)
inline val FVec3.spst get() = FVec4(s, p, s, t)
inline val FVec3.spsp get() = FVec4(s, p, s, p)
inline val FVec3.spts get() = FVec4(s, p, t, s)
inline val FVec3.sptt get() = FVec4(s, p, t, t)
inline val FVec3.sptp get() = FVec4(s, p, t, p)
inline val FVec3.spps get() = FVec4(s, p, p, s)
inline val FVec3.sppt get() = FVec4(s, p, p, t)
inline val FVec3.sppp get() = FVec4(s, p, p, p)
inline val FVec3.tsss get() = FVec4(t, s, s, s)
inline val FVec3.tsst get() = FVec4(t, s, s, t)
inline val FVec3.tssp get() = FVec4(t, s, s, p)
inline val FVec3.tsts get() = FVec4(t, s, t, s)
inline val FVec3.tstt get() = FVec4(t, s, t, t)
inline val FVec3.tstp get() = FVec4(t, s, t, p)
inline val FVec3.tsps get() = FVec4(t, s, p, s)
inline val FVec3.tspt get() = FVec4(t, s, p, t)
inline val FVec3.tspp get() = FVec4(t, s, p, p)
inline val FVec3.ttss get() = FVec4(t, t, s, s)
inline val FVec3.ttst get() = FVec4(t, t, s, t)
inline val FVec3.ttsp get() = FVec4(t, t, s, p)
inline val FVec3.ttts get() = FVec4(t, t, t, s)
inline val FVec3.tttt get() = FVec4(t, t, t, t)
inline val FVec3.tttp get() = FVec4(t, t, t, p)
inline val FVec3.ttps get() = FVec4(t, t, p, s)
inline val FVec3.ttpt get() = FVec4(t, t, p, t)
inline val FVec3.ttpp get() = FVec4(t, t, p, p)
inline val FVec3.tpss get() = FVec4(t, p, s, s)
inline val FVec3.tpst get() = FVec4(t, p, s, t)
inline val FVec3.tpsp get() = FVec4(t, p, s, p)
inline val FVec3.tpts get() = FVec4(t, p, t, s)
inline val FVec3.tptt get() = FVec4(t, p, t, t)
inline val FVec3.tptp get() = FVec4(t, p, t, p)
inline val FVec3.tpps get() = FVec4(t, p, p, s)
inline val FVec3.tppt get() = FVec4(t, p, p, t)
inline val FVec3.tppp get() = FVec4(t, p, p, p)
inline val FVec3.psss get() = FVec4(p, s, s, s)
inline val FVec3.psst get() = FVec4(p, s, s, t)
inline val FVec3.pssp get() = FVec4(p, s, s, p)
inline val FVec3.psts get() = FVec4(p, s, t, s)
inline val FVec3.pstt get() = FVec4(p, s, t, t)
inline val FVec3.pstp get() = FVec4(p, s, t, p)
inline val FVec3.psps get() = FVec4(p, s, p, s)
inline val FVec3.pspt get() = FVec4(p, s, p, t)
inline val FVec3.pspp get() = FVec4(p, s, p, p)
inline val FVec3.ptss get() = FVec4(p, t, s, s)
inline val FVec3.ptst get() = FVec4(p, t, s, t)
inline val FVec3.ptsp get() = FVec4(p, t, s, p)
inline val FVec3.ptts get() = FVec4(p, t, t, s)
inline val FVec3.pttt get() = FVec4(p, t, t, t)
inline val FVec3.pttp get() = FVec4(p, t, t, p)
inline val FVec3.ptps get() = FVec4(p, t, p, s)
inline val FVec3.ptpt get() = FVec4(p, t, p, t)
inline val FVec3.ptpp get() = FVec4(p, t, p, p)
inline val FVec3.ppss get() = FVec4(p, p, s, s)
inline val FVec3.ppst get() = FVec4(p, p, s, t)
inline val FVec3.ppsp get() = FVec4(p, p, s, p)
inline val FVec3.ppts get() = FVec4(p, p, t, s)
inline val FVec3.pptt get() = FVec4(p, p, t, t)
inline val FVec3.pptp get() = FVec4(p, p, t, p)
inline val FVec3.ppps get() = FVec4(p, p, p, s)
inline val FVec3.pppt get() = FVec4(p, p, p, t)
inline val FVec3.pppp get() = FVec4(p, p, p, p)
//endregion

//region Swizzling Vec4
inline val FVec4.xx get() = FVec2(x, x)
inline val FVec4.xy get() = FVec2(x, y)
inline val FVec4.xz get() = FVec2(x, z)
inline val FVec4.xw get() = FVec2(x, w)
inline val FVec4.yx get() = FVec2(y, x)
inline val FVec4.yy get() = FVec2(y, y)
inline val FVec4.yz get() = FVec2(y, z)
inline val FVec4.yw get() = FVec2(y, w)
inline val FVec4.zx get() = FVec2(z, x)
inline val FVec4.zy get() = FVec2(z, y)
inline val FVec4.zz get() = FVec2(z, z)
inline val FVec4.zw get() = FVec2(z, w)
inline val FVec4.wx get() = FVec2(w, x)
inline val FVec4.wy get() = FVec2(w, y)
inline val FVec4.wz get() = FVec2(w, z)
inline val FVec4.ww get() = FVec2(w, w)

inline val FVec4.rr get() = FVec2(r, r)
inline val FVec4.rg get() = FVec2(r, g)
inline val FVec4.rb get() = FVec2(r, b)
inline val FVec4.ra get() = FVec2(r, a)
inline val FVec4.gr get() = FVec2(g, r)
inline val FVec4.gg get() = FVec2(g, g)
inline val FVec4.gb get() = FVec2(g, b)
inline val FVec4.ga get() = FVec2(g, a)
inline val FVec4.br get() = FVec2(b, r)
inline val FVec4.bg get() = FVec2(b, g)
inline val FVec4.bb get() = FVec2(b, b)
inline val FVec4.ba get() = FVec2(b, a)
inline val FVec4.ar get() = FVec2(a, r)
inline val FVec4.ag get() = FVec2(a, g)
inline val FVec4.ab get() = FVec2(a, b)
inline val FVec4.aa get() = FVec2(a, a)

inline val FVec4.ss get() = FVec2(s, s)
inline val FVec4.st get() = FVec2(s, t)
inline val FVec4.sp get() = FVec2(s, p)
inline val FVec4.sq get() = FVec2(s, q)
inline val FVec4.ts get() = FVec2(t, s)
inline val FVec4.tt get() = FVec2(t, t)
inline val FVec4.tp get() = FVec2(t, p)
inline val FVec4.tq get() = FVec2(t, q)
inline val FVec4.ps get() = FVec2(p, s)
inline val FVec4.pt get() = FVec2(p, t)
inline val FVec4.pp get() = FVec2(p, p)
inline val FVec4.pq get() = FVec2(p, q)
inline val FVec4.qs get() = FVec2(q, s)
inline val FVec4.qt get() = FVec2(q, t)
inline val FVec4.qp get() = FVec2(q, p)
inline val FVec4.qq get() = FVec2(q, q)

inline val FVec4.xxx get() = FVec3(x, x, x)
inline val FVec4.xxy get() = FVec3(x, x, y)
inline val FVec4.xxz get() = FVec3(x, x, z)
inline val FVec4.xxw get() = FVec3(x, x, w)
inline val FVec4.xyx get() = FVec3(x, y, x)
inline val FVec4.xyy get() = FVec3(x, y, y)
inline val FVec4.xyz get() = FVec3(x, y, z)
inline val FVec4.xyw get() = FVec3(x, y, w)
inline val FVec4.xzx get() = FVec3(x, z, x)
inline val FVec4.xzy get() = FVec3(x, z, y)
inline val FVec4.xzz get() = FVec3(x, z, z)
inline val FVec4.xzw get() = FVec3(x, z, w)
inline val FVec4.xwx get() = FVec3(x, w, x)
inline val FVec4.xwy get() = FVec3(x, w, y)
inline val FVec4.xwz get() = FVec3(x, w, z)
inline val FVec4.xww get() = FVec3(x, w, w)
inline val FVec4.yxx get() = FVec3(y, x, x)
inline val FVec4.yxy get() = FVec3(y, x, y)
inline val FVec4.yxz get() = FVec3(y, x, z)
inline val FVec4.yxw get() = FVec3(y, x, w)
inline val FVec4.yyx get() = FVec3(y, y, x)
inline val FVec4.yyy get() = FVec3(y, y, y)
inline val FVec4.yyz get() = FVec3(y, y, z)
inline val FVec4.yyw get() = FVec3(y, y, w)
inline val FVec4.yzx get() = FVec3(y, z, x)
inline val FVec4.yzy get() = FVec3(y, z, y)
inline val FVec4.yzz get() = FVec3(y, z, z)
inline val FVec4.yzw get() = FVec3(y, z, w)
inline val FVec4.ywx get() = FVec3(y, w, x)
inline val FVec4.ywy get() = FVec3(y, w, y)
inline val FVec4.ywz get() = FVec3(y, w, z)
inline val FVec4.yww get() = FVec3(y, w, w)
inline val FVec4.zxx get() = FVec3(z, x, x)
inline val FVec4.zxy get() = FVec3(z, x, y)
inline val FVec4.zxz get() = FVec3(z, x, z)
inline val FVec4.zxw get() = FVec3(z, x, w)
inline val FVec4.zyx get() = FVec3(z, y, x)
inline val FVec4.zyy get() = FVec3(z, y, y)
inline val FVec4.zyz get() = FVec3(z, y, z)
inline val FVec4.zyw get() = FVec3(z, y, w)
inline val FVec4.zzx get() = FVec3(z, z, x)
inline val FVec4.zzy get() = FVec3(z, z, y)
inline val FVec4.zzz get() = FVec3(z, z, z)
inline val FVec4.zzw get() = FVec3(z, z, w)
inline val FVec4.zwx get() = FVec3(z, w, x)
inline val FVec4.zwy get() = FVec3(z, w, y)
inline val FVec4.zwz get() = FVec3(z, w, z)
inline val FVec4.zww get() = FVec3(z, w, w)
inline val FVec4.wxx get() = FVec3(w, x, x)
inline val FVec4.wxy get() = FVec3(w, x, y)
inline val FVec4.wxz get() = FVec3(w, x, z)
inline val FVec4.wxw get() = FVec3(w, x, w)
inline val FVec4.wyx get() = FVec3(w, y, x)
inline val FVec4.wyy get() = FVec3(w, y, y)
inline val FVec4.wyz get() = FVec3(w, y, z)
inline val FVec4.wyw get() = FVec3(w, y, w)
inline val FVec4.wzx get() = FVec3(w, z, x)
inline val FVec4.wzy get() = FVec3(w, z, y)
inline val FVec4.wzz get() = FVec3(w, z, z)
inline val FVec4.wzw get() = FVec3(w, z, w)
inline val FVec4.wwx get() = FVec3(w, w, x)
inline val FVec4.wwy get() = FVec3(w, w, y)
inline val FVec4.wwz get() = FVec3(w, w, z)
inline val FVec4.www get() = FVec3(w, w, w)

inline val FVec4.rrr get() = FVec3(r, r, r)
inline val FVec4.rrg get() = FVec3(r, r, g)
inline val FVec4.rrb get() = FVec3(r, r, b)
inline val FVec4.rra get() = FVec3(r, r, a)
inline val FVec4.rgr get() = FVec3(r, g, r)
inline val FVec4.rgg get() = FVec3(r, g, g)
inline val FVec4.rgb get() = FVec3(r, g, b)
inline val FVec4.rga get() = FVec3(r, g, a)
inline val FVec4.rbr get() = FVec3(r, b, r)
inline val FVec4.rbg get() = FVec3(r, b, g)
inline val FVec4.rbb get() = FVec3(r, b, b)
inline val FVec4.rba get() = FVec3(r, b, a)
inline val FVec4.rar get() = FVec3(r, a, r)
inline val FVec4.rag get() = FVec3(r, a, g)
inline val FVec4.rab get() = FVec3(r, a, b)
inline val FVec4.raa get() = FVec3(r, a, a)
inline val FVec4.grr get() = FVec3(g, r, r)
inline val FVec4.grg get() = FVec3(g, r, g)
inline val FVec4.grb get() = FVec3(g, r, b)
inline val FVec4.gra get() = FVec3(g, r, a)
inline val FVec4.ggr get() = FVec3(g, g, r)
inline val FVec4.ggg get() = FVec3(g, g, g)
inline val FVec4.ggb get() = FVec3(g, g, b)
inline val FVec4.gga get() = FVec3(g, g, a)
inline val FVec4.gbr get() = FVec3(g, b, r)
inline val FVec4.gbg get() = FVec3(g, b, g)
inline val FVec4.gbb get() = FVec3(g, b, b)
inline val FVec4.gba get() = FVec3(g, b, a)
inline val FVec4.gar get() = FVec3(g, a, r)
inline val FVec4.gag get() = FVec3(g, a, g)
inline val FVec4.gab get() = FVec3(g, a, b)
inline val FVec4.gaa get() = FVec3(g, a, a)
inline val FVec4.brr get() = FVec3(b, r, r)
inline val FVec4.brg get() = FVec3(b, r, g)
inline val FVec4.brb get() = FVec3(b, r, b)
inline val FVec4.bra get() = FVec3(b, r, a)
inline val FVec4.bgr get() = FVec3(b, g, r)
inline val FVec4.bgg get() = FVec3(b, g, g)
inline val FVec4.bgb get() = FVec3(b, g, b)
inline val FVec4.bga get() = FVec3(b, g, a)
inline val FVec4.bbr get() = FVec3(b, b, r)
inline val FVec4.bbg get() = FVec3(b, b, g)
inline val FVec4.bbb get() = FVec3(b, b, b)
inline val FVec4.bba get() = FVec3(b, b, a)
inline val FVec4.bar get() = FVec3(b, a, r)
inline val FVec4.bag get() = FVec3(b, a, g)
inline val FVec4.bab get() = FVec3(b, a, b)
inline val FVec4.baa get() = FVec3(b, a, a)
inline val FVec4.arr get() = FVec3(a, r, r)
inline val FVec4.arg get() = FVec3(a, r, g)
inline val FVec4.arb get() = FVec3(a, r, b)
inline val FVec4.ara get() = FVec3(a, r, a)
inline val FVec4.agr get() = FVec3(a, g, r)
inline val FVec4.agg get() = FVec3(a, g, g)
inline val FVec4.agb get() = FVec3(a, g, b)
inline val FVec4.aga get() = FVec3(a, g, a)
inline val FVec4.abr get() = FVec3(a, b, r)
inline val FVec4.abg get() = FVec3(a, b, g)
inline val FVec4.abb get() = FVec3(a, b, b)
inline val FVec4.aba get() = FVec3(a, b, a)
inline val FVec4.aar get() = FVec3(a, a, r)
inline val FVec4.aag get() = FVec3(a, a, g)
inline val FVec4.aab get() = FVec3(a, a, b)
inline val FVec4.aaa get() = FVec3(a, a, a)

inline val FVec4.sss get() = FVec3(s, s, s)
inline val FVec4.sst get() = FVec3(s, s, t)
inline val FVec4.ssp get() = FVec3(s, s, p)
inline val FVec4.ssq get() = FVec3(s, s, q)
inline val FVec4.sts get() = FVec3(s, t, s)
inline val FVec4.stt get() = FVec3(s, t, t)
inline val FVec4.stp get() = FVec3(s, t, p)
inline val FVec4.stq get() = FVec3(s, t, q)
inline val FVec4.sps get() = FVec3(s, p, s)
inline val FVec4.spt get() = FVec3(s, p, t)
inline val FVec4.spp get() = FVec3(s, p, p)
inline val FVec4.spq get() = FVec3(s, p, q)
inline val FVec4.sqs get() = FVec3(s, q, s)
inline val FVec4.sqt get() = FVec3(s, q, t)
inline val FVec4.sqp get() = FVec3(s, q, p)
inline val FVec4.sqq get() = FVec3(s, q, q)
inline val FVec4.tss get() = FVec3(t, s, s)
inline val FVec4.tst get() = FVec3(t, s, t)
inline val FVec4.tsp get() = FVec3(t, s, p)
inline val FVec4.tsq get() = FVec3(t, s, q)
inline val FVec4.tts get() = FVec3(t, t, s)
inline val FVec4.ttt get() = FVec3(t, t, t)
inline val FVec4.ttp get() = FVec3(t, t, p)
inline val FVec4.ttq get() = FVec3(t, t, q)
inline val FVec4.tps get() = FVec3(t, p, s)
inline val FVec4.tpt get() = FVec3(t, p, t)
inline val FVec4.tpp get() = FVec3(t, p, p)
inline val FVec4.tpq get() = FVec3(t, p, q)
inline val FVec4.tqs get() = FVec3(t, q, s)
inline val FVec4.tqt get() = FVec3(t, q, t)
inline val FVec4.tqp get() = FVec3(t, q, p)
inline val FVec4.tqq get() = FVec3(t, q, q)
inline val FVec4.pss get() = FVec3(p, s, s)
inline val FVec4.pst get() = FVec3(p, s, t)
inline val FVec4.psp get() = FVec3(p, s, p)
inline val FVec4.psq get() = FVec3(p, s, q)
inline val FVec4.pts get() = FVec3(p, t, s)
inline val FVec4.ptt get() = FVec3(p, t, t)
inline val FVec4.ptp get() = FVec3(p, t, p)
inline val FVec4.ptq get() = FVec3(p, t, q)
inline val FVec4.pps get() = FVec3(p, p, s)
inline val FVec4.ppt get() = FVec3(p, p, t)
inline val FVec4.ppp get() = FVec3(p, p, p)
inline val FVec4.ppq get() = FVec3(p, p, q)
inline val FVec4.pqs get() = FVec3(p, q, s)
inline val FVec4.pqt get() = FVec3(p, q, t)
inline val FVec4.pqp get() = FVec3(p, q, p)
inline val FVec4.pqq get() = FVec3(p, q, q)
inline val FVec4.qss get() = FVec3(q, s, s)
inline val FVec4.qst get() = FVec3(q, s, t)
inline val FVec4.qsp get() = FVec3(q, s, p)
inline val FVec4.qsq get() = FVec3(q, s, q)
inline val FVec4.qts get() = FVec3(q, t, s)
inline val FVec4.qtt get() = FVec3(q, t, t)
inline val FVec4.qtp get() = FVec3(q, t, p)
inline val FVec4.qtq get() = FVec3(q, t, q)
inline val FVec4.qps get() = FVec3(q, p, s)
inline val FVec4.qpt get() = FVec3(q, p, t)
inline val FVec4.qpp get() = FVec3(q, p, p)
inline val FVec4.qpq get() = FVec3(q, p, q)
inline val FVec4.qqs get() = FVec3(q, q, s)
inline val FVec4.qqt get() = FVec3(q, q, t)
inline val FVec4.qqp get() = FVec3(q, q, p)
inline val FVec4.qqq get() = FVec3(q, q, q)

inline val FVec4.xxxx get() = FVec4(x, x, x, x)
inline val FVec4.xxxy get() = FVec4(x, x, x, y)
inline val FVec4.xxxz get() = FVec4(x, x, x, z)
inline val FVec4.xxxw get() = FVec4(x, x, x, w)
inline val FVec4.xxyx get() = FVec4(x, x, y, x)
inline val FVec4.xxyy get() = FVec4(x, x, y, y)
inline val FVec4.xxyz get() = FVec4(x, x, y, z)
inline val FVec4.xxyw get() = FVec4(x, x, y, w)
inline val FVec4.xxzx get() = FVec4(x, x, z, x)
inline val FVec4.xxzy get() = FVec4(x, x, z, y)
inline val FVec4.xxzz get() = FVec4(x, x, z, z)
inline val FVec4.xxzw get() = FVec4(x, x, z, w)
inline val FVec4.xxwx get() = FVec4(x, x, w, x)
inline val FVec4.xxwy get() = FVec4(x, x, w, y)
inline val FVec4.xxwz get() = FVec4(x, x, w, z)
inline val FVec4.xxww get() = FVec4(x, x, w, w)
inline val FVec4.xyxx get() = FVec4(x, y, x, x)
inline val FVec4.xyxy get() = FVec4(x, y, x, y)
inline val FVec4.xyxz get() = FVec4(x, y, x, z)
inline val FVec4.xyxw get() = FVec4(x, y, x, w)
inline val FVec4.xyyx get() = FVec4(x, y, y, x)
inline val FVec4.xyyy get() = FVec4(x, y, y, y)
inline val FVec4.xyyz get() = FVec4(x, y, y, z)
inline val FVec4.xyyw get() = FVec4(x, y, y, w)
inline val FVec4.xyzx get() = FVec4(x, y, z, x)
inline val FVec4.xyzy get() = FVec4(x, y, z, y)
inline val FVec4.xyzz get() = FVec4(x, y, z, z)
inline val FVec4.xyzw get() = FVec4(x, y, z, w)
inline val FVec4.xywx get() = FVec4(x, y, w, x)
inline val FVec4.xywy get() = FVec4(x, y, w, y)
inline val FVec4.xywz get() = FVec4(x, y, w, z)
inline val FVec4.xyww get() = FVec4(x, y, w, w)
inline val FVec4.xzxx get() = FVec4(x, z, x, x)
inline val FVec4.xzxy get() = FVec4(x, z, x, y)
inline val FVec4.xzxz get() = FVec4(x, z, x, z)
inline val FVec4.xzxw get() = FVec4(x, z, x, w)
inline val FVec4.xzyx get() = FVec4(x, z, y, x)
inline val FVec4.xzyy get() = FVec4(x, z, y, y)
inline val FVec4.xzyz get() = FVec4(x, z, y, z)
inline val FVec4.xzyw get() = FVec4(x, z, y, w)
inline val FVec4.xzzx get() = FVec4(x, z, z, x)
inline val FVec4.xzzy get() = FVec4(x, z, z, y)
inline val FVec4.xzzz get() = FVec4(x, z, z, z)
inline val FVec4.xzzw get() = FVec4(x, z, z, w)
inline val FVec4.xzwx get() = FVec4(x, z, w, x)
inline val FVec4.xzwy get() = FVec4(x, z, w, y)
inline val FVec4.xzwz get() = FVec4(x, z, w, z)
inline val FVec4.xzww get() = FVec4(x, z, w, w)
inline val FVec4.xwxx get() = FVec4(x, w, x, x)
inline val FVec4.xwxy get() = FVec4(x, w, x, y)
inline val FVec4.xwxz get() = FVec4(x, w, x, z)
inline val FVec4.xwxw get() = FVec4(x, w, x, w)
inline val FVec4.xwyx get() = FVec4(x, w, y, x)
inline val FVec4.xwyy get() = FVec4(x, w, y, y)
inline val FVec4.xwyz get() = FVec4(x, w, y, z)
inline val FVec4.xwyw get() = FVec4(x, w, y, w)
inline val FVec4.xwzx get() = FVec4(x, w, z, x)
inline val FVec4.xwzy get() = FVec4(x, w, z, y)
inline val FVec4.xwzz get() = FVec4(x, w, z, z)
inline val FVec4.xwzw get() = FVec4(x, w, z, w)
inline val FVec4.xwwx get() = FVec4(x, w, w, x)
inline val FVec4.xwwy get() = FVec4(x, w, w, y)
inline val FVec4.xwwz get() = FVec4(x, w, w, z)
inline val FVec4.xwww get() = FVec4(x, w, w, w)
inline val FVec4.yxxx get() = FVec4(y, x, x, x)
inline val FVec4.yxxy get() = FVec4(y, x, x, y)
inline val FVec4.yxxz get() = FVec4(y, x, x, z)
inline val FVec4.yxxw get() = FVec4(y, x, x, w)
inline val FVec4.yxyx get() = FVec4(y, x, y, x)
inline val FVec4.yxyy get() = FVec4(y, x, y, y)
inline val FVec4.yxyz get() = FVec4(y, x, y, z)
inline val FVec4.yxyw get() = FVec4(y, x, y, w)
inline val FVec4.yxzx get() = FVec4(y, x, z, x)
inline val FVec4.yxzy get() = FVec4(y, x, z, y)
inline val FVec4.yxzz get() = FVec4(y, x, z, z)
inline val FVec4.yxzw get() = FVec4(y, x, z, w)
inline val FVec4.yxwx get() = FVec4(y, x, w, x)
inline val FVec4.yxwy get() = FVec4(y, x, w, y)
inline val FVec4.yxwz get() = FVec4(y, x, w, z)
inline val FVec4.yxww get() = FVec4(y, x, w, w)
inline val FVec4.yyxx get() = FVec4(y, y, x, x)
inline val FVec4.yyxy get() = FVec4(y, y, x, y)
inline val FVec4.yyxz get() = FVec4(y, y, x, z)
inline val FVec4.yyxw get() = FVec4(y, y, x, w)
inline val FVec4.yyyx get() = FVec4(y, y, y, x)
inline val FVec4.yyyy get() = FVec4(y, y, y, y)
inline val FVec4.yyyz get() = FVec4(y, y, y, z)
inline val FVec4.yyyw get() = FVec4(y, y, y, w)
inline val FVec4.yyzx get() = FVec4(y, y, z, x)
inline val FVec4.yyzy get() = FVec4(y, y, z, y)
inline val FVec4.yyzz get() = FVec4(y, y, z, z)
inline val FVec4.yyzw get() = FVec4(y, y, z, w)
inline val FVec4.yywx get() = FVec4(y, y, w, x)
inline val FVec4.yywy get() = FVec4(y, y, w, y)
inline val FVec4.yywz get() = FVec4(y, y, w, z)
inline val FVec4.yyww get() = FVec4(y, y, w, w)
inline val FVec4.yzxx get() = FVec4(y, z, x, x)
inline val FVec4.yzxy get() = FVec4(y, z, x, y)
inline val FVec4.yzxz get() = FVec4(y, z, x, z)
inline val FVec4.yzxw get() = FVec4(y, z, x, w)
inline val FVec4.yzyx get() = FVec4(y, z, y, x)
inline val FVec4.yzyy get() = FVec4(y, z, y, y)
inline val FVec4.yzyz get() = FVec4(y, z, y, z)
inline val FVec4.yzyw get() = FVec4(y, z, y, w)
inline val FVec4.yzzx get() = FVec4(y, z, z, x)
inline val FVec4.yzzy get() = FVec4(y, z, z, y)
inline val FVec4.yzzz get() = FVec4(y, z, z, z)
inline val FVec4.yzzw get() = FVec4(y, z, z, w)
inline val FVec4.yzwx get() = FVec4(y, z, w, x)
inline val FVec4.yzwy get() = FVec4(y, z, w, y)
inline val FVec4.yzwz get() = FVec4(y, z, w, z)
inline val FVec4.yzww get() = FVec4(y, z, w, w)
inline val FVec4.ywxx get() = FVec4(y, w, x, x)
inline val FVec4.ywxy get() = FVec4(y, w, x, y)
inline val FVec4.ywxz get() = FVec4(y, w, x, z)
inline val FVec4.ywxw get() = FVec4(y, w, x, w)
inline val FVec4.ywyx get() = FVec4(y, w, y, x)
inline val FVec4.ywyy get() = FVec4(y, w, y, y)
inline val FVec4.ywyz get() = FVec4(y, w, y, z)
inline val FVec4.ywyw get() = FVec4(y, w, y, w)
inline val FVec4.ywzx get() = FVec4(y, w, z, x)
inline val FVec4.ywzy get() = FVec4(y, w, z, y)
inline val FVec4.ywzz get() = FVec4(y, w, z, z)
inline val FVec4.ywzw get() = FVec4(y, w, z, w)
inline val FVec4.ywwx get() = FVec4(y, w, w, x)
inline val FVec4.ywwy get() = FVec4(y, w, w, y)
inline val FVec4.ywwz get() = FVec4(y, w, w, z)
inline val FVec4.ywww get() = FVec4(y, w, w, w)
inline val FVec4.zxxx get() = FVec4(z, x, x, x)
inline val FVec4.zxxy get() = FVec4(z, x, x, y)
inline val FVec4.zxxz get() = FVec4(z, x, x, z)
inline val FVec4.zxxw get() = FVec4(z, x, x, w)
inline val FVec4.zxyx get() = FVec4(z, x, y, x)
inline val FVec4.zxyy get() = FVec4(z, x, y, y)
inline val FVec4.zxyz get() = FVec4(z, x, y, z)
inline val FVec4.zxyw get() = FVec4(z, x, y, w)
inline val FVec4.zxzx get() = FVec4(z, x, z, x)
inline val FVec4.zxzy get() = FVec4(z, x, z, y)
inline val FVec4.zxzz get() = FVec4(z, x, z, z)
inline val FVec4.zxzw get() = FVec4(z, x, z, w)
inline val FVec4.zxwx get() = FVec4(z, x, w, x)
inline val FVec4.zxwy get() = FVec4(z, x, w, y)
inline val FVec4.zxwz get() = FVec4(z, x, w, z)
inline val FVec4.zxww get() = FVec4(z, x, w, w)
inline val FVec4.zyxx get() = FVec4(z, y, x, x)
inline val FVec4.zyxy get() = FVec4(z, y, x, y)
inline val FVec4.zyxz get() = FVec4(z, y, x, z)
inline val FVec4.zyxw get() = FVec4(z, y, x, w)
inline val FVec4.zyyx get() = FVec4(z, y, y, x)
inline val FVec4.zyyy get() = FVec4(z, y, y, y)
inline val FVec4.zyyz get() = FVec4(z, y, y, z)
inline val FVec4.zyyw get() = FVec4(z, y, y, w)
inline val FVec4.zyzx get() = FVec4(z, y, z, x)
inline val FVec4.zyzy get() = FVec4(z, y, z, y)
inline val FVec4.zyzz get() = FVec4(z, y, z, z)
inline val FVec4.zyzw get() = FVec4(z, y, z, w)
inline val FVec4.zywx get() = FVec4(z, y, w, x)
inline val FVec4.zywy get() = FVec4(z, y, w, y)
inline val FVec4.zywz get() = FVec4(z, y, w, z)
inline val FVec4.zyww get() = FVec4(z, y, w, w)
inline val FVec4.zzxx get() = FVec4(z, z, x, x)
inline val FVec4.zzxy get() = FVec4(z, z, x, y)
inline val FVec4.zzxz get() = FVec4(z, z, x, z)
inline val FVec4.zzxw get() = FVec4(z, z, x, w)
inline val FVec4.zzyx get() = FVec4(z, z, y, x)
inline val FVec4.zzyy get() = FVec4(z, z, y, y)
inline val FVec4.zzyz get() = FVec4(z, z, y, z)
inline val FVec4.zzyw get() = FVec4(z, z, y, w)
inline val FVec4.zzzx get() = FVec4(z, z, z, x)
inline val FVec4.zzzy get() = FVec4(z, z, z, y)
inline val FVec4.zzzz get() = FVec4(z, z, z, z)
inline val FVec4.zzzw get() = FVec4(z, z, z, w)
inline val FVec4.zzwx get() = FVec4(z, z, w, x)
inline val FVec4.zzwy get() = FVec4(z, z, w, y)
inline val FVec4.zzwz get() = FVec4(z, z, w, z)
inline val FVec4.zzww get() = FVec4(z, z, w, w)
inline val FVec4.zwxx get() = FVec4(z, w, x, x)
inline val FVec4.zwxy get() = FVec4(z, w, x, y)
inline val FVec4.zwxz get() = FVec4(z, w, x, z)
inline val FVec4.zwxw get() = FVec4(z, w, x, w)
inline val FVec4.zwyx get() = FVec4(z, w, y, x)
inline val FVec4.zwyy get() = FVec4(z, w, y, y)
inline val FVec4.zwyz get() = FVec4(z, w, y, z)
inline val FVec4.zwyw get() = FVec4(z, w, y, w)
inline val FVec4.zwzx get() = FVec4(z, w, z, x)
inline val FVec4.zwzy get() = FVec4(z, w, z, y)
inline val FVec4.zwzz get() = FVec4(z, w, z, z)
inline val FVec4.zwzw get() = FVec4(z, w, z, w)
inline val FVec4.zwwx get() = FVec4(z, w, w, x)
inline val FVec4.zwwy get() = FVec4(z, w, w, y)
inline val FVec4.zwwz get() = FVec4(z, w, w, z)
inline val FVec4.zwww get() = FVec4(z, w, w, w)
inline val FVec4.wxxx get() = FVec4(w, x, x, x)
inline val FVec4.wxxy get() = FVec4(w, x, x, y)
inline val FVec4.wxxz get() = FVec4(w, x, x, z)
inline val FVec4.wxxw get() = FVec4(w, x, x, w)
inline val FVec4.wxyx get() = FVec4(w, x, y, x)
inline val FVec4.wxyy get() = FVec4(w, x, y, y)
inline val FVec4.wxyz get() = FVec4(w, x, y, z)
inline val FVec4.wxyw get() = FVec4(w, x, y, w)
inline val FVec4.wxzx get() = FVec4(w, x, z, x)
inline val FVec4.wxzy get() = FVec4(w, x, z, y)
inline val FVec4.wxzz get() = FVec4(w, x, z, z)
inline val FVec4.wxzw get() = FVec4(w, x, z, w)
inline val FVec4.wxwx get() = FVec4(w, x, w, x)
inline val FVec4.wxwy get() = FVec4(w, x, w, y)
inline val FVec4.wxwz get() = FVec4(w, x, w, z)
inline val FVec4.wxww get() = FVec4(w, x, w, w)
inline val FVec4.wyxx get() = FVec4(w, y, x, x)
inline val FVec4.wyxy get() = FVec4(w, y, x, y)
inline val FVec4.wyxz get() = FVec4(w, y, x, z)
inline val FVec4.wyxw get() = FVec4(w, y, x, w)
inline val FVec4.wyyx get() = FVec4(w, y, y, x)
inline val FVec4.wyyy get() = FVec4(w, y, y, y)
inline val FVec4.wyyz get() = FVec4(w, y, y, z)
inline val FVec4.wyyw get() = FVec4(w, y, y, w)
inline val FVec4.wyzx get() = FVec4(w, y, z, x)
inline val FVec4.wyzy get() = FVec4(w, y, z, y)
inline val FVec4.wyzz get() = FVec4(w, y, z, z)
inline val FVec4.wyzw get() = FVec4(w, y, z, w)
inline val FVec4.wywx get() = FVec4(w, y, w, x)
inline val FVec4.wywy get() = FVec4(w, y, w, y)
inline val FVec4.wywz get() = FVec4(w, y, w, z)
inline val FVec4.wyww get() = FVec4(w, y, w, w)
inline val FVec4.wzxx get() = FVec4(w, z, x, x)
inline val FVec4.wzxy get() = FVec4(w, z, x, y)
inline val FVec4.wzxz get() = FVec4(w, z, x, z)
inline val FVec4.wzxw get() = FVec4(w, z, x, w)
inline val FVec4.wzyx get() = FVec4(w, z, y, x)
inline val FVec4.wzyy get() = FVec4(w, z, y, y)
inline val FVec4.wzyz get() = FVec4(w, z, y, z)
inline val FVec4.wzyw get() = FVec4(w, z, y, w)
inline val FVec4.wzzx get() = FVec4(w, z, z, x)
inline val FVec4.wzzy get() = FVec4(w, z, z, y)
inline val FVec4.wzzz get() = FVec4(w, z, z, z)
inline val FVec4.wzzw get() = FVec4(w, z, z, w)
inline val FVec4.wzwx get() = FVec4(w, z, w, x)
inline val FVec4.wzwy get() = FVec4(w, z, w, y)
inline val FVec4.wzwz get() = FVec4(w, z, w, z)
inline val FVec4.wzww get() = FVec4(w, z, w, w)
inline val FVec4.wwxx get() = FVec4(w, w, x, x)
inline val FVec4.wwxy get() = FVec4(w, w, x, y)
inline val FVec4.wwxz get() = FVec4(w, w, x, z)
inline val FVec4.wwxw get() = FVec4(w, w, x, w)
inline val FVec4.wwyx get() = FVec4(w, w, y, x)
inline val FVec4.wwyy get() = FVec4(w, w, y, y)
inline val FVec4.wwyz get() = FVec4(w, w, y, z)
inline val FVec4.wwyw get() = FVec4(w, w, y, w)
inline val FVec4.wwzx get() = FVec4(w, w, z, x)
inline val FVec4.wwzy get() = FVec4(w, w, z, y)
inline val FVec4.wwzz get() = FVec4(w, w, z, z)
inline val FVec4.wwzw get() = FVec4(w, w, z, w)
inline val FVec4.wwwx get() = FVec4(w, w, w, x)
inline val FVec4.wwwy get() = FVec4(w, w, w, y)
inline val FVec4.wwwz get() = FVec4(w, w, w, z)
inline val FVec4.wwww get() = FVec4(w, w, w, w)

inline val FVec4.rrrr get() = FVec4(r, r, r, r)
inline val FVec4.rrrg get() = FVec4(r, r, r, g)
inline val FVec4.rrrb get() = FVec4(r, r, r, b)
inline val FVec4.rrra get() = FVec4(r, r, r, a)
inline val FVec4.rrgr get() = FVec4(r, r, g, r)
inline val FVec4.rrgg get() = FVec4(r, r, g, g)
inline val FVec4.rrgb get() = FVec4(r, r, g, b)
inline val FVec4.rrga get() = FVec4(r, r, g, a)
inline val FVec4.rrbr get() = FVec4(r, r, b, r)
inline val FVec4.rrbg get() = FVec4(r, r, b, g)
inline val FVec4.rrbb get() = FVec4(r, r, b, b)
inline val FVec4.rrba get() = FVec4(r, r, b, a)
inline val FVec4.rrar get() = FVec4(r, r, a, r)
inline val FVec4.rrag get() = FVec4(r, r, a, g)
inline val FVec4.rrab get() = FVec4(r, r, a, b)
inline val FVec4.rraa get() = FVec4(r, r, a, a)
inline val FVec4.rgrr get() = FVec4(r, g, r, r)
inline val FVec4.rgrg get() = FVec4(r, g, r, g)
inline val FVec4.rgrb get() = FVec4(r, g, r, b)
inline val FVec4.rgra get() = FVec4(r, g, r, a)
inline val FVec4.rggr get() = FVec4(r, g, g, r)
inline val FVec4.rggg get() = FVec4(r, g, g, g)
inline val FVec4.rggb get() = FVec4(r, g, g, b)
inline val FVec4.rgga get() = FVec4(r, g, g, a)
inline val FVec4.rgbr get() = FVec4(r, g, b, r)
inline val FVec4.rgbg get() = FVec4(r, g, b, g)
inline val FVec4.rgbb get() = FVec4(r, g, b, b)
inline val FVec4.rgba get() = FVec4(r, g, b, a)
inline val FVec4.rgar get() = FVec4(r, g, a, r)
inline val FVec4.rgag get() = FVec4(r, g, a, g)
inline val FVec4.rgab get() = FVec4(r, g, a, b)
inline val FVec4.rgaa get() = FVec4(r, g, a, a)
inline val FVec4.rbrr get() = FVec4(r, b, r, r)
inline val FVec4.rbrg get() = FVec4(r, b, r, g)
inline val FVec4.rbrb get() = FVec4(r, b, r, b)
inline val FVec4.rbra get() = FVec4(r, b, r, a)
inline val FVec4.rbgr get() = FVec4(r, b, g, r)
inline val FVec4.rbgg get() = FVec4(r, b, g, g)
inline val FVec4.rbgb get() = FVec4(r, b, g, b)
inline val FVec4.rbga get() = FVec4(r, b, g, a)
inline val FVec4.rbbr get() = FVec4(r, b, b, r)
inline val FVec4.rbbg get() = FVec4(r, b, b, g)
inline val FVec4.rbbb get() = FVec4(r, b, b, b)
inline val FVec4.rbba get() = FVec4(r, b, b, a)
inline val FVec4.rbar get() = FVec4(r, b, a, r)
inline val FVec4.rbag get() = FVec4(r, b, a, g)
inline val FVec4.rbab get() = FVec4(r, b, a, b)
inline val FVec4.rbaa get() = FVec4(r, b, a, a)
inline val FVec4.rarr get() = FVec4(r, a, r, r)
inline val FVec4.rarg get() = FVec4(r, a, r, g)
inline val FVec4.rarb get() = FVec4(r, a, r, b)
inline val FVec4.rara get() = FVec4(r, a, r, a)
inline val FVec4.ragr get() = FVec4(r, a, g, r)
inline val FVec4.ragg get() = FVec4(r, a, g, g)
inline val FVec4.ragb get() = FVec4(r, a, g, b)
inline val FVec4.raga get() = FVec4(r, a, g, a)
inline val FVec4.rabr get() = FVec4(r, a, b, r)
inline val FVec4.rabg get() = FVec4(r, a, b, g)
inline val FVec4.rabb get() = FVec4(r, a, b, b)
inline val FVec4.raba get() = FVec4(r, a, b, a)
inline val FVec4.raar get() = FVec4(r, a, a, r)
inline val FVec4.raag get() = FVec4(r, a, a, g)
inline val FVec4.raab get() = FVec4(r, a, a, b)
inline val FVec4.raaa get() = FVec4(r, a, a, a)
inline val FVec4.grrr get() = FVec4(g, r, r, r)
inline val FVec4.grrg get() = FVec4(g, r, r, g)
inline val FVec4.grrb get() = FVec4(g, r, r, b)
inline val FVec4.grra get() = FVec4(g, r, r, a)
inline val FVec4.grgr get() = FVec4(g, r, g, r)
inline val FVec4.grgg get() = FVec4(g, r, g, g)
inline val FVec4.grgb get() = FVec4(g, r, g, b)
inline val FVec4.grga get() = FVec4(g, r, g, a)
inline val FVec4.grbr get() = FVec4(g, r, b, r)
inline val FVec4.grbg get() = FVec4(g, r, b, g)
inline val FVec4.grbb get() = FVec4(g, r, b, b)
inline val FVec4.grba get() = FVec4(g, r, b, a)
inline val FVec4.grar get() = FVec4(g, r, a, r)
inline val FVec4.grag get() = FVec4(g, r, a, g)
inline val FVec4.grab get() = FVec4(g, r, a, b)
inline val FVec4.graa get() = FVec4(g, r, a, a)
inline val FVec4.ggrr get() = FVec4(g, g, r, r)
inline val FVec4.ggrg get() = FVec4(g, g, r, g)
inline val FVec4.ggrb get() = FVec4(g, g, r, b)
inline val FVec4.ggra get() = FVec4(g, g, r, a)
inline val FVec4.gggr get() = FVec4(g, g, g, r)
inline val FVec4.gggg get() = FVec4(g, g, g, g)
inline val FVec4.gggb get() = FVec4(g, g, g, b)
inline val FVec4.ggga get() = FVec4(g, g, g, a)
inline val FVec4.ggbr get() = FVec4(g, g, b, r)
inline val FVec4.ggbg get() = FVec4(g, g, b, g)
inline val FVec4.ggbb get() = FVec4(g, g, b, b)
inline val FVec4.ggba get() = FVec4(g, g, b, a)
inline val FVec4.ggar get() = FVec4(g, g, a, r)
inline val FVec4.ggag get() = FVec4(g, g, a, g)
inline val FVec4.ggab get() = FVec4(g, g, a, b)
inline val FVec4.ggaa get() = FVec4(g, g, a, a)
inline val FVec4.gbrr get() = FVec4(g, b, r, r)
inline val FVec4.gbrg get() = FVec4(g, b, r, g)
inline val FVec4.gbrb get() = FVec4(g, b, r, b)
inline val FVec4.gbra get() = FVec4(g, b, r, a)
inline val FVec4.gbgr get() = FVec4(g, b, g, r)
inline val FVec4.gbgg get() = FVec4(g, b, g, g)
inline val FVec4.gbgb get() = FVec4(g, b, g, b)
inline val FVec4.gbga get() = FVec4(g, b, g, a)
inline val FVec4.gbbr get() = FVec4(g, b, b, r)
inline val FVec4.gbbg get() = FVec4(g, b, b, g)
inline val FVec4.gbbb get() = FVec4(g, b, b, b)
inline val FVec4.gbba get() = FVec4(g, b, b, a)
inline val FVec4.gbar get() = FVec4(g, b, a, r)
inline val FVec4.gbag get() = FVec4(g, b, a, g)
inline val FVec4.gbab get() = FVec4(g, b, a, b)
inline val FVec4.gbaa get() = FVec4(g, b, a, a)
inline val FVec4.garr get() = FVec4(g, a, r, r)
inline val FVec4.garg get() = FVec4(g, a, r, g)
inline val FVec4.garb get() = FVec4(g, a, r, b)
inline val FVec4.gara get() = FVec4(g, a, r, a)
inline val FVec4.gagr get() = FVec4(g, a, g, r)
inline val FVec4.gagg get() = FVec4(g, a, g, g)
inline val FVec4.gagb get() = FVec4(g, a, g, b)
inline val FVec4.gaga get() = FVec4(g, a, g, a)
inline val FVec4.gabr get() = FVec4(g, a, b, r)
inline val FVec4.gabg get() = FVec4(g, a, b, g)
inline val FVec4.gabb get() = FVec4(g, a, b, b)
inline val FVec4.gaba get() = FVec4(g, a, b, a)
inline val FVec4.gaar get() = FVec4(g, a, a, r)
inline val FVec4.gaag get() = FVec4(g, a, a, g)
inline val FVec4.gaab get() = FVec4(g, a, a, b)
inline val FVec4.gaaa get() = FVec4(g, a, a, a)
inline val FVec4.brrr get() = FVec4(b, r, r, r)
inline val FVec4.brrg get() = FVec4(b, r, r, g)
inline val FVec4.brrb get() = FVec4(b, r, r, b)
inline val FVec4.brra get() = FVec4(b, r, r, a)
inline val FVec4.brgr get() = FVec4(b, r, g, r)
inline val FVec4.brgg get() = FVec4(b, r, g, g)
inline val FVec4.brgb get() = FVec4(b, r, g, b)
inline val FVec4.brga get() = FVec4(b, r, g, a)
inline val FVec4.brbr get() = FVec4(b, r, b, r)
inline val FVec4.brbg get() = FVec4(b, r, b, g)
inline val FVec4.brbb get() = FVec4(b, r, b, b)
inline val FVec4.brba get() = FVec4(b, r, b, a)
inline val FVec4.brar get() = FVec4(b, r, a, r)
inline val FVec4.brag get() = FVec4(b, r, a, g)
inline val FVec4.brab get() = FVec4(b, r, a, b)
inline val FVec4.braa get() = FVec4(b, r, a, a)
inline val FVec4.bgrr get() = FVec4(b, g, r, r)
inline val FVec4.bgrg get() = FVec4(b, g, r, g)
inline val FVec4.bgrb get() = FVec4(b, g, r, b)
inline val FVec4.bgra get() = FVec4(b, g, r, a)
inline val FVec4.bggr get() = FVec4(b, g, g, r)
inline val FVec4.bggg get() = FVec4(b, g, g, g)
inline val FVec4.bggb get() = FVec4(b, g, g, b)
inline val FVec4.bgga get() = FVec4(b, g, g, a)
inline val FVec4.bgbr get() = FVec4(b, g, b, r)
inline val FVec4.bgbg get() = FVec4(b, g, b, g)
inline val FVec4.bgbb get() = FVec4(b, g, b, b)
inline val FVec4.bgba get() = FVec4(b, g, b, a)
inline val FVec4.bgar get() = FVec4(b, g, a, r)
inline val FVec4.bgag get() = FVec4(b, g, a, g)
inline val FVec4.bgab get() = FVec4(b, g, a, b)
inline val FVec4.bgaa get() = FVec4(b, g, a, a)
inline val FVec4.bbrr get() = FVec4(b, b, r, r)
inline val FVec4.bbrg get() = FVec4(b, b, r, g)
inline val FVec4.bbrb get() = FVec4(b, b, r, b)
inline val FVec4.bbra get() = FVec4(b, b, r, a)
inline val FVec4.bbgr get() = FVec4(b, b, g, r)
inline val FVec4.bbgg get() = FVec4(b, b, g, g)
inline val FVec4.bbgb get() = FVec4(b, b, g, b)
inline val FVec4.bbga get() = FVec4(b, b, g, a)
inline val FVec4.bbbr get() = FVec4(b, b, b, r)
inline val FVec4.bbbg get() = FVec4(b, b, b, g)
inline val FVec4.bbbb get() = FVec4(b, b, b, b)
inline val FVec4.bbba get() = FVec4(b, b, b, a)
inline val FVec4.bbar get() = FVec4(b, b, a, r)
inline val FVec4.bbag get() = FVec4(b, b, a, g)
inline val FVec4.bbab get() = FVec4(b, b, a, b)
inline val FVec4.bbaa get() = FVec4(b, b, a, a)
inline val FVec4.barr get() = FVec4(b, a, r, r)
inline val FVec4.barg get() = FVec4(b, a, r, g)
inline val FVec4.barb get() = FVec4(b, a, r, b)
inline val FVec4.bara get() = FVec4(b, a, r, a)
inline val FVec4.bagr get() = FVec4(b, a, g, r)
inline val FVec4.bagg get() = FVec4(b, a, g, g)
inline val FVec4.bagb get() = FVec4(b, a, g, b)
inline val FVec4.baga get() = FVec4(b, a, g, a)
inline val FVec4.babr get() = FVec4(b, a, b, r)
inline val FVec4.babg get() = FVec4(b, a, b, g)
inline val FVec4.babb get() = FVec4(b, a, b, b)
inline val FVec4.baba get() = FVec4(b, a, b, a)
inline val FVec4.baar get() = FVec4(b, a, a, r)
inline val FVec4.baag get() = FVec4(b, a, a, g)
inline val FVec4.baab get() = FVec4(b, a, a, b)
inline val FVec4.baaa get() = FVec4(b, a, a, a)
inline val FVec4.arrr get() = FVec4(a, r, r, r)
inline val FVec4.arrg get() = FVec4(a, r, r, g)
inline val FVec4.arrb get() = FVec4(a, r, r, b)
inline val FVec4.arra get() = FVec4(a, r, r, a)
inline val FVec4.argr get() = FVec4(a, r, g, r)
inline val FVec4.argg get() = FVec4(a, r, g, g)
inline val FVec4.argb get() = FVec4(a, r, g, b)
inline val FVec4.arga get() = FVec4(a, r, g, a)
inline val FVec4.arbr get() = FVec4(a, r, b, r)
inline val FVec4.arbg get() = FVec4(a, r, b, g)
inline val FVec4.arbb get() = FVec4(a, r, b, b)
inline val FVec4.arba get() = FVec4(a, r, b, a)
inline val FVec4.arar get() = FVec4(a, r, a, r)
inline val FVec4.arag get() = FVec4(a, r, a, g)
inline val FVec4.arab get() = FVec4(a, r, a, b)
inline val FVec4.araa get() = FVec4(a, r, a, a)
inline val FVec4.agrr get() = FVec4(a, g, r, r)
inline val FVec4.agrg get() = FVec4(a, g, r, g)
inline val FVec4.agrb get() = FVec4(a, g, r, b)
inline val FVec4.agra get() = FVec4(a, g, r, a)
inline val FVec4.aggr get() = FVec4(a, g, g, r)
inline val FVec4.aggg get() = FVec4(a, g, g, g)
inline val FVec4.aggb get() = FVec4(a, g, g, b)
inline val FVec4.agga get() = FVec4(a, g, g, a)
inline val FVec4.agbr get() = FVec4(a, g, b, r)
inline val FVec4.agbg get() = FVec4(a, g, b, g)
inline val FVec4.agbb get() = FVec4(a, g, b, b)
inline val FVec4.agba get() = FVec4(a, g, b, a)
inline val FVec4.agar get() = FVec4(a, g, a, r)
inline val FVec4.agag get() = FVec4(a, g, a, g)
inline val FVec4.agab get() = FVec4(a, g, a, b)
inline val FVec4.agaa get() = FVec4(a, g, a, a)
inline val FVec4.abrr get() = FVec4(a, b, r, r)
inline val FVec4.abrg get() = FVec4(a, b, r, g)
inline val FVec4.abrb get() = FVec4(a, b, r, b)
inline val FVec4.abra get() = FVec4(a, b, r, a)
inline val FVec4.abgr get() = FVec4(a, b, g, r)
inline val FVec4.abgg get() = FVec4(a, b, g, g)
inline val FVec4.abgb get() = FVec4(a, b, g, b)
inline val FVec4.abga get() = FVec4(a, b, g, a)
inline val FVec4.abbr get() = FVec4(a, b, b, r)
inline val FVec4.abbg get() = FVec4(a, b, b, g)
inline val FVec4.abbb get() = FVec4(a, b, b, b)
inline val FVec4.abba get() = FVec4(a, b, b, a)
inline val FVec4.abar get() = FVec4(a, b, a, r)
inline val FVec4.abag get() = FVec4(a, b, a, g)
inline val FVec4.abab get() = FVec4(a, b, a, b)
inline val FVec4.abaa get() = FVec4(a, b, a, a)
inline val FVec4.aarr get() = FVec4(a, a, r, r)
inline val FVec4.aarg get() = FVec4(a, a, r, g)
inline val FVec4.aarb get() = FVec4(a, a, r, b)
inline val FVec4.aara get() = FVec4(a, a, r, a)
inline val FVec4.aagr get() = FVec4(a, a, g, r)
inline val FVec4.aagg get() = FVec4(a, a, g, g)
inline val FVec4.aagb get() = FVec4(a, a, g, b)
inline val FVec4.aaga get() = FVec4(a, a, g, a)
inline val FVec4.aabr get() = FVec4(a, a, b, r)
inline val FVec4.aabg get() = FVec4(a, a, b, g)
inline val FVec4.aabb get() = FVec4(a, a, b, b)
inline val FVec4.aaba get() = FVec4(a, a, b, a)
inline val FVec4.aaar get() = FVec4(a, a, a, r)
inline val FVec4.aaag get() = FVec4(a, a, a, g)
inline val FVec4.aaab get() = FVec4(a, a, a, b)
inline val FVec4.aaaa get() = FVec4(a, a, a, a)

inline val FVec4.ssss get() = FVec4(s, s, s, s)
inline val FVec4.ssst get() = FVec4(s, s, s, t)
inline val FVec4.sssp get() = FVec4(s, s, s, p)
inline val FVec4.sssq get() = FVec4(s, s, s, q)
inline val FVec4.ssts get() = FVec4(s, s, t, s)
inline val FVec4.sstt get() = FVec4(s, s, t, t)
inline val FVec4.sstp get() = FVec4(s, s, t, p)
inline val FVec4.sstq get() = FVec4(s, s, t, q)
inline val FVec4.ssps get() = FVec4(s, s, p, s)
inline val FVec4.sspt get() = FVec4(s, s, p, t)
inline val FVec4.sspp get() = FVec4(s, s, p, p)
inline val FVec4.sspq get() = FVec4(s, s, p, q)
inline val FVec4.ssqs get() = FVec4(s, s, q, s)
inline val FVec4.ssqt get() = FVec4(s, s, q, t)
inline val FVec4.ssqp get() = FVec4(s, s, q, p)
inline val FVec4.ssqq get() = FVec4(s, s, q, q)
inline val FVec4.stss get() = FVec4(s, t, s, s)
inline val FVec4.stst get() = FVec4(s, t, s, t)
inline val FVec4.stsp get() = FVec4(s, t, s, p)
inline val FVec4.stsq get() = FVec4(s, t, s, q)
inline val FVec4.stts get() = FVec4(s, t, t, s)
inline val FVec4.sttt get() = FVec4(s, t, t, t)
inline val FVec4.sttp get() = FVec4(s, t, t, p)
inline val FVec4.sttq get() = FVec4(s, t, t, q)
inline val FVec4.stps get() = FVec4(s, t, p, s)
inline val FVec4.stpt get() = FVec4(s, t, p, t)
inline val FVec4.stpp get() = FVec4(s, t, p, p)
inline val FVec4.stpq get() = FVec4(s, t, p, q)
inline val FVec4.stqs get() = FVec4(s, t, q, s)
inline val FVec4.stqt get() = FVec4(s, t, q, t)
inline val FVec4.stqp get() = FVec4(s, t, q, p)
inline val FVec4.stqq get() = FVec4(s, t, q, q)
inline val FVec4.spss get() = FVec4(s, p, s, s)
inline val FVec4.spst get() = FVec4(s, p, s, t)
inline val FVec4.spsp get() = FVec4(s, p, s, p)
inline val FVec4.spsq get() = FVec4(s, p, s, q)
inline val FVec4.spts get() = FVec4(s, p, t, s)
inline val FVec4.sptt get() = FVec4(s, p, t, t)
inline val FVec4.sptp get() = FVec4(s, p, t, p)
inline val FVec4.sptq get() = FVec4(s, p, t, q)
inline val FVec4.spps get() = FVec4(s, p, p, s)
inline val FVec4.sppt get() = FVec4(s, p, p, t)
inline val FVec4.sppp get() = FVec4(s, p, p, p)
inline val FVec4.sppq get() = FVec4(s, p, p, q)
inline val FVec4.spqs get() = FVec4(s, p, q, s)
inline val FVec4.spqt get() = FVec4(s, p, q, t)
inline val FVec4.spqp get() = FVec4(s, p, q, p)
inline val FVec4.spqq get() = FVec4(s, p, q, q)
inline val FVec4.sqss get() = FVec4(s, q, s, s)
inline val FVec4.sqst get() = FVec4(s, q, s, t)
inline val FVec4.sqsp get() = FVec4(s, q, s, p)
inline val FVec4.sqsq get() = FVec4(s, q, s, q)
inline val FVec4.sqts get() = FVec4(s, q, t, s)
inline val FVec4.sqtt get() = FVec4(s, q, t, t)
inline val FVec4.sqtp get() = FVec4(s, q, t, p)
inline val FVec4.sqtq get() = FVec4(s, q, t, q)
inline val FVec4.sqps get() = FVec4(s, q, p, s)
inline val FVec4.sqpt get() = FVec4(s, q, p, t)
inline val FVec4.sqpp get() = FVec4(s, q, p, p)
inline val FVec4.sqpq get() = FVec4(s, q, p, q)
inline val FVec4.sqqs get() = FVec4(s, q, q, s)
inline val FVec4.sqqt get() = FVec4(s, q, q, t)
inline val FVec4.sqqp get() = FVec4(s, q, q, p)
inline val FVec4.sqqq get() = FVec4(s, q, q, q)
inline val FVec4.tsss get() = FVec4(t, s, s, s)
inline val FVec4.tsst get() = FVec4(t, s, s, t)
inline val FVec4.tssp get() = FVec4(t, s, s, p)
inline val FVec4.tssq get() = FVec4(t, s, s, q)
inline val FVec4.tsts get() = FVec4(t, s, t, s)
inline val FVec4.tstt get() = FVec4(t, s, t, t)
inline val FVec4.tstp get() = FVec4(t, s, t, p)
inline val FVec4.tstq get() = FVec4(t, s, t, q)
inline val FVec4.tsps get() = FVec4(t, s, p, s)
inline val FVec4.tspt get() = FVec4(t, s, p, t)
inline val FVec4.tspp get() = FVec4(t, s, p, p)
inline val FVec4.tspq get() = FVec4(t, s, p, q)
inline val FVec4.tsqs get() = FVec4(t, s, q, s)
inline val FVec4.tsqt get() = FVec4(t, s, q, t)
inline val FVec4.tsqp get() = FVec4(t, s, q, p)
inline val FVec4.tsqq get() = FVec4(t, s, q, q)
inline val FVec4.ttss get() = FVec4(t, t, s, s)
inline val FVec4.ttst get() = FVec4(t, t, s, t)
inline val FVec4.ttsp get() = FVec4(t, t, s, p)
inline val FVec4.ttsq get() = FVec4(t, t, s, q)
inline val FVec4.ttts get() = FVec4(t, t, t, s)
inline val FVec4.tttt get() = FVec4(t, t, t, t)
inline val FVec4.tttp get() = FVec4(t, t, t, p)
inline val FVec4.tttq get() = FVec4(t, t, t, q)
inline val FVec4.ttps get() = FVec4(t, t, p, s)
inline val FVec4.ttpt get() = FVec4(t, t, p, t)
inline val FVec4.ttpp get() = FVec4(t, t, p, p)
inline val FVec4.ttpq get() = FVec4(t, t, p, q)
inline val FVec4.ttqs get() = FVec4(t, t, q, s)
inline val FVec4.ttqt get() = FVec4(t, t, q, t)
inline val FVec4.ttqp get() = FVec4(t, t, q, p)
inline val FVec4.ttqq get() = FVec4(t, t, q, q)
inline val FVec4.tpss get() = FVec4(t, p, s, s)
inline val FVec4.tpst get() = FVec4(t, p, s, t)
inline val FVec4.tpsp get() = FVec4(t, p, s, p)
inline val FVec4.tpsq get() = FVec4(t, p, s, q)
inline val FVec4.tpts get() = FVec4(t, p, t, s)
inline val FVec4.tptt get() = FVec4(t, p, t, t)
inline val FVec4.tptp get() = FVec4(t, p, t, p)
inline val FVec4.tptq get() = FVec4(t, p, t, q)
inline val FVec4.tpps get() = FVec4(t, p, p, s)
inline val FVec4.tppt get() = FVec4(t, p, p, t)
inline val FVec4.tppp get() = FVec4(t, p, p, p)
inline val FVec4.tppq get() = FVec4(t, p, p, q)
inline val FVec4.tpqs get() = FVec4(t, p, q, s)
inline val FVec4.tpqt get() = FVec4(t, p, q, t)
inline val FVec4.tpqp get() = FVec4(t, p, q, p)
inline val FVec4.tpqq get() = FVec4(t, p, q, q)
inline val FVec4.tqss get() = FVec4(t, q, s, s)
inline val FVec4.tqst get() = FVec4(t, q, s, t)
inline val FVec4.tqsp get() = FVec4(t, q, s, p)
inline val FVec4.tqsq get() = FVec4(t, q, s, q)
inline val FVec4.tqts get() = FVec4(t, q, t, s)
inline val FVec4.tqtt get() = FVec4(t, q, t, t)
inline val FVec4.tqtp get() = FVec4(t, q, t, p)
inline val FVec4.tqtq get() = FVec4(t, q, t, q)
inline val FVec4.tqps get() = FVec4(t, q, p, s)
inline val FVec4.tqpt get() = FVec4(t, q, p, t)
inline val FVec4.tqpp get() = FVec4(t, q, p, p)
inline val FVec4.tqpq get() = FVec4(t, q, p, q)
inline val FVec4.tqqs get() = FVec4(t, q, q, s)
inline val FVec4.tqqt get() = FVec4(t, q, q, t)
inline val FVec4.tqqp get() = FVec4(t, q, q, p)
inline val FVec4.tqqq get() = FVec4(t, q, q, q)
inline val FVec4.psss get() = FVec4(p, s, s, s)
inline val FVec4.psst get() = FVec4(p, s, s, t)
inline val FVec4.pssp get() = FVec4(p, s, s, p)
inline val FVec4.pssq get() = FVec4(p, s, s, q)
inline val FVec4.psts get() = FVec4(p, s, t, s)
inline val FVec4.pstt get() = FVec4(p, s, t, t)
inline val FVec4.pstp get() = FVec4(p, s, t, p)
inline val FVec4.pstq get() = FVec4(p, s, t, q)
inline val FVec4.psps get() = FVec4(p, s, p, s)
inline val FVec4.pspt get() = FVec4(p, s, p, t)
inline val FVec4.pspp get() = FVec4(p, s, p, p)
inline val FVec4.pspq get() = FVec4(p, s, p, q)
inline val FVec4.psqs get() = FVec4(p, s, q, s)
inline val FVec4.psqt get() = FVec4(p, s, q, t)
inline val FVec4.psqp get() = FVec4(p, s, q, p)
inline val FVec4.psqq get() = FVec4(p, s, q, q)
inline val FVec4.ptss get() = FVec4(p, t, s, s)
inline val FVec4.ptst get() = FVec4(p, t, s, t)
inline val FVec4.ptsp get() = FVec4(p, t, s, p)
inline val FVec4.ptsq get() = FVec4(p, t, s, q)
inline val FVec4.ptts get() = FVec4(p, t, t, s)
inline val FVec4.pttt get() = FVec4(p, t, t, t)
inline val FVec4.pttp get() = FVec4(p, t, t, p)
inline val FVec4.pttq get() = FVec4(p, t, t, q)
inline val FVec4.ptps get() = FVec4(p, t, p, s)
inline val FVec4.ptpt get() = FVec4(p, t, p, t)
inline val FVec4.ptpp get() = FVec4(p, t, p, p)
inline val FVec4.ptpq get() = FVec4(p, t, p, q)
inline val FVec4.ptqs get() = FVec4(p, t, q, s)
inline val FVec4.ptqt get() = FVec4(p, t, q, t)
inline val FVec4.ptqp get() = FVec4(p, t, q, p)
inline val FVec4.ptqq get() = FVec4(p, t, q, q)
inline val FVec4.ppss get() = FVec4(p, p, s, s)
inline val FVec4.ppst get() = FVec4(p, p, s, t)
inline val FVec4.ppsp get() = FVec4(p, p, s, p)
inline val FVec4.ppsq get() = FVec4(p, p, s, q)
inline val FVec4.ppts get() = FVec4(p, p, t, s)
inline val FVec4.pptt get() = FVec4(p, p, t, t)
inline val FVec4.pptp get() = FVec4(p, p, t, p)
inline val FVec4.pptq get() = FVec4(p, p, t, q)
inline val FVec4.ppps get() = FVec4(p, p, p, s)
inline val FVec4.pppt get() = FVec4(p, p, p, t)
inline val FVec4.pppp get() = FVec4(p, p, p, p)
inline val FVec4.pppq get() = FVec4(p, p, p, q)
inline val FVec4.ppqs get() = FVec4(p, p, q, s)
inline val FVec4.ppqt get() = FVec4(p, p, q, t)
inline val FVec4.ppqp get() = FVec4(p, p, q, p)
inline val FVec4.ppqq get() = FVec4(p, p, q, q)
inline val FVec4.pqss get() = FVec4(p, q, s, s)
inline val FVec4.pqst get() = FVec4(p, q, s, t)
inline val FVec4.pqsp get() = FVec4(p, q, s, p)
inline val FVec4.pqsq get() = FVec4(p, q, s, q)
inline val FVec4.pqts get() = FVec4(p, q, t, s)
inline val FVec4.pqtt get() = FVec4(p, q, t, t)
inline val FVec4.pqtp get() = FVec4(p, q, t, p)
inline val FVec4.pqtq get() = FVec4(p, q, t, q)
inline val FVec4.pqps get() = FVec4(p, q, p, s)
inline val FVec4.pqpt get() = FVec4(p, q, p, t)
inline val FVec4.pqpp get() = FVec4(p, q, p, p)
inline val FVec4.pqpq get() = FVec4(p, q, p, q)
inline val FVec4.pqqs get() = FVec4(p, q, q, s)
inline val FVec4.pqqt get() = FVec4(p, q, q, t)
inline val FVec4.pqqp get() = FVec4(p, q, q, p)
inline val FVec4.pqqq get() = FVec4(p, q, q, q)
inline val FVec4.qsss get() = FVec4(q, s, s, s)
inline val FVec4.qsst get() = FVec4(q, s, s, t)
inline val FVec4.qssp get() = FVec4(q, s, s, p)
inline val FVec4.qssq get() = FVec4(q, s, s, q)
inline val FVec4.qsts get() = FVec4(q, s, t, s)
inline val FVec4.qstt get() = FVec4(q, s, t, t)
inline val FVec4.qstp get() = FVec4(q, s, t, p)
inline val FVec4.qstq get() = FVec4(q, s, t, q)
inline val FVec4.qsps get() = FVec4(q, s, p, s)
inline val FVec4.qspt get() = FVec4(q, s, p, t)
inline val FVec4.qspp get() = FVec4(q, s, p, p)
inline val FVec4.qspq get() = FVec4(q, s, p, q)
inline val FVec4.qsqs get() = FVec4(q, s, q, s)
inline val FVec4.qsqt get() = FVec4(q, s, q, t)
inline val FVec4.qsqp get() = FVec4(q, s, q, p)
inline val FVec4.qsqq get() = FVec4(q, s, q, q)
inline val FVec4.qtss get() = FVec4(q, t, s, s)
inline val FVec4.qtst get() = FVec4(q, t, s, t)
inline val FVec4.qtsp get() = FVec4(q, t, s, p)
inline val FVec4.qtsq get() = FVec4(q, t, s, q)
inline val FVec4.qtts get() = FVec4(q, t, t, s)
inline val FVec4.qttt get() = FVec4(q, t, t, t)
inline val FVec4.qttp get() = FVec4(q, t, t, p)
inline val FVec4.qttq get() = FVec4(q, t, t, q)
inline val FVec4.qtps get() = FVec4(q, t, p, s)
inline val FVec4.qtpt get() = FVec4(q, t, p, t)
inline val FVec4.qtpp get() = FVec4(q, t, p, p)
inline val FVec4.qtpq get() = FVec4(q, t, p, q)
inline val FVec4.qtqs get() = FVec4(q, t, q, s)
inline val FVec4.qtqt get() = FVec4(q, t, q, t)
inline val FVec4.qtqp get() = FVec4(q, t, q, p)
inline val FVec4.qtqq get() = FVec4(q, t, q, q)
inline val FVec4.qpss get() = FVec4(q, p, s, s)
inline val FVec4.qpst get() = FVec4(q, p, s, t)
inline val FVec4.qpsp get() = FVec4(q, p, s, p)
inline val FVec4.qpsq get() = FVec4(q, p, s, q)
inline val FVec4.qpts get() = FVec4(q, p, t, s)
inline val FVec4.qptt get() = FVec4(q, p, t, t)
inline val FVec4.qptp get() = FVec4(q, p, t, p)
inline val FVec4.qptq get() = FVec4(q, p, t, q)
inline val FVec4.qpps get() = FVec4(q, p, p, s)
inline val FVec4.qppt get() = FVec4(q, p, p, t)
inline val FVec4.qppp get() = FVec4(q, p, p, p)
inline val FVec4.qppq get() = FVec4(q, p, p, q)
inline val FVec4.qpqs get() = FVec4(q, p, q, s)
inline val FVec4.qpqt get() = FVec4(q, p, q, t)
inline val FVec4.qpqp get() = FVec4(q, p, q, p)
inline val FVec4.qpqq get() = FVec4(q, p, q, q)
inline val FVec4.qqss get() = FVec4(q, q, s, s)
inline val FVec4.qqst get() = FVec4(q, q, s, t)
inline val FVec4.qqsp get() = FVec4(q, q, s, p)
inline val FVec4.qqsq get() = FVec4(q, q, s, q)
inline val FVec4.qqts get() = FVec4(q, q, t, s)
inline val FVec4.qqtt get() = FVec4(q, q, t, t)
inline val FVec4.qqtp get() = FVec4(q, q, t, p)
inline val FVec4.qqtq get() = FVec4(q, q, t, q)
inline val FVec4.qqps get() = FVec4(q, q, p, s)
inline val FVec4.qqpt get() = FVec4(q, q, p, t)
inline val FVec4.qqpp get() = FVec4(q, q, p, p)
inline val FVec4.qqpq get() = FVec4(q, q, p, q)
inline val FVec4.qqqs get() = FVec4(q, q, q, s)
inline val FVec4.qqqt get() = FVec4(q, q, q, t)
inline val FVec4.qqqp get() = FVec4(q, q, q, p)
inline val FVec4.qqqq get() = FVec4(q, q, q, q)
//endregion
