@file:Suppress("NOTHING_TO_INLINE", "MemberVisibilityCanBePrivate", "unused", "SpellCheckingInspection")

package io.github.aecsocket.klam

private const val AS_STRING_FORMAT = "%f"
private const val TO_STRING_FORMAT = DECIMAL_FORMAT
private inline fun typeArrayOf(vararg elements: Double) = doubleArrayOf(*elements)

data class DVec2(@JvmField var x: Double, @JvmField var y: Double) {
    constructor(v: DVec2) : this(v.x, v.y)
    constructor(s: Double) : this(s, s)

    fun from(x: Double, y: Double) { this.x = x; this.y = y }
    fun from(v: DVec2) = from(v.x, v.y)

    operator fun get(idx: Index) = when (idx) {
        0 -> x
        1 -> y
        else -> throw IndexOutOfBoundsException(idx)
    }

    operator fun set(idx: Index, s: Double) = when (idx) {
        0 -> x = s
        1 -> y = s
        else -> throw IndexOutOfBoundsException(idx)
    }

    fun compareTo(v: DVec2) = IVec2(x.compareTo(v.x), y.compareTo(v.y))
    fun equalTo(v: DVec2) = x.compareTo(v.x) == 0 && y.compareTo(v.y) == 0
    fun toArray() = typeArrayOf(x, y)

    fun asString(fmt: String = AS_STRING_FORMAT) = "($fmt, $fmt)".format(x, y)
    override fun toString() = asString(TO_STRING_FORMAT)
}

inline fun DVec2.map(block: (Double) -> Double) = DVec2(block(x), block(y))

inline operator fun DVec2.unaryMinus() = DVec2(-x, -y)
inline operator fun DVec2.inc()        = DVec2(x + 1, y + 1)
inline operator fun DVec2.dec()        = DVec2(x - 1, y - 1)

inline operator fun DVec2.plus(s: Double)  = DVec2(x + s, y + s)
inline operator fun DVec2.minus(s: Double) = DVec2(x - s, y - s)
inline operator fun DVec2.times(s: Double) = DVec2(x * s, y * s)
inline operator fun DVec2.div(s: Double)   = DVec2(x / s, y / s)

inline operator fun Double.plus(v: DVec2)  = DVec2(this + v.x, this + v.y)
inline operator fun Double.minus(v: DVec2) = DVec2(this - v.x, this - v.y)
inline operator fun Double.times(v: DVec2) = DVec2(this * v.x, this * v.y)
inline operator fun Double.div(v: DVec2)   = DVec2(this / v.x, this / v.y)

inline operator fun DVec2.plusAssign(s: Double)  { x += s; y += s }
inline operator fun DVec2.minusAssign(s: Double) { x -= s; y -= s }
inline operator fun DVec2.timesAssign(s: Double) { x *= s; y *= s }
inline operator fun DVec2.divAssign(s: Double)   { x /= s; y /= s }

inline operator fun DVec2.plus(v: DVec2)  = DVec2(x + v.x, y + v.y)
inline operator fun DVec2.minus(v: DVec2) = DVec2(x - v.x, y - v.y)
inline operator fun DVec2.times(v: DVec2) = DVec2(x * v.x, y * v.y)
inline operator fun DVec2.div(v: DVec2)   = DVec2(x / v.x, y / v.y)

inline operator fun DVec2.plusAssign(v: DVec2)  { x += v.x; y += v.y }
inline operator fun DVec2.minusAssign(v: DVec2) { x -= v.x; y -= v.y }
inline operator fun DVec2.timesAssign(v: DVec2) { x *= v.x; y *= v.y }
inline operator fun DVec2.divAssign(v: DVec2)   { x /= v.x; y /= v.y }

inline infix fun DVec2.eq(v: DVec2) = BVec2(x.compareTo(v.x) == 0, y.compareTo(v.y) == 0)
inline infix fun DVec2.ne(v: DVec2) = BVec2(x.compareTo(v.x) != 0, y.compareTo(v.y) != 0)
inline infix fun DVec2.lt(v: DVec2) = BVec2(x  < v.x, y  < v.y)
inline infix fun DVec2.le(v: DVec2) = BVec2(x <= v.x, y <= v.y)
inline infix fun DVec2.gt(v: DVec2) = BVec2(x  > v.x, y  > v.y)
inline infix fun DVec2.ge(v: DVec2) = BVec2(x >= v.x, y >= v.y)

data class DVec3(@JvmField var x: Double, @JvmField var y: Double, @JvmField var z: Double) {
    constructor(v: DVec3) : this(v.x, v.y, v.z)
    constructor(v: DVec2, z: Double) : this(v.x, v.y, z)
    constructor(s: Double) : this(s, s, s)

    fun from(x: Double, y: Double, z: Double) { this.x = x; this.y = y; this.z = z }
    fun from(v: DVec3) = from(v.x, v.y, v.z)

    operator fun get(idx: Index) = when (idx) {
        0 -> x
        1 -> y
        2 -> z
        else -> throw IndexOutOfBoundsException(idx)
    }

    operator fun set(idx: Index, s: Double) = when (idx) {
        0 -> x = s
        1 -> y = s
        2 -> z = s
        else -> throw IndexOutOfBoundsException(idx)
    }

    fun compareTo(v: DVec3) = IVec3(x.compareTo(v.x), y.compareTo(v.y), z.compareTo(v.z))
    fun equalTo(v: DVec3) = x.compareTo(v.x) == 0 && y.compareTo(v.y) == 0 && z.compareTo(v.z) == 0
    fun toArray() = typeArrayOf(x, y, z)

    fun asString(fmt: String = AS_STRING_FORMAT) = "($fmt, $fmt, $fmt)".format(x, y, z)
    override fun toString() = asString(TO_STRING_FORMAT)
}

inline fun DVec3.map(block: (Double) -> Double) = DVec3(block(x), block(y), block(z))

inline operator fun DVec3.unaryMinus() = DVec3(-x, -y, -z)
inline operator fun DVec3.inc()        = DVec3(x + 1, y + 1, z + 1)
inline operator fun DVec3.dec()        = DVec3(x - 1, y - 1, z - 1)

inline operator fun DVec3.plus(s: Double)  = DVec3(x + s, y + s, z + s)
inline operator fun DVec3.minus(s: Double) = DVec3(x - s, y - s, z - s)
inline operator fun DVec3.times(s: Double) = DVec3(x * s, y * s, z * s)
inline operator fun DVec3.div(s: Double)   = DVec3(x / s, y / s, z / s)

inline operator fun Double.plus(v: DVec3)  = DVec3(this + v.x, this + v.y, this + v.z)
inline operator fun Double.minus(v: DVec3) = DVec3(this - v.x, this - v.y, this - v.z)
inline operator fun Double.times(v: DVec3) = DVec3(this * v.x, this * v.y, this * v.z)
inline operator fun Double.div(v: DVec3)   = DVec3(this / v.x, this / v.y, this / v.z)

inline operator fun DVec3.plusAssign(s: Double)  { x += s; y += s; z += s }
inline operator fun DVec3.minusAssign(s: Double) { x -= s; y -= s; z -= s }
inline operator fun DVec3.timesAssign(s: Double) { x *= s; y *= s; z *= s }
inline operator fun DVec3.divAssign(s: Double)   { x /= s; y /= s; z /= s }

inline operator fun DVec3.plus(v: DVec3)  = DVec3(x + v.x, y + v.y, z / v.z)
inline operator fun DVec3.minus(v: DVec3) = DVec3(x - v.x, y - v.y, z / v.z)
inline operator fun DVec3.times(v: DVec3) = DVec3(x * v.x, y * v.y, z / v.z)
inline operator fun DVec3.div(v: DVec3)   = DVec3(x / v.x, y / v.y, z / v.z)

inline operator fun DVec3.plusAssign(v: DVec3)  { x += v.x; y += v.y; z += v.z }
inline operator fun DVec3.minusAssign(v: DVec3) { x -= v.x; y -= v.y; z -= v.z }
inline operator fun DVec3.timesAssign(v: DVec3) { x *= v.x; y *= v.y; z *= v.z }
inline operator fun DVec3.divAssign(v: DVec3)   { x /= v.x; y /= v.y; z /= v.z }

inline infix fun DVec3.eq(v: DVec3) = BVec3(x.compareTo(v.x) == 0, y.compareTo(v.y) == 0, z.compareTo(v.z) == 0)
inline infix fun DVec3.ne(v: DVec3) = BVec3(x.compareTo(v.x) != 0, y.compareTo(v.y) != 0, z.compareTo(v.z) != 0)
inline infix fun DVec3.lt(v: DVec3) = BVec3(x  < v.x, y  < v.y, z  < v.z)
inline infix fun DVec3.le(v: DVec3) = BVec3(x <= v.x, y <= v.y, z <= v.z)
inline infix fun DVec3.gt(v: DVec3) = BVec3(x  > v.x, y  > v.y, z  > v.z)
inline infix fun DVec3.ge(v: DVec3) = BVec3(x >= v.x, y >= v.y, z >= v.z)

data class DVec4(@JvmField var x: Double, @JvmField var y: Double, @JvmField var z: Double, @JvmField var w: Double) {
    constructor(v: DVec4) : this(v.x, v.y, v.z, v.w)
    constructor(v: DVec3, w: Double) : this(v.x, v.y, v.z, w)
    constructor(v: DVec2, z: Double, w: Double) : this(v.x, v.y, z, w)
    constructor(s: Double) : this(s, s, s, s)

    fun from(x: Double, y: Double, z: Double, w: Double) { this.x = x; this.y = y; this.z = z; this.w = w }
    fun from(v: DVec4) = from(v.x, v.y, v.z, v.w)

    operator fun get(idx: Index) = when (idx) {
        0 -> x
        1 -> y
        2 -> z
        3 -> w
        else -> throw IndexOutOfBoundsException(idx)
    }

    operator fun set(idx: Index, s: Double) = when (idx) {
        0 -> x = s
        1 -> y = s
        2 -> z = s
        3 -> w = s
        else -> throw IndexOutOfBoundsException(idx)
    }

    fun compareTo(v: DVec4) = IVec4(x.compareTo(v.x), y.compareTo(v.y), z.compareTo(v.z), w.compareTo(v.w))
    fun equalTo(v: DVec4) = x.compareTo(v.x) == 0 && y.compareTo(v.y) == 0 && z.compareTo(v.z) == 0 && w.compareTo(v.w) == 0
    fun toArray() = typeArrayOf(x, y, z, w)

    fun asString(fmt: String = AS_STRING_FORMAT) = "($fmt, $fmt, $fmt, $fmt)".format(x, y, z, w)
    override fun toString() = asString(TO_STRING_FORMAT)
}

inline fun DVec4.map(block: (Double) -> Double) = DVec4(block(x), block(y), block(z), block(w))

inline operator fun DVec4.unaryMinus() = DVec4(-x, -y, -z, -w)
inline operator fun DVec4.inc()        = DVec4(x + 1, y + 1, z + 1, w + 1)
inline operator fun DVec4.dec()        = DVec4(x - 1, y - 1, z - 1, w - 1)

inline operator fun DVec4.plus(s: Double)  = DVec4(x + s, y + s, z + s, w + s)
inline operator fun DVec4.minus(s: Double) = DVec4(x - s, y - s, z - s, w - s)
inline operator fun DVec4.times(s: Double) = DVec4(x * s, y * s, z * s, w * s)
inline operator fun DVec4.div(s: Double)   = DVec4(x / s, y / s, z / s, w / s)

inline operator fun Double.plus(v: DVec4)  = DVec4(this + v.x, this + v.y, this + v.z, this + v.w)
inline operator fun Double.minus(v: DVec4) = DVec4(this - v.x, this - v.y, this - v.z, this - v.w)
inline operator fun Double.times(v: DVec4) = DVec4(this * v.x, this * v.y, this * v.z, this * v.w)
inline operator fun Double.div(v: DVec4)   = DVec4(this / v.x, this / v.y, this / v.z, this / v.w)

inline operator fun DVec4.plusAssign(s: Double)  { x += s; y += s; z += s; w += s }
inline operator fun DVec4.minusAssign(s: Double) { x -= s; y -= s; z -= s; w -= s }
inline operator fun DVec4.timesAssign(s: Double) { x *= s; y *= s; z *= s; w *= s }
inline operator fun DVec4.divAssign(s: Double)   { x /= s; y /= s; z /= s; w /= s }

inline operator fun DVec4.plus(v: DVec4)  = DVec4(x + v.x, y + v.y, z / v.z, w / v.w)
inline operator fun DVec4.minus(v: DVec4) = DVec4(x - v.x, y - v.y, z / v.z, w / v.w)
inline operator fun DVec4.times(v: DVec4) = DVec4(x * v.x, y * v.y, z / v.z, w / v.w)
inline operator fun DVec4.div(v: DVec4)   = DVec4(x / v.x, y / v.y, z / v.z, w / v.w)

inline operator fun DVec4.plusAssign(v: DVec4)  { x += v.x; y += v.y; z += v.z; w += v.w }
inline operator fun DVec4.minusAssign(v: DVec4) { x -= v.x; y -= v.y; z -= v.z; w -= v.w }
inline operator fun DVec4.timesAssign(v: DVec4) { x *= v.x; y *= v.y; z *= v.z; w *= v.w }
inline operator fun DVec4.divAssign(v: DVec4)   { x /= v.x; y /= v.y; z /= v.z; w /= v.w }

inline infix fun DVec4.eq(v: DVec4) = BVec4(x.compareTo(v.x) == 0, y.compareTo(v.y) == 0, z.compareTo(v.z) == 0, w.compareTo(v.w) == 0)
inline infix fun DVec4.ne(v: DVec4) = BVec4(x.compareTo(v.x) != 0, y.compareTo(v.y) != 0, z.compareTo(v.z) != 0, w.compareTo(v.w) != 0)
inline infix fun DVec4.lt(v: DVec4) = BVec4(x  < v.x, y  < v.y, z  < v.z, w  < v.w)
inline infix fun DVec4.le(v: DVec4) = BVec4(x <= v.x, y <= v.y, z <= v.z, w <= v.w)
inline infix fun DVec4.gt(v: DVec4) = BVec4(x  > v.x, y  > v.y, z  > v.z, w  > v.w)
inline infix fun DVec4.ge(v: DVec4) = BVec4(x >= v.x, y >= v.y, z >= v.z, w >= v.w)

//region Alternate accessors
inline var DVec2.r get() = x; set(value) { x = value }
inline var DVec2.g get() = y; set(value) { y = value }

inline var DVec2.s get() = x; set(value) { x = value }
inline var DVec2.t get() = y; set(value) { y = value}

inline var DVec3.r get() = x; set(value) { x = value }
inline var DVec3.g get() = y; set(value) { y = value }
inline var DVec3.b get() = z; set(value) { z = value }

inline var DVec3.s get() = x; set(value) { x = value}
inline var DVec3.t get() = y; set(value) { y = value }
inline var DVec3.p get() = z; set(value) { z = value }

inline var DVec4.r get() = x; set(value) { x = value }
inline var DVec4.g get() = y; set(value) { y = value }
inline var DVec4.b get() = z; set(value) { z = value }
inline var DVec4.a get() = w; set(value) { w = value }

inline var DVec4.s get() = x; set(value) { x = value }
inline var DVec4.t get() = y; set(value) { y = value }
inline var DVec4.p get() = z; set(value) { z = value }
inline var DVec4.q get() = w; set(value) { w = value }
//endregion

//region Swizzling Vec2
inline val DVec2.xx get() = DVec2(x, x)
inline val DVec2.xy get() = DVec2(x, y)
inline val DVec2.yx get() = DVec2(y, x)
inline val DVec2.yy get() = DVec2(y, y)

inline val DVec2.rr get() = DVec2(r, r)
inline val DVec2.rg get() = DVec2(r, g)
inline val DVec2.gr get() = DVec2(g, r)
inline val DVec2.gg get() = DVec2(g, g)

inline val DVec2.ss get() = DVec2(s, s)
inline val DVec2.st get() = DVec2(s, t)
inline val DVec2.ts get() = DVec2(t, s)
inline val DVec2.tt get() = DVec2(t, t)

inline val DVec2.xxx get() = DVec3(x, x, x)
inline val DVec2.xxy get() = DVec3(x, x, y)
inline val DVec2.xyx get() = DVec3(x, y, x)
inline val DVec2.xyy get() = DVec3(x, y, y)
inline val DVec2.yxx get() = DVec3(y, x, x)
inline val DVec2.yxy get() = DVec3(y, x, y)
inline val DVec2.yyx get() = DVec3(y, y, x)
inline val DVec2.yyy get() = DVec3(y, y, y)

inline val DVec2.rrr get() = DVec3(r, r, r)
inline val DVec2.rrg get() = DVec3(r, r, g)
inline val DVec2.rgr get() = DVec3(r, g, r)
inline val DVec2.rgg get() = DVec3(r, g, g)
inline val DVec2.grr get() = DVec3(g, r, r)
inline val DVec2.grg get() = DVec3(g, r, g)
inline val DVec2.ggr get() = DVec3(g, g, r)
inline val DVec2.ggg get() = DVec3(g, g, g)

inline val DVec2.sss get() = DVec3(s, s, s)
inline val DVec2.sst get() = DVec3(s, s, t)
inline val DVec2.sts get() = DVec3(s, t, s)
inline val DVec2.stt get() = DVec3(s, t, t)
inline val DVec2.tss get() = DVec3(t, s, s)
inline val DVec2.tst get() = DVec3(t, s, t)
inline val DVec2.tts get() = DVec3(t, t, s)
inline val DVec2.ttt get() = DVec3(t, t, t)

inline val DVec2.xxxx get() = DVec4(x, x, x, x)
inline val DVec2.xxxy get() = DVec4(x, x, x, y)
inline val DVec2.xxyx get() = DVec4(x, x, y, x)
inline val DVec2.xxyy get() = DVec4(x, x, y, y)
inline val DVec2.xyxx get() = DVec4(x, y, x, x)
inline val DVec2.xyxy get() = DVec4(x, y, x, y)
inline val DVec2.xyyx get() = DVec4(x, y, y, x)
inline val DVec2.xyyy get() = DVec4(x, y, y, y)
inline val DVec2.yxxx get() = DVec4(y, x, x, x)
inline val DVec2.yxxy get() = DVec4(y, x, x, y)
inline val DVec2.yxyx get() = DVec4(y, x, y, x)
inline val DVec2.yxyy get() = DVec4(y, x, y, y)
inline val DVec2.yyxx get() = DVec4(y, y, x, x)
inline val DVec2.yyxy get() = DVec4(y, y, x, y)
inline val DVec2.yyyx get() = DVec4(y, y, y, x)
inline val DVec2.yyyy get() = DVec4(y, y, y, y)

inline val DVec2.rrrr get() = DVec4(r, r, r, r)
inline val DVec2.rrrg get() = DVec4(r, r, r, g)
inline val DVec2.rrgr get() = DVec4(r, r, g, r)
inline val DVec2.rrgg get() = DVec4(r, r, g, g)
inline val DVec2.rgrr get() = DVec4(r, g, r, r)
inline val DVec2.rgrg get() = DVec4(r, g, r, g)
inline val DVec2.rggr get() = DVec4(r, g, g, r)
inline val DVec2.rggg get() = DVec4(r, g, g, g)
inline val DVec2.grrr get() = DVec4(g, r, r, r)
inline val DVec2.grrg get() = DVec4(g, r, r, g)
inline val DVec2.grgr get() = DVec4(g, r, g, r)
inline val DVec2.grgg get() = DVec4(g, r, g, g)
inline val DVec2.ggrr get() = DVec4(g, g, r, r)
inline val DVec2.ggrg get() = DVec4(g, g, r, g)
inline val DVec2.gggr get() = DVec4(g, g, g, r)
inline val DVec2.gggg get() = DVec4(g, g, g, g)

inline val DVec2.ssss get() = DVec4(s, s, s, s)
inline val DVec2.ssst get() = DVec4(s, s, s, t)
inline val DVec2.ssts get() = DVec4(s, s, t, s)
inline val DVec2.sstt get() = DVec4(s, s, t, t)
inline val DVec2.stss get() = DVec4(s, t, s, s)
inline val DVec2.stst get() = DVec4(s, t, s, t)
inline val DVec2.stts get() = DVec4(s, t, t, s)
inline val DVec2.sttt get() = DVec4(s, t, t, t)
inline val DVec2.tsss get() = DVec4(t, s, s, s)
inline val DVec2.tsst get() = DVec4(t, s, s, t)
inline val DVec2.tsts get() = DVec4(t, s, t, s)
inline val DVec2.tstt get() = DVec4(t, s, t, t)
inline val DVec2.ttss get() = DVec4(t, t, s, s)
inline val DVec2.ttst get() = DVec4(t, t, s, t)
inline val DVec2.ttts get() = DVec4(t, t, t, s)
inline val DVec2.tttt get() = DVec4(t, t, t, t)
//endregion

//region Swizzling Vec3
inline val DVec3.xx get() = DVec2(x, x)
inline val DVec3.xy get() = DVec2(x, y)
inline val DVec3.xz get() = DVec2(x, z)
inline val DVec3.yx get() = DVec2(y, x)
inline val DVec3.yy get() = DVec2(y, y)
inline val DVec3.yz get() = DVec2(y, z)
inline val DVec3.zx get() = DVec2(z, x)
inline val DVec3.zy get() = DVec2(z, y)
inline val DVec3.zz get() = DVec2(z, z)

inline val DVec3.rr get() = DVec2(r, r)
inline val DVec3.rg get() = DVec2(r, g)
inline val DVec3.rb get() = DVec2(r, b)
inline val DVec3.gr get() = DVec2(g, r)
inline val DVec3.gg get() = DVec2(g, g)
inline val DVec3.gb get() = DVec2(g, b)
inline val DVec3.br get() = DVec2(b, r)
inline val DVec3.bg get() = DVec2(b, g)
inline val DVec3.bb get() = DVec2(b, b)

inline val DVec3.ss get() = DVec2(s, s)
inline val DVec3.st get() = DVec2(s, t)
inline val DVec3.sp get() = DVec2(s, p)
inline val DVec3.ts get() = DVec2(t, s)
inline val DVec3.tt get() = DVec2(t, t)
inline val DVec3.tp get() = DVec2(t, p)
inline val DVec3.ps get() = DVec2(p, s)
inline val DVec3.pt get() = DVec2(p, t)
inline val DVec3.pp get() = DVec2(p, p)

inline val DVec3.xxx get() = DVec3(x, x, x)
inline val DVec3.xxy get() = DVec3(x, x, y)
inline val DVec3.xxz get() = DVec3(x, x, z)
inline val DVec3.xyx get() = DVec3(x, y, x)
inline val DVec3.xyy get() = DVec3(x, y, y)
inline val DVec3.xyz get() = DVec3(x, y, z)
inline val DVec3.xzx get() = DVec3(x, z, x)
inline val DVec3.xzy get() = DVec3(x, z, y)
inline val DVec3.xzz get() = DVec3(x, z, z)
inline val DVec3.yxx get() = DVec3(y, x, x)
inline val DVec3.yxy get() = DVec3(y, x, y)
inline val DVec3.yxz get() = DVec3(y, x, z)
inline val DVec3.yyx get() = DVec3(y, y, x)
inline val DVec3.yyy get() = DVec3(y, y, y)
inline val DVec3.yyz get() = DVec3(y, y, z)
inline val DVec3.yzx get() = DVec3(y, z, x)
inline val DVec3.yzy get() = DVec3(y, z, y)
inline val DVec3.yzz get() = DVec3(y, z, z)
inline val DVec3.zxx get() = DVec3(z, x, x)
inline val DVec3.zxy get() = DVec3(z, x, y)
inline val DVec3.zxz get() = DVec3(z, x, z)
inline val DVec3.zyx get() = DVec3(z, y, x)
inline val DVec3.zyy get() = DVec3(z, y, y)
inline val DVec3.zyz get() = DVec3(z, y, z)
inline val DVec3.zzx get() = DVec3(z, z, x)
inline val DVec3.zzy get() = DVec3(z, z, y)
inline val DVec3.zzz get() = DVec3(z, z, z)

inline val DVec3.rrr get() = DVec3(r, r, r)
inline val DVec3.rrg get() = DVec3(r, r, g)
inline val DVec3.rrb get() = DVec3(r, r, b)
inline val DVec3.rgr get() = DVec3(r, g, r)
inline val DVec3.rgg get() = DVec3(r, g, g)
inline val DVec3.rgb get() = DVec3(r, g, b)
inline val DVec3.rbr get() = DVec3(r, b, r)
inline val DVec3.rbg get() = DVec3(r, b, g)
inline val DVec3.rbb get() = DVec3(r, b, b)
inline val DVec3.grr get() = DVec3(g, r, r)
inline val DVec3.grg get() = DVec3(g, r, g)
inline val DVec3.grb get() = DVec3(g, r, b)
inline val DVec3.ggr get() = DVec3(g, g, r)
inline val DVec3.ggg get() = DVec3(g, g, g)
inline val DVec3.ggb get() = DVec3(g, g, b)
inline val DVec3.gbr get() = DVec3(g, b, r)
inline val DVec3.gbg get() = DVec3(g, b, g)
inline val DVec3.gbb get() = DVec3(g, b, b)
inline val DVec3.brr get() = DVec3(b, r, r)
inline val DVec3.brg get() = DVec3(b, r, g)
inline val DVec3.brb get() = DVec3(b, r, b)
inline val DVec3.bgr get() = DVec3(b, g, r)
inline val DVec3.bgg get() = DVec3(b, g, g)
inline val DVec3.bgb get() = DVec3(b, g, b)
inline val DVec3.bbr get() = DVec3(b, b, r)
inline val DVec3.bbg get() = DVec3(b, b, g)
inline val DVec3.bbb get() = DVec3(b, b, b)

inline val DVec3.sss get() = DVec3(s, s, s)
inline val DVec3.sst get() = DVec3(s, s, t)
inline val DVec3.ssp get() = DVec3(s, s, p)
inline val DVec3.sts get() = DVec3(s, t, s)
inline val DVec3.stt get() = DVec3(s, t, t)
inline val DVec3.stp get() = DVec3(s, t, p)
inline val DVec3.sps get() = DVec3(s, p, s)
inline val DVec3.spt get() = DVec3(s, p, t)
inline val DVec3.spp get() = DVec3(s, p, p)
inline val DVec3.tss get() = DVec3(t, s, s)
inline val DVec3.tst get() = DVec3(t, s, t)
inline val DVec3.tsp get() = DVec3(t, s, p)
inline val DVec3.tts get() = DVec3(t, t, s)
inline val DVec3.ttt get() = DVec3(t, t, t)
inline val DVec3.ttp get() = DVec3(t, t, p)
inline val DVec3.tps get() = DVec3(t, p, s)
inline val DVec3.tpt get() = DVec3(t, p, t)
inline val DVec3.tpp get() = DVec3(t, p, p)
inline val DVec3.pss get() = DVec3(p, s, s)
inline val DVec3.pst get() = DVec3(p, s, t)
inline val DVec3.psp get() = DVec3(p, s, p)
inline val DVec3.pts get() = DVec3(p, t, s)
inline val DVec3.ptt get() = DVec3(p, t, t)
inline val DVec3.ptp get() = DVec3(p, t, p)
inline val DVec3.pps get() = DVec3(p, p, s)
inline val DVec3.ppt get() = DVec3(p, p, t)
inline val DVec3.ppp get() = DVec3(p, p, p)

inline val DVec3.xxxx get() = DVec4(x, x, x, x)
inline val DVec3.xxxy get() = DVec4(x, x, x, y)
inline val DVec3.xxxz get() = DVec4(x, x, x, z)
inline val DVec3.xxyx get() = DVec4(x, x, y, x)
inline val DVec3.xxyy get() = DVec4(x, x, y, y)
inline val DVec3.xxyz get() = DVec4(x, x, y, z)
inline val DVec3.xxzx get() = DVec4(x, x, z, x)
inline val DVec3.xxzy get() = DVec4(x, x, z, y)
inline val DVec3.xxzz get() = DVec4(x, x, z, z)
inline val DVec3.xyxx get() = DVec4(x, y, x, x)
inline val DVec3.xyxy get() = DVec4(x, y, x, y)
inline val DVec3.xyxz get() = DVec4(x, y, x, z)
inline val DVec3.xyyx get() = DVec4(x, y, y, x)
inline val DVec3.xyyy get() = DVec4(x, y, y, y)
inline val DVec3.xyyz get() = DVec4(x, y, y, z)
inline val DVec3.xyzx get() = DVec4(x, y, z, x)
inline val DVec3.xyzy get() = DVec4(x, y, z, y)
inline val DVec3.xyzz get() = DVec4(x, y, z, z)
inline val DVec3.xzxx get() = DVec4(x, z, x, x)
inline val DVec3.xzxy get() = DVec4(x, z, x, y)
inline val DVec3.xzxz get() = DVec4(x, z, x, z)
inline val DVec3.xzyx get() = DVec4(x, z, y, x)
inline val DVec3.xzyy get() = DVec4(x, z, y, y)
inline val DVec3.xzyz get() = DVec4(x, z, y, z)
inline val DVec3.xzzx get() = DVec4(x, z, z, x)
inline val DVec3.xzzy get() = DVec4(x, z, z, y)
inline val DVec3.xzzz get() = DVec4(x, z, z, z)
inline val DVec3.yxxx get() = DVec4(y, x, x, x)
inline val DVec3.yxxy get() = DVec4(y, x, x, y)
inline val DVec3.yxxz get() = DVec4(y, x, x, z)
inline val DVec3.yxyx get() = DVec4(y, x, y, x)
inline val DVec3.yxyy get() = DVec4(y, x, y, y)
inline val DVec3.yxyz get() = DVec4(y, x, y, z)
inline val DVec3.yxzx get() = DVec4(y, x, z, x)
inline val DVec3.yxzy get() = DVec4(y, x, z, y)
inline val DVec3.yxzz get() = DVec4(y, x, z, z)
inline val DVec3.yyxx get() = DVec4(y, y, x, x)
inline val DVec3.yyxy get() = DVec4(y, y, x, y)
inline val DVec3.yyxz get() = DVec4(y, y, x, z)
inline val DVec3.yyyx get() = DVec4(y, y, y, x)
inline val DVec3.yyyy get() = DVec4(y, y, y, y)
inline val DVec3.yyyz get() = DVec4(y, y, y, z)
inline val DVec3.yyzx get() = DVec4(y, y, z, x)
inline val DVec3.yyzy get() = DVec4(y, y, z, y)
inline val DVec3.yyzz get() = DVec4(y, y, z, z)
inline val DVec3.yzxx get() = DVec4(y, z, x, x)
inline val DVec3.yzxy get() = DVec4(y, z, x, y)
inline val DVec3.yzxz get() = DVec4(y, z, x, z)
inline val DVec3.yzyx get() = DVec4(y, z, y, x)
inline val DVec3.yzyy get() = DVec4(y, z, y, y)
inline val DVec3.yzyz get() = DVec4(y, z, y, z)
inline val DVec3.yzzx get() = DVec4(y, z, z, x)
inline val DVec3.yzzy get() = DVec4(y, z, z, y)
inline val DVec3.yzzz get() = DVec4(y, z, z, z)
inline val DVec3.zxxx get() = DVec4(z, x, x, x)
inline val DVec3.zxxy get() = DVec4(z, x, x, y)
inline val DVec3.zxxz get() = DVec4(z, x, x, z)
inline val DVec3.zxyx get() = DVec4(z, x, y, x)
inline val DVec3.zxyy get() = DVec4(z, x, y, y)
inline val DVec3.zxyz get() = DVec4(z, x, y, z)
inline val DVec3.zxzx get() = DVec4(z, x, z, x)
inline val DVec3.zxzy get() = DVec4(z, x, z, y)
inline val DVec3.zxzz get() = DVec4(z, x, z, z)
inline val DVec3.zyxx get() = DVec4(z, y, x, x)
inline val DVec3.zyxy get() = DVec4(z, y, x, y)
inline val DVec3.zyxz get() = DVec4(z, y, x, z)
inline val DVec3.zyyx get() = DVec4(z, y, y, x)
inline val DVec3.zyyy get() = DVec4(z, y, y, y)
inline val DVec3.zyyz get() = DVec4(z, y, y, z)
inline val DVec3.zyzx get() = DVec4(z, y, z, x)
inline val DVec3.zyzy get() = DVec4(z, y, z, y)
inline val DVec3.zyzz get() = DVec4(z, y, z, z)
inline val DVec3.zzxx get() = DVec4(z, z, x, x)
inline val DVec3.zzxy get() = DVec4(z, z, x, y)
inline val DVec3.zzxz get() = DVec4(z, z, x, z)
inline val DVec3.zzyx get() = DVec4(z, z, y, x)
inline val DVec3.zzyy get() = DVec4(z, z, y, y)
inline val DVec3.zzyz get() = DVec4(z, z, y, z)
inline val DVec3.zzzx get() = DVec4(z, z, z, x)
inline val DVec3.zzzy get() = DVec4(z, z, z, y)
inline val DVec3.zzzz get() = DVec4(z, z, z, z)

inline val DVec3.rrrr get() = DVec4(r, r, r, r)
inline val DVec3.rrrg get() = DVec4(r, r, r, g)
inline val DVec3.rrrb get() = DVec4(r, r, r, b)
inline val DVec3.rrgr get() = DVec4(r, r, g, r)
inline val DVec3.rrgg get() = DVec4(r, r, g, g)
inline val DVec3.rrgb get() = DVec4(r, r, g, b)
inline val DVec3.rrbr get() = DVec4(r, r, b, r)
inline val DVec3.rrbg get() = DVec4(r, r, b, g)
inline val DVec3.rrbb get() = DVec4(r, r, b, b)
inline val DVec3.rgrr get() = DVec4(r, g, r, r)
inline val DVec3.rgrg get() = DVec4(r, g, r, g)
inline val DVec3.rgrb get() = DVec4(r, g, r, b)
inline val DVec3.rggr get() = DVec4(r, g, g, r)
inline val DVec3.rggg get() = DVec4(r, g, g, g)
inline val DVec3.rggb get() = DVec4(r, g, g, b)
inline val DVec3.rgbr get() = DVec4(r, g, b, r)
inline val DVec3.rgbg get() = DVec4(r, g, b, g)
inline val DVec3.rgbb get() = DVec4(r, g, b, b)
inline val DVec3.rbrr get() = DVec4(r, b, r, r)
inline val DVec3.rbrg get() = DVec4(r, b, r, g)
inline val DVec3.rbrb get() = DVec4(r, b, r, b)
inline val DVec3.rbgr get() = DVec4(r, b, g, r)
inline val DVec3.rbgg get() = DVec4(r, b, g, g)
inline val DVec3.rbgb get() = DVec4(r, b, g, b)
inline val DVec3.rbbr get() = DVec4(r, b, b, r)
inline val DVec3.rbbg get() = DVec4(r, b, b, g)
inline val DVec3.rbbb get() = DVec4(r, b, b, b)
inline val DVec3.grrr get() = DVec4(g, r, r, r)
inline val DVec3.grrg get() = DVec4(g, r, r, g)
inline val DVec3.grrb get() = DVec4(g, r, r, b)
inline val DVec3.grgr get() = DVec4(g, r, g, r)
inline val DVec3.grgg get() = DVec4(g, r, g, g)
inline val DVec3.grgb get() = DVec4(g, r, g, b)
inline val DVec3.grbr get() = DVec4(g, r, b, r)
inline val DVec3.grbg get() = DVec4(g, r, b, g)
inline val DVec3.grbb get() = DVec4(g, r, b, b)
inline val DVec3.ggrr get() = DVec4(g, g, r, r)
inline val DVec3.ggrg get() = DVec4(g, g, r, g)
inline val DVec3.ggrb get() = DVec4(g, g, r, b)
inline val DVec3.gggr get() = DVec4(g, g, g, r)
inline val DVec3.gggg get() = DVec4(g, g, g, g)
inline val DVec3.gggb get() = DVec4(g, g, g, b)
inline val DVec3.ggbr get() = DVec4(g, g, b, r)
inline val DVec3.ggbg get() = DVec4(g, g, b, g)
inline val DVec3.ggbb get() = DVec4(g, g, b, b)
inline val DVec3.gbrr get() = DVec4(g, b, r, r)
inline val DVec3.gbrg get() = DVec4(g, b, r, g)
inline val DVec3.gbrb get() = DVec4(g, b, r, b)
inline val DVec3.gbgr get() = DVec4(g, b, g, r)
inline val DVec3.gbgg get() = DVec4(g, b, g, g)
inline val DVec3.gbgb get() = DVec4(g, b, g, b)
inline val DVec3.gbbr get() = DVec4(g, b, b, r)
inline val DVec3.gbbg get() = DVec4(g, b, b, g)
inline val DVec3.gbbb get() = DVec4(g, b, b, b)
inline val DVec3.brrr get() = DVec4(b, r, r, r)
inline val DVec3.brrg get() = DVec4(b, r, r, g)
inline val DVec3.brrb get() = DVec4(b, r, r, b)
inline val DVec3.brgr get() = DVec4(b, r, g, r)
inline val DVec3.brgg get() = DVec4(b, r, g, g)
inline val DVec3.brgb get() = DVec4(b, r, g, b)
inline val DVec3.brbr get() = DVec4(b, r, b, r)
inline val DVec3.brbg get() = DVec4(b, r, b, g)
inline val DVec3.brbb get() = DVec4(b, r, b, b)
inline val DVec3.bgrr get() = DVec4(b, g, r, r)
inline val DVec3.bgrg get() = DVec4(b, g, r, g)
inline val DVec3.bgrb get() = DVec4(b, g, r, b)
inline val DVec3.bggr get() = DVec4(b, g, g, r)
inline val DVec3.bggg get() = DVec4(b, g, g, g)
inline val DVec3.bggb get() = DVec4(b, g, g, b)
inline val DVec3.bgbr get() = DVec4(b, g, b, r)
inline val DVec3.bgbg get() = DVec4(b, g, b, g)
inline val DVec3.bgbb get() = DVec4(b, g, b, b)
inline val DVec3.bbrr get() = DVec4(b, b, r, r)
inline val DVec3.bbrg get() = DVec4(b, b, r, g)
inline val DVec3.bbrb get() = DVec4(b, b, r, b)
inline val DVec3.bbgr get() = DVec4(b, b, g, r)
inline val DVec3.bbgg get() = DVec4(b, b, g, g)
inline val DVec3.bbgb get() = DVec4(b, b, g, b)
inline val DVec3.bbbr get() = DVec4(b, b, b, r)
inline val DVec3.bbbg get() = DVec4(b, b, b, g)
inline val DVec3.bbbb get() = DVec4(b, b, b, b)

inline val DVec3.ssss get() = DVec4(s, s, s, s)
inline val DVec3.ssst get() = DVec4(s, s, s, t)
inline val DVec3.sssp get() = DVec4(s, s, s, p)
inline val DVec3.ssts get() = DVec4(s, s, t, s)
inline val DVec3.sstt get() = DVec4(s, s, t, t)
inline val DVec3.sstp get() = DVec4(s, s, t, p)
inline val DVec3.ssps get() = DVec4(s, s, p, s)
inline val DVec3.sspt get() = DVec4(s, s, p, t)
inline val DVec3.sspp get() = DVec4(s, s, p, p)
inline val DVec3.stss get() = DVec4(s, t, s, s)
inline val DVec3.stst get() = DVec4(s, t, s, t)
inline val DVec3.stsp get() = DVec4(s, t, s, p)
inline val DVec3.stts get() = DVec4(s, t, t, s)
inline val DVec3.sttt get() = DVec4(s, t, t, t)
inline val DVec3.sttp get() = DVec4(s, t, t, p)
inline val DVec3.stps get() = DVec4(s, t, p, s)
inline val DVec3.stpt get() = DVec4(s, t, p, t)
inline val DVec3.stpp get() = DVec4(s, t, p, p)
inline val DVec3.spss get() = DVec4(s, p, s, s)
inline val DVec3.spst get() = DVec4(s, p, s, t)
inline val DVec3.spsp get() = DVec4(s, p, s, p)
inline val DVec3.spts get() = DVec4(s, p, t, s)
inline val DVec3.sptt get() = DVec4(s, p, t, t)
inline val DVec3.sptp get() = DVec4(s, p, t, p)
inline val DVec3.spps get() = DVec4(s, p, p, s)
inline val DVec3.sppt get() = DVec4(s, p, p, t)
inline val DVec3.sppp get() = DVec4(s, p, p, p)
inline val DVec3.tsss get() = DVec4(t, s, s, s)
inline val DVec3.tsst get() = DVec4(t, s, s, t)
inline val DVec3.tssp get() = DVec4(t, s, s, p)
inline val DVec3.tsts get() = DVec4(t, s, t, s)
inline val DVec3.tstt get() = DVec4(t, s, t, t)
inline val DVec3.tstp get() = DVec4(t, s, t, p)
inline val DVec3.tsps get() = DVec4(t, s, p, s)
inline val DVec3.tspt get() = DVec4(t, s, p, t)
inline val DVec3.tspp get() = DVec4(t, s, p, p)
inline val DVec3.ttss get() = DVec4(t, t, s, s)
inline val DVec3.ttst get() = DVec4(t, t, s, t)
inline val DVec3.ttsp get() = DVec4(t, t, s, p)
inline val DVec3.ttts get() = DVec4(t, t, t, s)
inline val DVec3.tttt get() = DVec4(t, t, t, t)
inline val DVec3.tttp get() = DVec4(t, t, t, p)
inline val DVec3.ttps get() = DVec4(t, t, p, s)
inline val DVec3.ttpt get() = DVec4(t, t, p, t)
inline val DVec3.ttpp get() = DVec4(t, t, p, p)
inline val DVec3.tpss get() = DVec4(t, p, s, s)
inline val DVec3.tpst get() = DVec4(t, p, s, t)
inline val DVec3.tpsp get() = DVec4(t, p, s, p)
inline val DVec3.tpts get() = DVec4(t, p, t, s)
inline val DVec3.tptt get() = DVec4(t, p, t, t)
inline val DVec3.tptp get() = DVec4(t, p, t, p)
inline val DVec3.tpps get() = DVec4(t, p, p, s)
inline val DVec3.tppt get() = DVec4(t, p, p, t)
inline val DVec3.tppp get() = DVec4(t, p, p, p)
inline val DVec3.psss get() = DVec4(p, s, s, s)
inline val DVec3.psst get() = DVec4(p, s, s, t)
inline val DVec3.pssp get() = DVec4(p, s, s, p)
inline val DVec3.psts get() = DVec4(p, s, t, s)
inline val DVec3.pstt get() = DVec4(p, s, t, t)
inline val DVec3.pstp get() = DVec4(p, s, t, p)
inline val DVec3.psps get() = DVec4(p, s, p, s)
inline val DVec3.pspt get() = DVec4(p, s, p, t)
inline val DVec3.pspp get() = DVec4(p, s, p, p)
inline val DVec3.ptss get() = DVec4(p, t, s, s)
inline val DVec3.ptst get() = DVec4(p, t, s, t)
inline val DVec3.ptsp get() = DVec4(p, t, s, p)
inline val DVec3.ptts get() = DVec4(p, t, t, s)
inline val DVec3.pttt get() = DVec4(p, t, t, t)
inline val DVec3.pttp get() = DVec4(p, t, t, p)
inline val DVec3.ptps get() = DVec4(p, t, p, s)
inline val DVec3.ptpt get() = DVec4(p, t, p, t)
inline val DVec3.ptpp get() = DVec4(p, t, p, p)
inline val DVec3.ppss get() = DVec4(p, p, s, s)
inline val DVec3.ppst get() = DVec4(p, p, s, t)
inline val DVec3.ppsp get() = DVec4(p, p, s, p)
inline val DVec3.ppts get() = DVec4(p, p, t, s)
inline val DVec3.pptt get() = DVec4(p, p, t, t)
inline val DVec3.pptp get() = DVec4(p, p, t, p)
inline val DVec3.ppps get() = DVec4(p, p, p, s)
inline val DVec3.pppt get() = DVec4(p, p, p, t)
inline val DVec3.pppp get() = DVec4(p, p, p, p)
//endregion

//region Swizzling Vec4
inline val DVec4.xx get() = DVec2(x, x)
inline val DVec4.xy get() = DVec2(x, y)
inline val DVec4.xz get() = DVec2(x, z)
inline val DVec4.xw get() = DVec2(x, w)
inline val DVec4.yx get() = DVec2(y, x)
inline val DVec4.yy get() = DVec2(y, y)
inline val DVec4.yz get() = DVec2(y, z)
inline val DVec4.yw get() = DVec2(y, w)
inline val DVec4.zx get() = DVec2(z, x)
inline val DVec4.zy get() = DVec2(z, y)
inline val DVec4.zz get() = DVec2(z, z)
inline val DVec4.zw get() = DVec2(z, w)
inline val DVec4.wx get() = DVec2(w, x)
inline val DVec4.wy get() = DVec2(w, y)
inline val DVec4.wz get() = DVec2(w, z)
inline val DVec4.ww get() = DVec2(w, w)

inline val DVec4.rr get() = DVec2(r, r)
inline val DVec4.rg get() = DVec2(r, g)
inline val DVec4.rb get() = DVec2(r, b)
inline val DVec4.ra get() = DVec2(r, a)
inline val DVec4.gr get() = DVec2(g, r)
inline val DVec4.gg get() = DVec2(g, g)
inline val DVec4.gb get() = DVec2(g, b)
inline val DVec4.ga get() = DVec2(g, a)
inline val DVec4.br get() = DVec2(b, r)
inline val DVec4.bg get() = DVec2(b, g)
inline val DVec4.bb get() = DVec2(b, b)
inline val DVec4.ba get() = DVec2(b, a)
inline val DVec4.ar get() = DVec2(a, r)
inline val DVec4.ag get() = DVec2(a, g)
inline val DVec4.ab get() = DVec2(a, b)
inline val DVec4.aa get() = DVec2(a, a)

inline val DVec4.ss get() = DVec2(s, s)
inline val DVec4.st get() = DVec2(s, t)
inline val DVec4.sp get() = DVec2(s, p)
inline val DVec4.sq get() = DVec2(s, q)
inline val DVec4.ts get() = DVec2(t, s)
inline val DVec4.tt get() = DVec2(t, t)
inline val DVec4.tp get() = DVec2(t, p)
inline val DVec4.tq get() = DVec2(t, q)
inline val DVec4.ps get() = DVec2(p, s)
inline val DVec4.pt get() = DVec2(p, t)
inline val DVec4.pp get() = DVec2(p, p)
inline val DVec4.pq get() = DVec2(p, q)
inline val DVec4.qs get() = DVec2(q, s)
inline val DVec4.qt get() = DVec2(q, t)
inline val DVec4.qp get() = DVec2(q, p)
inline val DVec4.qq get() = DVec2(q, q)

inline val DVec4.xxx get() = DVec3(x, x, x)
inline val DVec4.xxy get() = DVec3(x, x, y)
inline val DVec4.xxz get() = DVec3(x, x, z)
inline val DVec4.xxw get() = DVec3(x, x, w)
inline val DVec4.xyx get() = DVec3(x, y, x)
inline val DVec4.xyy get() = DVec3(x, y, y)
inline val DVec4.xyz get() = DVec3(x, y, z)
inline val DVec4.xyw get() = DVec3(x, y, w)
inline val DVec4.xzx get() = DVec3(x, z, x)
inline val DVec4.xzy get() = DVec3(x, z, y)
inline val DVec4.xzz get() = DVec3(x, z, z)
inline val DVec4.xzw get() = DVec3(x, z, w)
inline val DVec4.xwx get() = DVec3(x, w, x)
inline val DVec4.xwy get() = DVec3(x, w, y)
inline val DVec4.xwz get() = DVec3(x, w, z)
inline val DVec4.xww get() = DVec3(x, w, w)
inline val DVec4.yxx get() = DVec3(y, x, x)
inline val DVec4.yxy get() = DVec3(y, x, y)
inline val DVec4.yxz get() = DVec3(y, x, z)
inline val DVec4.yxw get() = DVec3(y, x, w)
inline val DVec4.yyx get() = DVec3(y, y, x)
inline val DVec4.yyy get() = DVec3(y, y, y)
inline val DVec4.yyz get() = DVec3(y, y, z)
inline val DVec4.yyw get() = DVec3(y, y, w)
inline val DVec4.yzx get() = DVec3(y, z, x)
inline val DVec4.yzy get() = DVec3(y, z, y)
inline val DVec4.yzz get() = DVec3(y, z, z)
inline val DVec4.yzw get() = DVec3(y, z, w)
inline val DVec4.ywx get() = DVec3(y, w, x)
inline val DVec4.ywy get() = DVec3(y, w, y)
inline val DVec4.ywz get() = DVec3(y, w, z)
inline val DVec4.yww get() = DVec3(y, w, w)
inline val DVec4.zxx get() = DVec3(z, x, x)
inline val DVec4.zxy get() = DVec3(z, x, y)
inline val DVec4.zxz get() = DVec3(z, x, z)
inline val DVec4.zxw get() = DVec3(z, x, w)
inline val DVec4.zyx get() = DVec3(z, y, x)
inline val DVec4.zyy get() = DVec3(z, y, y)
inline val DVec4.zyz get() = DVec3(z, y, z)
inline val DVec4.zyw get() = DVec3(z, y, w)
inline val DVec4.zzx get() = DVec3(z, z, x)
inline val DVec4.zzy get() = DVec3(z, z, y)
inline val DVec4.zzz get() = DVec3(z, z, z)
inline val DVec4.zzw get() = DVec3(z, z, w)
inline val DVec4.zwx get() = DVec3(z, w, x)
inline val DVec4.zwy get() = DVec3(z, w, y)
inline val DVec4.zwz get() = DVec3(z, w, z)
inline val DVec4.zww get() = DVec3(z, w, w)
inline val DVec4.wxx get() = DVec3(w, x, x)
inline val DVec4.wxy get() = DVec3(w, x, y)
inline val DVec4.wxz get() = DVec3(w, x, z)
inline val DVec4.wxw get() = DVec3(w, x, w)
inline val DVec4.wyx get() = DVec3(w, y, x)
inline val DVec4.wyy get() = DVec3(w, y, y)
inline val DVec4.wyz get() = DVec3(w, y, z)
inline val DVec4.wyw get() = DVec3(w, y, w)
inline val DVec4.wzx get() = DVec3(w, z, x)
inline val DVec4.wzy get() = DVec3(w, z, y)
inline val DVec4.wzz get() = DVec3(w, z, z)
inline val DVec4.wzw get() = DVec3(w, z, w)
inline val DVec4.wwx get() = DVec3(w, w, x)
inline val DVec4.wwy get() = DVec3(w, w, y)
inline val DVec4.wwz get() = DVec3(w, w, z)
inline val DVec4.www get() = DVec3(w, w, w)

inline val DVec4.rrr get() = DVec3(r, r, r)
inline val DVec4.rrg get() = DVec3(r, r, g)
inline val DVec4.rrb get() = DVec3(r, r, b)
inline val DVec4.rra get() = DVec3(r, r, a)
inline val DVec4.rgr get() = DVec3(r, g, r)
inline val DVec4.rgg get() = DVec3(r, g, g)
inline val DVec4.rgb get() = DVec3(r, g, b)
inline val DVec4.rga get() = DVec3(r, g, a)
inline val DVec4.rbr get() = DVec3(r, b, r)
inline val DVec4.rbg get() = DVec3(r, b, g)
inline val DVec4.rbb get() = DVec3(r, b, b)
inline val DVec4.rba get() = DVec3(r, b, a)
inline val DVec4.rar get() = DVec3(r, a, r)
inline val DVec4.rag get() = DVec3(r, a, g)
inline val DVec4.rab get() = DVec3(r, a, b)
inline val DVec4.raa get() = DVec3(r, a, a)
inline val DVec4.grr get() = DVec3(g, r, r)
inline val DVec4.grg get() = DVec3(g, r, g)
inline val DVec4.grb get() = DVec3(g, r, b)
inline val DVec4.gra get() = DVec3(g, r, a)
inline val DVec4.ggr get() = DVec3(g, g, r)
inline val DVec4.ggg get() = DVec3(g, g, g)
inline val DVec4.ggb get() = DVec3(g, g, b)
inline val DVec4.gga get() = DVec3(g, g, a)
inline val DVec4.gbr get() = DVec3(g, b, r)
inline val DVec4.gbg get() = DVec3(g, b, g)
inline val DVec4.gbb get() = DVec3(g, b, b)
inline val DVec4.gba get() = DVec3(g, b, a)
inline val DVec4.gar get() = DVec3(g, a, r)
inline val DVec4.gag get() = DVec3(g, a, g)
inline val DVec4.gab get() = DVec3(g, a, b)
inline val DVec4.gaa get() = DVec3(g, a, a)
inline val DVec4.brr get() = DVec3(b, r, r)
inline val DVec4.brg get() = DVec3(b, r, g)
inline val DVec4.brb get() = DVec3(b, r, b)
inline val DVec4.bra get() = DVec3(b, r, a)
inline val DVec4.bgr get() = DVec3(b, g, r)
inline val DVec4.bgg get() = DVec3(b, g, g)
inline val DVec4.bgb get() = DVec3(b, g, b)
inline val DVec4.bga get() = DVec3(b, g, a)
inline val DVec4.bbr get() = DVec3(b, b, r)
inline val DVec4.bbg get() = DVec3(b, b, g)
inline val DVec4.bbb get() = DVec3(b, b, b)
inline val DVec4.bba get() = DVec3(b, b, a)
inline val DVec4.bar get() = DVec3(b, a, r)
inline val DVec4.bag get() = DVec3(b, a, g)
inline val DVec4.bab get() = DVec3(b, a, b)
inline val DVec4.baa get() = DVec3(b, a, a)
inline val DVec4.arr get() = DVec3(a, r, r)
inline val DVec4.arg get() = DVec3(a, r, g)
inline val DVec4.arb get() = DVec3(a, r, b)
inline val DVec4.ara get() = DVec3(a, r, a)
inline val DVec4.agr get() = DVec3(a, g, r)
inline val DVec4.agg get() = DVec3(a, g, g)
inline val DVec4.agb get() = DVec3(a, g, b)
inline val DVec4.aga get() = DVec3(a, g, a)
inline val DVec4.abr get() = DVec3(a, b, r)
inline val DVec4.abg get() = DVec3(a, b, g)
inline val DVec4.abb get() = DVec3(a, b, b)
inline val DVec4.aba get() = DVec3(a, b, a)
inline val DVec4.aar get() = DVec3(a, a, r)
inline val DVec4.aag get() = DVec3(a, a, g)
inline val DVec4.aab get() = DVec3(a, a, b)
inline val DVec4.aaa get() = DVec3(a, a, a)

inline val DVec4.sss get() = DVec3(s, s, s)
inline val DVec4.sst get() = DVec3(s, s, t)
inline val DVec4.ssp get() = DVec3(s, s, p)
inline val DVec4.ssq get() = DVec3(s, s, q)
inline val DVec4.sts get() = DVec3(s, t, s)
inline val DVec4.stt get() = DVec3(s, t, t)
inline val DVec4.stp get() = DVec3(s, t, p)
inline val DVec4.stq get() = DVec3(s, t, q)
inline val DVec4.sps get() = DVec3(s, p, s)
inline val DVec4.spt get() = DVec3(s, p, t)
inline val DVec4.spp get() = DVec3(s, p, p)
inline val DVec4.spq get() = DVec3(s, p, q)
inline val DVec4.sqs get() = DVec3(s, q, s)
inline val DVec4.sqt get() = DVec3(s, q, t)
inline val DVec4.sqp get() = DVec3(s, q, p)
inline val DVec4.sqq get() = DVec3(s, q, q)
inline val DVec4.tss get() = DVec3(t, s, s)
inline val DVec4.tst get() = DVec3(t, s, t)
inline val DVec4.tsp get() = DVec3(t, s, p)
inline val DVec4.tsq get() = DVec3(t, s, q)
inline val DVec4.tts get() = DVec3(t, t, s)
inline val DVec4.ttt get() = DVec3(t, t, t)
inline val DVec4.ttp get() = DVec3(t, t, p)
inline val DVec4.ttq get() = DVec3(t, t, q)
inline val DVec4.tps get() = DVec3(t, p, s)
inline val DVec4.tpt get() = DVec3(t, p, t)
inline val DVec4.tpp get() = DVec3(t, p, p)
inline val DVec4.tpq get() = DVec3(t, p, q)
inline val DVec4.tqs get() = DVec3(t, q, s)
inline val DVec4.tqt get() = DVec3(t, q, t)
inline val DVec4.tqp get() = DVec3(t, q, p)
inline val DVec4.tqq get() = DVec3(t, q, q)
inline val DVec4.pss get() = DVec3(p, s, s)
inline val DVec4.pst get() = DVec3(p, s, t)
inline val DVec4.psp get() = DVec3(p, s, p)
inline val DVec4.psq get() = DVec3(p, s, q)
inline val DVec4.pts get() = DVec3(p, t, s)
inline val DVec4.ptt get() = DVec3(p, t, t)
inline val DVec4.ptp get() = DVec3(p, t, p)
inline val DVec4.ptq get() = DVec3(p, t, q)
inline val DVec4.pps get() = DVec3(p, p, s)
inline val DVec4.ppt get() = DVec3(p, p, t)
inline val DVec4.ppp get() = DVec3(p, p, p)
inline val DVec4.ppq get() = DVec3(p, p, q)
inline val DVec4.pqs get() = DVec3(p, q, s)
inline val DVec4.pqt get() = DVec3(p, q, t)
inline val DVec4.pqp get() = DVec3(p, q, p)
inline val DVec4.pqq get() = DVec3(p, q, q)
inline val DVec4.qss get() = DVec3(q, s, s)
inline val DVec4.qst get() = DVec3(q, s, t)
inline val DVec4.qsp get() = DVec3(q, s, p)
inline val DVec4.qsq get() = DVec3(q, s, q)
inline val DVec4.qts get() = DVec3(q, t, s)
inline val DVec4.qtt get() = DVec3(q, t, t)
inline val DVec4.qtp get() = DVec3(q, t, p)
inline val DVec4.qtq get() = DVec3(q, t, q)
inline val DVec4.qps get() = DVec3(q, p, s)
inline val DVec4.qpt get() = DVec3(q, p, t)
inline val DVec4.qpp get() = DVec3(q, p, p)
inline val DVec4.qpq get() = DVec3(q, p, q)
inline val DVec4.qqs get() = DVec3(q, q, s)
inline val DVec4.qqt get() = DVec3(q, q, t)
inline val DVec4.qqp get() = DVec3(q, q, p)
inline val DVec4.qqq get() = DVec3(q, q, q)

inline val DVec4.xxxx get() = DVec4(x, x, x, x)
inline val DVec4.xxxy get() = DVec4(x, x, x, y)
inline val DVec4.xxxz get() = DVec4(x, x, x, z)
inline val DVec4.xxxw get() = DVec4(x, x, x, w)
inline val DVec4.xxyx get() = DVec4(x, x, y, x)
inline val DVec4.xxyy get() = DVec4(x, x, y, y)
inline val DVec4.xxyz get() = DVec4(x, x, y, z)
inline val DVec4.xxyw get() = DVec4(x, x, y, w)
inline val DVec4.xxzx get() = DVec4(x, x, z, x)
inline val DVec4.xxzy get() = DVec4(x, x, z, y)
inline val DVec4.xxzz get() = DVec4(x, x, z, z)
inline val DVec4.xxzw get() = DVec4(x, x, z, w)
inline val DVec4.xxwx get() = DVec4(x, x, w, x)
inline val DVec4.xxwy get() = DVec4(x, x, w, y)
inline val DVec4.xxwz get() = DVec4(x, x, w, z)
inline val DVec4.xxww get() = DVec4(x, x, w, w)
inline val DVec4.xyxx get() = DVec4(x, y, x, x)
inline val DVec4.xyxy get() = DVec4(x, y, x, y)
inline val DVec4.xyxz get() = DVec4(x, y, x, z)
inline val DVec4.xyxw get() = DVec4(x, y, x, w)
inline val DVec4.xyyx get() = DVec4(x, y, y, x)
inline val DVec4.xyyy get() = DVec4(x, y, y, y)
inline val DVec4.xyyz get() = DVec4(x, y, y, z)
inline val DVec4.xyyw get() = DVec4(x, y, y, w)
inline val DVec4.xyzx get() = DVec4(x, y, z, x)
inline val DVec4.xyzy get() = DVec4(x, y, z, y)
inline val DVec4.xyzz get() = DVec4(x, y, z, z)
inline val DVec4.xyzw get() = DVec4(x, y, z, w)
inline val DVec4.xywx get() = DVec4(x, y, w, x)
inline val DVec4.xywy get() = DVec4(x, y, w, y)
inline val DVec4.xywz get() = DVec4(x, y, w, z)
inline val DVec4.xyww get() = DVec4(x, y, w, w)
inline val DVec4.xzxx get() = DVec4(x, z, x, x)
inline val DVec4.xzxy get() = DVec4(x, z, x, y)
inline val DVec4.xzxz get() = DVec4(x, z, x, z)
inline val DVec4.xzxw get() = DVec4(x, z, x, w)
inline val DVec4.xzyx get() = DVec4(x, z, y, x)
inline val DVec4.xzyy get() = DVec4(x, z, y, y)
inline val DVec4.xzyz get() = DVec4(x, z, y, z)
inline val DVec4.xzyw get() = DVec4(x, z, y, w)
inline val DVec4.xzzx get() = DVec4(x, z, z, x)
inline val DVec4.xzzy get() = DVec4(x, z, z, y)
inline val DVec4.xzzz get() = DVec4(x, z, z, z)
inline val DVec4.xzzw get() = DVec4(x, z, z, w)
inline val DVec4.xzwx get() = DVec4(x, z, w, x)
inline val DVec4.xzwy get() = DVec4(x, z, w, y)
inline val DVec4.xzwz get() = DVec4(x, z, w, z)
inline val DVec4.xzww get() = DVec4(x, z, w, w)
inline val DVec4.xwxx get() = DVec4(x, w, x, x)
inline val DVec4.xwxy get() = DVec4(x, w, x, y)
inline val DVec4.xwxz get() = DVec4(x, w, x, z)
inline val DVec4.xwxw get() = DVec4(x, w, x, w)
inline val DVec4.xwyx get() = DVec4(x, w, y, x)
inline val DVec4.xwyy get() = DVec4(x, w, y, y)
inline val DVec4.xwyz get() = DVec4(x, w, y, z)
inline val DVec4.xwyw get() = DVec4(x, w, y, w)
inline val DVec4.xwzx get() = DVec4(x, w, z, x)
inline val DVec4.xwzy get() = DVec4(x, w, z, y)
inline val DVec4.xwzz get() = DVec4(x, w, z, z)
inline val DVec4.xwzw get() = DVec4(x, w, z, w)
inline val DVec4.xwwx get() = DVec4(x, w, w, x)
inline val DVec4.xwwy get() = DVec4(x, w, w, y)
inline val DVec4.xwwz get() = DVec4(x, w, w, z)
inline val DVec4.xwww get() = DVec4(x, w, w, w)
inline val DVec4.yxxx get() = DVec4(y, x, x, x)
inline val DVec4.yxxy get() = DVec4(y, x, x, y)
inline val DVec4.yxxz get() = DVec4(y, x, x, z)
inline val DVec4.yxxw get() = DVec4(y, x, x, w)
inline val DVec4.yxyx get() = DVec4(y, x, y, x)
inline val DVec4.yxyy get() = DVec4(y, x, y, y)
inline val DVec4.yxyz get() = DVec4(y, x, y, z)
inline val DVec4.yxyw get() = DVec4(y, x, y, w)
inline val DVec4.yxzx get() = DVec4(y, x, z, x)
inline val DVec4.yxzy get() = DVec4(y, x, z, y)
inline val DVec4.yxzz get() = DVec4(y, x, z, z)
inline val DVec4.yxzw get() = DVec4(y, x, z, w)
inline val DVec4.yxwx get() = DVec4(y, x, w, x)
inline val DVec4.yxwy get() = DVec4(y, x, w, y)
inline val DVec4.yxwz get() = DVec4(y, x, w, z)
inline val DVec4.yxww get() = DVec4(y, x, w, w)
inline val DVec4.yyxx get() = DVec4(y, y, x, x)
inline val DVec4.yyxy get() = DVec4(y, y, x, y)
inline val DVec4.yyxz get() = DVec4(y, y, x, z)
inline val DVec4.yyxw get() = DVec4(y, y, x, w)
inline val DVec4.yyyx get() = DVec4(y, y, y, x)
inline val DVec4.yyyy get() = DVec4(y, y, y, y)
inline val DVec4.yyyz get() = DVec4(y, y, y, z)
inline val DVec4.yyyw get() = DVec4(y, y, y, w)
inline val DVec4.yyzx get() = DVec4(y, y, z, x)
inline val DVec4.yyzy get() = DVec4(y, y, z, y)
inline val DVec4.yyzz get() = DVec4(y, y, z, z)
inline val DVec4.yyzw get() = DVec4(y, y, z, w)
inline val DVec4.yywx get() = DVec4(y, y, w, x)
inline val DVec4.yywy get() = DVec4(y, y, w, y)
inline val DVec4.yywz get() = DVec4(y, y, w, z)
inline val DVec4.yyww get() = DVec4(y, y, w, w)
inline val DVec4.yzxx get() = DVec4(y, z, x, x)
inline val DVec4.yzxy get() = DVec4(y, z, x, y)
inline val DVec4.yzxz get() = DVec4(y, z, x, z)
inline val DVec4.yzxw get() = DVec4(y, z, x, w)
inline val DVec4.yzyx get() = DVec4(y, z, y, x)
inline val DVec4.yzyy get() = DVec4(y, z, y, y)
inline val DVec4.yzyz get() = DVec4(y, z, y, z)
inline val DVec4.yzyw get() = DVec4(y, z, y, w)
inline val DVec4.yzzx get() = DVec4(y, z, z, x)
inline val DVec4.yzzy get() = DVec4(y, z, z, y)
inline val DVec4.yzzz get() = DVec4(y, z, z, z)
inline val DVec4.yzzw get() = DVec4(y, z, z, w)
inline val DVec4.yzwx get() = DVec4(y, z, w, x)
inline val DVec4.yzwy get() = DVec4(y, z, w, y)
inline val DVec4.yzwz get() = DVec4(y, z, w, z)
inline val DVec4.yzww get() = DVec4(y, z, w, w)
inline val DVec4.ywxx get() = DVec4(y, w, x, x)
inline val DVec4.ywxy get() = DVec4(y, w, x, y)
inline val DVec4.ywxz get() = DVec4(y, w, x, z)
inline val DVec4.ywxw get() = DVec4(y, w, x, w)
inline val DVec4.ywyx get() = DVec4(y, w, y, x)
inline val DVec4.ywyy get() = DVec4(y, w, y, y)
inline val DVec4.ywyz get() = DVec4(y, w, y, z)
inline val DVec4.ywyw get() = DVec4(y, w, y, w)
inline val DVec4.ywzx get() = DVec4(y, w, z, x)
inline val DVec4.ywzy get() = DVec4(y, w, z, y)
inline val DVec4.ywzz get() = DVec4(y, w, z, z)
inline val DVec4.ywzw get() = DVec4(y, w, z, w)
inline val DVec4.ywwx get() = DVec4(y, w, w, x)
inline val DVec4.ywwy get() = DVec4(y, w, w, y)
inline val DVec4.ywwz get() = DVec4(y, w, w, z)
inline val DVec4.ywww get() = DVec4(y, w, w, w)
inline val DVec4.zxxx get() = DVec4(z, x, x, x)
inline val DVec4.zxxy get() = DVec4(z, x, x, y)
inline val DVec4.zxxz get() = DVec4(z, x, x, z)
inline val DVec4.zxxw get() = DVec4(z, x, x, w)
inline val DVec4.zxyx get() = DVec4(z, x, y, x)
inline val DVec4.zxyy get() = DVec4(z, x, y, y)
inline val DVec4.zxyz get() = DVec4(z, x, y, z)
inline val DVec4.zxyw get() = DVec4(z, x, y, w)
inline val DVec4.zxzx get() = DVec4(z, x, z, x)
inline val DVec4.zxzy get() = DVec4(z, x, z, y)
inline val DVec4.zxzz get() = DVec4(z, x, z, z)
inline val DVec4.zxzw get() = DVec4(z, x, z, w)
inline val DVec4.zxwx get() = DVec4(z, x, w, x)
inline val DVec4.zxwy get() = DVec4(z, x, w, y)
inline val DVec4.zxwz get() = DVec4(z, x, w, z)
inline val DVec4.zxww get() = DVec4(z, x, w, w)
inline val DVec4.zyxx get() = DVec4(z, y, x, x)
inline val DVec4.zyxy get() = DVec4(z, y, x, y)
inline val DVec4.zyxz get() = DVec4(z, y, x, z)
inline val DVec4.zyxw get() = DVec4(z, y, x, w)
inline val DVec4.zyyx get() = DVec4(z, y, y, x)
inline val DVec4.zyyy get() = DVec4(z, y, y, y)
inline val DVec4.zyyz get() = DVec4(z, y, y, z)
inline val DVec4.zyyw get() = DVec4(z, y, y, w)
inline val DVec4.zyzx get() = DVec4(z, y, z, x)
inline val DVec4.zyzy get() = DVec4(z, y, z, y)
inline val DVec4.zyzz get() = DVec4(z, y, z, z)
inline val DVec4.zyzw get() = DVec4(z, y, z, w)
inline val DVec4.zywx get() = DVec4(z, y, w, x)
inline val DVec4.zywy get() = DVec4(z, y, w, y)
inline val DVec4.zywz get() = DVec4(z, y, w, z)
inline val DVec4.zyww get() = DVec4(z, y, w, w)
inline val DVec4.zzxx get() = DVec4(z, z, x, x)
inline val DVec4.zzxy get() = DVec4(z, z, x, y)
inline val DVec4.zzxz get() = DVec4(z, z, x, z)
inline val DVec4.zzxw get() = DVec4(z, z, x, w)
inline val DVec4.zzyx get() = DVec4(z, z, y, x)
inline val DVec4.zzyy get() = DVec4(z, z, y, y)
inline val DVec4.zzyz get() = DVec4(z, z, y, z)
inline val DVec4.zzyw get() = DVec4(z, z, y, w)
inline val DVec4.zzzx get() = DVec4(z, z, z, x)
inline val DVec4.zzzy get() = DVec4(z, z, z, y)
inline val DVec4.zzzz get() = DVec4(z, z, z, z)
inline val DVec4.zzzw get() = DVec4(z, z, z, w)
inline val DVec4.zzwx get() = DVec4(z, z, w, x)
inline val DVec4.zzwy get() = DVec4(z, z, w, y)
inline val DVec4.zzwz get() = DVec4(z, z, w, z)
inline val DVec4.zzww get() = DVec4(z, z, w, w)
inline val DVec4.zwxx get() = DVec4(z, w, x, x)
inline val DVec4.zwxy get() = DVec4(z, w, x, y)
inline val DVec4.zwxz get() = DVec4(z, w, x, z)
inline val DVec4.zwxw get() = DVec4(z, w, x, w)
inline val DVec4.zwyx get() = DVec4(z, w, y, x)
inline val DVec4.zwyy get() = DVec4(z, w, y, y)
inline val DVec4.zwyz get() = DVec4(z, w, y, z)
inline val DVec4.zwyw get() = DVec4(z, w, y, w)
inline val DVec4.zwzx get() = DVec4(z, w, z, x)
inline val DVec4.zwzy get() = DVec4(z, w, z, y)
inline val DVec4.zwzz get() = DVec4(z, w, z, z)
inline val DVec4.zwzw get() = DVec4(z, w, z, w)
inline val DVec4.zwwx get() = DVec4(z, w, w, x)
inline val DVec4.zwwy get() = DVec4(z, w, w, y)
inline val DVec4.zwwz get() = DVec4(z, w, w, z)
inline val DVec4.zwww get() = DVec4(z, w, w, w)
inline val DVec4.wxxx get() = DVec4(w, x, x, x)
inline val DVec4.wxxy get() = DVec4(w, x, x, y)
inline val DVec4.wxxz get() = DVec4(w, x, x, z)
inline val DVec4.wxxw get() = DVec4(w, x, x, w)
inline val DVec4.wxyx get() = DVec4(w, x, y, x)
inline val DVec4.wxyy get() = DVec4(w, x, y, y)
inline val DVec4.wxyz get() = DVec4(w, x, y, z)
inline val DVec4.wxyw get() = DVec4(w, x, y, w)
inline val DVec4.wxzx get() = DVec4(w, x, z, x)
inline val DVec4.wxzy get() = DVec4(w, x, z, y)
inline val DVec4.wxzz get() = DVec4(w, x, z, z)
inline val DVec4.wxzw get() = DVec4(w, x, z, w)
inline val DVec4.wxwx get() = DVec4(w, x, w, x)
inline val DVec4.wxwy get() = DVec4(w, x, w, y)
inline val DVec4.wxwz get() = DVec4(w, x, w, z)
inline val DVec4.wxww get() = DVec4(w, x, w, w)
inline val DVec4.wyxx get() = DVec4(w, y, x, x)
inline val DVec4.wyxy get() = DVec4(w, y, x, y)
inline val DVec4.wyxz get() = DVec4(w, y, x, z)
inline val DVec4.wyxw get() = DVec4(w, y, x, w)
inline val DVec4.wyyx get() = DVec4(w, y, y, x)
inline val DVec4.wyyy get() = DVec4(w, y, y, y)
inline val DVec4.wyyz get() = DVec4(w, y, y, z)
inline val DVec4.wyyw get() = DVec4(w, y, y, w)
inline val DVec4.wyzx get() = DVec4(w, y, z, x)
inline val DVec4.wyzy get() = DVec4(w, y, z, y)
inline val DVec4.wyzz get() = DVec4(w, y, z, z)
inline val DVec4.wyzw get() = DVec4(w, y, z, w)
inline val DVec4.wywx get() = DVec4(w, y, w, x)
inline val DVec4.wywy get() = DVec4(w, y, w, y)
inline val DVec4.wywz get() = DVec4(w, y, w, z)
inline val DVec4.wyww get() = DVec4(w, y, w, w)
inline val DVec4.wzxx get() = DVec4(w, z, x, x)
inline val DVec4.wzxy get() = DVec4(w, z, x, y)
inline val DVec4.wzxz get() = DVec4(w, z, x, z)
inline val DVec4.wzxw get() = DVec4(w, z, x, w)
inline val DVec4.wzyx get() = DVec4(w, z, y, x)
inline val DVec4.wzyy get() = DVec4(w, z, y, y)
inline val DVec4.wzyz get() = DVec4(w, z, y, z)
inline val DVec4.wzyw get() = DVec4(w, z, y, w)
inline val DVec4.wzzx get() = DVec4(w, z, z, x)
inline val DVec4.wzzy get() = DVec4(w, z, z, y)
inline val DVec4.wzzz get() = DVec4(w, z, z, z)
inline val DVec4.wzzw get() = DVec4(w, z, z, w)
inline val DVec4.wzwx get() = DVec4(w, z, w, x)
inline val DVec4.wzwy get() = DVec4(w, z, w, y)
inline val DVec4.wzwz get() = DVec4(w, z, w, z)
inline val DVec4.wzww get() = DVec4(w, z, w, w)
inline val DVec4.wwxx get() = DVec4(w, w, x, x)
inline val DVec4.wwxy get() = DVec4(w, w, x, y)
inline val DVec4.wwxz get() = DVec4(w, w, x, z)
inline val DVec4.wwxw get() = DVec4(w, w, x, w)
inline val DVec4.wwyx get() = DVec4(w, w, y, x)
inline val DVec4.wwyy get() = DVec4(w, w, y, y)
inline val DVec4.wwyz get() = DVec4(w, w, y, z)
inline val DVec4.wwyw get() = DVec4(w, w, y, w)
inline val DVec4.wwzx get() = DVec4(w, w, z, x)
inline val DVec4.wwzy get() = DVec4(w, w, z, y)
inline val DVec4.wwzz get() = DVec4(w, w, z, z)
inline val DVec4.wwzw get() = DVec4(w, w, z, w)
inline val DVec4.wwwx get() = DVec4(w, w, w, x)
inline val DVec4.wwwy get() = DVec4(w, w, w, y)
inline val DVec4.wwwz get() = DVec4(w, w, w, z)
inline val DVec4.wwww get() = DVec4(w, w, w, w)

inline val DVec4.rrrr get() = DVec4(r, r, r, r)
inline val DVec4.rrrg get() = DVec4(r, r, r, g)
inline val DVec4.rrrb get() = DVec4(r, r, r, b)
inline val DVec4.rrra get() = DVec4(r, r, r, a)
inline val DVec4.rrgr get() = DVec4(r, r, g, r)
inline val DVec4.rrgg get() = DVec4(r, r, g, g)
inline val DVec4.rrgb get() = DVec4(r, r, g, b)
inline val DVec4.rrga get() = DVec4(r, r, g, a)
inline val DVec4.rrbr get() = DVec4(r, r, b, r)
inline val DVec4.rrbg get() = DVec4(r, r, b, g)
inline val DVec4.rrbb get() = DVec4(r, r, b, b)
inline val DVec4.rrba get() = DVec4(r, r, b, a)
inline val DVec4.rrar get() = DVec4(r, r, a, r)
inline val DVec4.rrag get() = DVec4(r, r, a, g)
inline val DVec4.rrab get() = DVec4(r, r, a, b)
inline val DVec4.rraa get() = DVec4(r, r, a, a)
inline val DVec4.rgrr get() = DVec4(r, g, r, r)
inline val DVec4.rgrg get() = DVec4(r, g, r, g)
inline val DVec4.rgrb get() = DVec4(r, g, r, b)
inline val DVec4.rgra get() = DVec4(r, g, r, a)
inline val DVec4.rggr get() = DVec4(r, g, g, r)
inline val DVec4.rggg get() = DVec4(r, g, g, g)
inline val DVec4.rggb get() = DVec4(r, g, g, b)
inline val DVec4.rgga get() = DVec4(r, g, g, a)
inline val DVec4.rgbr get() = DVec4(r, g, b, r)
inline val DVec4.rgbg get() = DVec4(r, g, b, g)
inline val DVec4.rgbb get() = DVec4(r, g, b, b)
inline val DVec4.rgba get() = DVec4(r, g, b, a)
inline val DVec4.rgar get() = DVec4(r, g, a, r)
inline val DVec4.rgag get() = DVec4(r, g, a, g)
inline val DVec4.rgab get() = DVec4(r, g, a, b)
inline val DVec4.rgaa get() = DVec4(r, g, a, a)
inline val DVec4.rbrr get() = DVec4(r, b, r, r)
inline val DVec4.rbrg get() = DVec4(r, b, r, g)
inline val DVec4.rbrb get() = DVec4(r, b, r, b)
inline val DVec4.rbra get() = DVec4(r, b, r, a)
inline val DVec4.rbgr get() = DVec4(r, b, g, r)
inline val DVec4.rbgg get() = DVec4(r, b, g, g)
inline val DVec4.rbgb get() = DVec4(r, b, g, b)
inline val DVec4.rbga get() = DVec4(r, b, g, a)
inline val DVec4.rbbr get() = DVec4(r, b, b, r)
inline val DVec4.rbbg get() = DVec4(r, b, b, g)
inline val DVec4.rbbb get() = DVec4(r, b, b, b)
inline val DVec4.rbba get() = DVec4(r, b, b, a)
inline val DVec4.rbar get() = DVec4(r, b, a, r)
inline val DVec4.rbag get() = DVec4(r, b, a, g)
inline val DVec4.rbab get() = DVec4(r, b, a, b)
inline val DVec4.rbaa get() = DVec4(r, b, a, a)
inline val DVec4.rarr get() = DVec4(r, a, r, r)
inline val DVec4.rarg get() = DVec4(r, a, r, g)
inline val DVec4.rarb get() = DVec4(r, a, r, b)
inline val DVec4.rara get() = DVec4(r, a, r, a)
inline val DVec4.ragr get() = DVec4(r, a, g, r)
inline val DVec4.ragg get() = DVec4(r, a, g, g)
inline val DVec4.ragb get() = DVec4(r, a, g, b)
inline val DVec4.raga get() = DVec4(r, a, g, a)
inline val DVec4.rabr get() = DVec4(r, a, b, r)
inline val DVec4.rabg get() = DVec4(r, a, b, g)
inline val DVec4.rabb get() = DVec4(r, a, b, b)
inline val DVec4.raba get() = DVec4(r, a, b, a)
inline val DVec4.raar get() = DVec4(r, a, a, r)
inline val DVec4.raag get() = DVec4(r, a, a, g)
inline val DVec4.raab get() = DVec4(r, a, a, b)
inline val DVec4.raaa get() = DVec4(r, a, a, a)
inline val DVec4.grrr get() = DVec4(g, r, r, r)
inline val DVec4.grrg get() = DVec4(g, r, r, g)
inline val DVec4.grrb get() = DVec4(g, r, r, b)
inline val DVec4.grra get() = DVec4(g, r, r, a)
inline val DVec4.grgr get() = DVec4(g, r, g, r)
inline val DVec4.grgg get() = DVec4(g, r, g, g)
inline val DVec4.grgb get() = DVec4(g, r, g, b)
inline val DVec4.grga get() = DVec4(g, r, g, a)
inline val DVec4.grbr get() = DVec4(g, r, b, r)
inline val DVec4.grbg get() = DVec4(g, r, b, g)
inline val DVec4.grbb get() = DVec4(g, r, b, b)
inline val DVec4.grba get() = DVec4(g, r, b, a)
inline val DVec4.grar get() = DVec4(g, r, a, r)
inline val DVec4.grag get() = DVec4(g, r, a, g)
inline val DVec4.grab get() = DVec4(g, r, a, b)
inline val DVec4.graa get() = DVec4(g, r, a, a)
inline val DVec4.ggrr get() = DVec4(g, g, r, r)
inline val DVec4.ggrg get() = DVec4(g, g, r, g)
inline val DVec4.ggrb get() = DVec4(g, g, r, b)
inline val DVec4.ggra get() = DVec4(g, g, r, a)
inline val DVec4.gggr get() = DVec4(g, g, g, r)
inline val DVec4.gggg get() = DVec4(g, g, g, g)
inline val DVec4.gggb get() = DVec4(g, g, g, b)
inline val DVec4.ggga get() = DVec4(g, g, g, a)
inline val DVec4.ggbr get() = DVec4(g, g, b, r)
inline val DVec4.ggbg get() = DVec4(g, g, b, g)
inline val DVec4.ggbb get() = DVec4(g, g, b, b)
inline val DVec4.ggba get() = DVec4(g, g, b, a)
inline val DVec4.ggar get() = DVec4(g, g, a, r)
inline val DVec4.ggag get() = DVec4(g, g, a, g)
inline val DVec4.ggab get() = DVec4(g, g, a, b)
inline val DVec4.ggaa get() = DVec4(g, g, a, a)
inline val DVec4.gbrr get() = DVec4(g, b, r, r)
inline val DVec4.gbrg get() = DVec4(g, b, r, g)
inline val DVec4.gbrb get() = DVec4(g, b, r, b)
inline val DVec4.gbra get() = DVec4(g, b, r, a)
inline val DVec4.gbgr get() = DVec4(g, b, g, r)
inline val DVec4.gbgg get() = DVec4(g, b, g, g)
inline val DVec4.gbgb get() = DVec4(g, b, g, b)
inline val DVec4.gbga get() = DVec4(g, b, g, a)
inline val DVec4.gbbr get() = DVec4(g, b, b, r)
inline val DVec4.gbbg get() = DVec4(g, b, b, g)
inline val DVec4.gbbb get() = DVec4(g, b, b, b)
inline val DVec4.gbba get() = DVec4(g, b, b, a)
inline val DVec4.gbar get() = DVec4(g, b, a, r)
inline val DVec4.gbag get() = DVec4(g, b, a, g)
inline val DVec4.gbab get() = DVec4(g, b, a, b)
inline val DVec4.gbaa get() = DVec4(g, b, a, a)
inline val DVec4.garr get() = DVec4(g, a, r, r)
inline val DVec4.garg get() = DVec4(g, a, r, g)
inline val DVec4.garb get() = DVec4(g, a, r, b)
inline val DVec4.gara get() = DVec4(g, a, r, a)
inline val DVec4.gagr get() = DVec4(g, a, g, r)
inline val DVec4.gagg get() = DVec4(g, a, g, g)
inline val DVec4.gagb get() = DVec4(g, a, g, b)
inline val DVec4.gaga get() = DVec4(g, a, g, a)
inline val DVec4.gabr get() = DVec4(g, a, b, r)
inline val DVec4.gabg get() = DVec4(g, a, b, g)
inline val DVec4.gabb get() = DVec4(g, a, b, b)
inline val DVec4.gaba get() = DVec4(g, a, b, a)
inline val DVec4.gaar get() = DVec4(g, a, a, r)
inline val DVec4.gaag get() = DVec4(g, a, a, g)
inline val DVec4.gaab get() = DVec4(g, a, a, b)
inline val DVec4.gaaa get() = DVec4(g, a, a, a)
inline val DVec4.brrr get() = DVec4(b, r, r, r)
inline val DVec4.brrg get() = DVec4(b, r, r, g)
inline val DVec4.brrb get() = DVec4(b, r, r, b)
inline val DVec4.brra get() = DVec4(b, r, r, a)
inline val DVec4.brgr get() = DVec4(b, r, g, r)
inline val DVec4.brgg get() = DVec4(b, r, g, g)
inline val DVec4.brgb get() = DVec4(b, r, g, b)
inline val DVec4.brga get() = DVec4(b, r, g, a)
inline val DVec4.brbr get() = DVec4(b, r, b, r)
inline val DVec4.brbg get() = DVec4(b, r, b, g)
inline val DVec4.brbb get() = DVec4(b, r, b, b)
inline val DVec4.brba get() = DVec4(b, r, b, a)
inline val DVec4.brar get() = DVec4(b, r, a, r)
inline val DVec4.brag get() = DVec4(b, r, a, g)
inline val DVec4.brab get() = DVec4(b, r, a, b)
inline val DVec4.braa get() = DVec4(b, r, a, a)
inline val DVec4.bgrr get() = DVec4(b, g, r, r)
inline val DVec4.bgrg get() = DVec4(b, g, r, g)
inline val DVec4.bgrb get() = DVec4(b, g, r, b)
inline val DVec4.bgra get() = DVec4(b, g, r, a)
inline val DVec4.bggr get() = DVec4(b, g, g, r)
inline val DVec4.bggg get() = DVec4(b, g, g, g)
inline val DVec4.bggb get() = DVec4(b, g, g, b)
inline val DVec4.bgga get() = DVec4(b, g, g, a)
inline val DVec4.bgbr get() = DVec4(b, g, b, r)
inline val DVec4.bgbg get() = DVec4(b, g, b, g)
inline val DVec4.bgbb get() = DVec4(b, g, b, b)
inline val DVec4.bgba get() = DVec4(b, g, b, a)
inline val DVec4.bgar get() = DVec4(b, g, a, r)
inline val DVec4.bgag get() = DVec4(b, g, a, g)
inline val DVec4.bgab get() = DVec4(b, g, a, b)
inline val DVec4.bgaa get() = DVec4(b, g, a, a)
inline val DVec4.bbrr get() = DVec4(b, b, r, r)
inline val DVec4.bbrg get() = DVec4(b, b, r, g)
inline val DVec4.bbrb get() = DVec4(b, b, r, b)
inline val DVec4.bbra get() = DVec4(b, b, r, a)
inline val DVec4.bbgr get() = DVec4(b, b, g, r)
inline val DVec4.bbgg get() = DVec4(b, b, g, g)
inline val DVec4.bbgb get() = DVec4(b, b, g, b)
inline val DVec4.bbga get() = DVec4(b, b, g, a)
inline val DVec4.bbbr get() = DVec4(b, b, b, r)
inline val DVec4.bbbg get() = DVec4(b, b, b, g)
inline val DVec4.bbbb get() = DVec4(b, b, b, b)
inline val DVec4.bbba get() = DVec4(b, b, b, a)
inline val DVec4.bbar get() = DVec4(b, b, a, r)
inline val DVec4.bbag get() = DVec4(b, b, a, g)
inline val DVec4.bbab get() = DVec4(b, b, a, b)
inline val DVec4.bbaa get() = DVec4(b, b, a, a)
inline val DVec4.barr get() = DVec4(b, a, r, r)
inline val DVec4.barg get() = DVec4(b, a, r, g)
inline val DVec4.barb get() = DVec4(b, a, r, b)
inline val DVec4.bara get() = DVec4(b, a, r, a)
inline val DVec4.bagr get() = DVec4(b, a, g, r)
inline val DVec4.bagg get() = DVec4(b, a, g, g)
inline val DVec4.bagb get() = DVec4(b, a, g, b)
inline val DVec4.baga get() = DVec4(b, a, g, a)
inline val DVec4.babr get() = DVec4(b, a, b, r)
inline val DVec4.babg get() = DVec4(b, a, b, g)
inline val DVec4.babb get() = DVec4(b, a, b, b)
inline val DVec4.baba get() = DVec4(b, a, b, a)
inline val DVec4.baar get() = DVec4(b, a, a, r)
inline val DVec4.baag get() = DVec4(b, a, a, g)
inline val DVec4.baab get() = DVec4(b, a, a, b)
inline val DVec4.baaa get() = DVec4(b, a, a, a)
inline val DVec4.arrr get() = DVec4(a, r, r, r)
inline val DVec4.arrg get() = DVec4(a, r, r, g)
inline val DVec4.arrb get() = DVec4(a, r, r, b)
inline val DVec4.arra get() = DVec4(a, r, r, a)
inline val DVec4.argr get() = DVec4(a, r, g, r)
inline val DVec4.argg get() = DVec4(a, r, g, g)
inline val DVec4.argb get() = DVec4(a, r, g, b)
inline val DVec4.arga get() = DVec4(a, r, g, a)
inline val DVec4.arbr get() = DVec4(a, r, b, r)
inline val DVec4.arbg get() = DVec4(a, r, b, g)
inline val DVec4.arbb get() = DVec4(a, r, b, b)
inline val DVec4.arba get() = DVec4(a, r, b, a)
inline val DVec4.arar get() = DVec4(a, r, a, r)
inline val DVec4.arag get() = DVec4(a, r, a, g)
inline val DVec4.arab get() = DVec4(a, r, a, b)
inline val DVec4.araa get() = DVec4(a, r, a, a)
inline val DVec4.agrr get() = DVec4(a, g, r, r)
inline val DVec4.agrg get() = DVec4(a, g, r, g)
inline val DVec4.agrb get() = DVec4(a, g, r, b)
inline val DVec4.agra get() = DVec4(a, g, r, a)
inline val DVec4.aggr get() = DVec4(a, g, g, r)
inline val DVec4.aggg get() = DVec4(a, g, g, g)
inline val DVec4.aggb get() = DVec4(a, g, g, b)
inline val DVec4.agga get() = DVec4(a, g, g, a)
inline val DVec4.agbr get() = DVec4(a, g, b, r)
inline val DVec4.agbg get() = DVec4(a, g, b, g)
inline val DVec4.agbb get() = DVec4(a, g, b, b)
inline val DVec4.agba get() = DVec4(a, g, b, a)
inline val DVec4.agar get() = DVec4(a, g, a, r)
inline val DVec4.agag get() = DVec4(a, g, a, g)
inline val DVec4.agab get() = DVec4(a, g, a, b)
inline val DVec4.agaa get() = DVec4(a, g, a, a)
inline val DVec4.abrr get() = DVec4(a, b, r, r)
inline val DVec4.abrg get() = DVec4(a, b, r, g)
inline val DVec4.abrb get() = DVec4(a, b, r, b)
inline val DVec4.abra get() = DVec4(a, b, r, a)
inline val DVec4.abgr get() = DVec4(a, b, g, r)
inline val DVec4.abgg get() = DVec4(a, b, g, g)
inline val DVec4.abgb get() = DVec4(a, b, g, b)
inline val DVec4.abga get() = DVec4(a, b, g, a)
inline val DVec4.abbr get() = DVec4(a, b, b, r)
inline val DVec4.abbg get() = DVec4(a, b, b, g)
inline val DVec4.abbb get() = DVec4(a, b, b, b)
inline val DVec4.abba get() = DVec4(a, b, b, a)
inline val DVec4.abar get() = DVec4(a, b, a, r)
inline val DVec4.abag get() = DVec4(a, b, a, g)
inline val DVec4.abab get() = DVec4(a, b, a, b)
inline val DVec4.abaa get() = DVec4(a, b, a, a)
inline val DVec4.aarr get() = DVec4(a, a, r, r)
inline val DVec4.aarg get() = DVec4(a, a, r, g)
inline val DVec4.aarb get() = DVec4(a, a, r, b)
inline val DVec4.aara get() = DVec4(a, a, r, a)
inline val DVec4.aagr get() = DVec4(a, a, g, r)
inline val DVec4.aagg get() = DVec4(a, a, g, g)
inline val DVec4.aagb get() = DVec4(a, a, g, b)
inline val DVec4.aaga get() = DVec4(a, a, g, a)
inline val DVec4.aabr get() = DVec4(a, a, b, r)
inline val DVec4.aabg get() = DVec4(a, a, b, g)
inline val DVec4.aabb get() = DVec4(a, a, b, b)
inline val DVec4.aaba get() = DVec4(a, a, b, a)
inline val DVec4.aaar get() = DVec4(a, a, a, r)
inline val DVec4.aaag get() = DVec4(a, a, a, g)
inline val DVec4.aaab get() = DVec4(a, a, a, b)
inline val DVec4.aaaa get() = DVec4(a, a, a, a)

inline val DVec4.ssss get() = DVec4(s, s, s, s)
inline val DVec4.ssst get() = DVec4(s, s, s, t)
inline val DVec4.sssp get() = DVec4(s, s, s, p)
inline val DVec4.sssq get() = DVec4(s, s, s, q)
inline val DVec4.ssts get() = DVec4(s, s, t, s)
inline val DVec4.sstt get() = DVec4(s, s, t, t)
inline val DVec4.sstp get() = DVec4(s, s, t, p)
inline val DVec4.sstq get() = DVec4(s, s, t, q)
inline val DVec4.ssps get() = DVec4(s, s, p, s)
inline val DVec4.sspt get() = DVec4(s, s, p, t)
inline val DVec4.sspp get() = DVec4(s, s, p, p)
inline val DVec4.sspq get() = DVec4(s, s, p, q)
inline val DVec4.ssqs get() = DVec4(s, s, q, s)
inline val DVec4.ssqt get() = DVec4(s, s, q, t)
inline val DVec4.ssqp get() = DVec4(s, s, q, p)
inline val DVec4.ssqq get() = DVec4(s, s, q, q)
inline val DVec4.stss get() = DVec4(s, t, s, s)
inline val DVec4.stst get() = DVec4(s, t, s, t)
inline val DVec4.stsp get() = DVec4(s, t, s, p)
inline val DVec4.stsq get() = DVec4(s, t, s, q)
inline val DVec4.stts get() = DVec4(s, t, t, s)
inline val DVec4.sttt get() = DVec4(s, t, t, t)
inline val DVec4.sttp get() = DVec4(s, t, t, p)
inline val DVec4.sttq get() = DVec4(s, t, t, q)
inline val DVec4.stps get() = DVec4(s, t, p, s)
inline val DVec4.stpt get() = DVec4(s, t, p, t)
inline val DVec4.stpp get() = DVec4(s, t, p, p)
inline val DVec4.stpq get() = DVec4(s, t, p, q)
inline val DVec4.stqs get() = DVec4(s, t, q, s)
inline val DVec4.stqt get() = DVec4(s, t, q, t)
inline val DVec4.stqp get() = DVec4(s, t, q, p)
inline val DVec4.stqq get() = DVec4(s, t, q, q)
inline val DVec4.spss get() = DVec4(s, p, s, s)
inline val DVec4.spst get() = DVec4(s, p, s, t)
inline val DVec4.spsp get() = DVec4(s, p, s, p)
inline val DVec4.spsq get() = DVec4(s, p, s, q)
inline val DVec4.spts get() = DVec4(s, p, t, s)
inline val DVec4.sptt get() = DVec4(s, p, t, t)
inline val DVec4.sptp get() = DVec4(s, p, t, p)
inline val DVec4.sptq get() = DVec4(s, p, t, q)
inline val DVec4.spps get() = DVec4(s, p, p, s)
inline val DVec4.sppt get() = DVec4(s, p, p, t)
inline val DVec4.sppp get() = DVec4(s, p, p, p)
inline val DVec4.sppq get() = DVec4(s, p, p, q)
inline val DVec4.spqs get() = DVec4(s, p, q, s)
inline val DVec4.spqt get() = DVec4(s, p, q, t)
inline val DVec4.spqp get() = DVec4(s, p, q, p)
inline val DVec4.spqq get() = DVec4(s, p, q, q)
inline val DVec4.sqss get() = DVec4(s, q, s, s)
inline val DVec4.sqst get() = DVec4(s, q, s, t)
inline val DVec4.sqsp get() = DVec4(s, q, s, p)
inline val DVec4.sqsq get() = DVec4(s, q, s, q)
inline val DVec4.sqts get() = DVec4(s, q, t, s)
inline val DVec4.sqtt get() = DVec4(s, q, t, t)
inline val DVec4.sqtp get() = DVec4(s, q, t, p)
inline val DVec4.sqtq get() = DVec4(s, q, t, q)
inline val DVec4.sqps get() = DVec4(s, q, p, s)
inline val DVec4.sqpt get() = DVec4(s, q, p, t)
inline val DVec4.sqpp get() = DVec4(s, q, p, p)
inline val DVec4.sqpq get() = DVec4(s, q, p, q)
inline val DVec4.sqqs get() = DVec4(s, q, q, s)
inline val DVec4.sqqt get() = DVec4(s, q, q, t)
inline val DVec4.sqqp get() = DVec4(s, q, q, p)
inline val DVec4.sqqq get() = DVec4(s, q, q, q)
inline val DVec4.tsss get() = DVec4(t, s, s, s)
inline val DVec4.tsst get() = DVec4(t, s, s, t)
inline val DVec4.tssp get() = DVec4(t, s, s, p)
inline val DVec4.tssq get() = DVec4(t, s, s, q)
inline val DVec4.tsts get() = DVec4(t, s, t, s)
inline val DVec4.tstt get() = DVec4(t, s, t, t)
inline val DVec4.tstp get() = DVec4(t, s, t, p)
inline val DVec4.tstq get() = DVec4(t, s, t, q)
inline val DVec4.tsps get() = DVec4(t, s, p, s)
inline val DVec4.tspt get() = DVec4(t, s, p, t)
inline val DVec4.tspp get() = DVec4(t, s, p, p)
inline val DVec4.tspq get() = DVec4(t, s, p, q)
inline val DVec4.tsqs get() = DVec4(t, s, q, s)
inline val DVec4.tsqt get() = DVec4(t, s, q, t)
inline val DVec4.tsqp get() = DVec4(t, s, q, p)
inline val DVec4.tsqq get() = DVec4(t, s, q, q)
inline val DVec4.ttss get() = DVec4(t, t, s, s)
inline val DVec4.ttst get() = DVec4(t, t, s, t)
inline val DVec4.ttsp get() = DVec4(t, t, s, p)
inline val DVec4.ttsq get() = DVec4(t, t, s, q)
inline val DVec4.ttts get() = DVec4(t, t, t, s)
inline val DVec4.tttt get() = DVec4(t, t, t, t)
inline val DVec4.tttp get() = DVec4(t, t, t, p)
inline val DVec4.tttq get() = DVec4(t, t, t, q)
inline val DVec4.ttps get() = DVec4(t, t, p, s)
inline val DVec4.ttpt get() = DVec4(t, t, p, t)
inline val DVec4.ttpp get() = DVec4(t, t, p, p)
inline val DVec4.ttpq get() = DVec4(t, t, p, q)
inline val DVec4.ttqs get() = DVec4(t, t, q, s)
inline val DVec4.ttqt get() = DVec4(t, t, q, t)
inline val DVec4.ttqp get() = DVec4(t, t, q, p)
inline val DVec4.ttqq get() = DVec4(t, t, q, q)
inline val DVec4.tpss get() = DVec4(t, p, s, s)
inline val DVec4.tpst get() = DVec4(t, p, s, t)
inline val DVec4.tpsp get() = DVec4(t, p, s, p)
inline val DVec4.tpsq get() = DVec4(t, p, s, q)
inline val DVec4.tpts get() = DVec4(t, p, t, s)
inline val DVec4.tptt get() = DVec4(t, p, t, t)
inline val DVec4.tptp get() = DVec4(t, p, t, p)
inline val DVec4.tptq get() = DVec4(t, p, t, q)
inline val DVec4.tpps get() = DVec4(t, p, p, s)
inline val DVec4.tppt get() = DVec4(t, p, p, t)
inline val DVec4.tppp get() = DVec4(t, p, p, p)
inline val DVec4.tppq get() = DVec4(t, p, p, q)
inline val DVec4.tpqs get() = DVec4(t, p, q, s)
inline val DVec4.tpqt get() = DVec4(t, p, q, t)
inline val DVec4.tpqp get() = DVec4(t, p, q, p)
inline val DVec4.tpqq get() = DVec4(t, p, q, q)
inline val DVec4.tqss get() = DVec4(t, q, s, s)
inline val DVec4.tqst get() = DVec4(t, q, s, t)
inline val DVec4.tqsp get() = DVec4(t, q, s, p)
inline val DVec4.tqsq get() = DVec4(t, q, s, q)
inline val DVec4.tqts get() = DVec4(t, q, t, s)
inline val DVec4.tqtt get() = DVec4(t, q, t, t)
inline val DVec4.tqtp get() = DVec4(t, q, t, p)
inline val DVec4.tqtq get() = DVec4(t, q, t, q)
inline val DVec4.tqps get() = DVec4(t, q, p, s)
inline val DVec4.tqpt get() = DVec4(t, q, p, t)
inline val DVec4.tqpp get() = DVec4(t, q, p, p)
inline val DVec4.tqpq get() = DVec4(t, q, p, q)
inline val DVec4.tqqs get() = DVec4(t, q, q, s)
inline val DVec4.tqqt get() = DVec4(t, q, q, t)
inline val DVec4.tqqp get() = DVec4(t, q, q, p)
inline val DVec4.tqqq get() = DVec4(t, q, q, q)
inline val DVec4.psss get() = DVec4(p, s, s, s)
inline val DVec4.psst get() = DVec4(p, s, s, t)
inline val DVec4.pssp get() = DVec4(p, s, s, p)
inline val DVec4.pssq get() = DVec4(p, s, s, q)
inline val DVec4.psts get() = DVec4(p, s, t, s)
inline val DVec4.pstt get() = DVec4(p, s, t, t)
inline val DVec4.pstp get() = DVec4(p, s, t, p)
inline val DVec4.pstq get() = DVec4(p, s, t, q)
inline val DVec4.psps get() = DVec4(p, s, p, s)
inline val DVec4.pspt get() = DVec4(p, s, p, t)
inline val DVec4.pspp get() = DVec4(p, s, p, p)
inline val DVec4.pspq get() = DVec4(p, s, p, q)
inline val DVec4.psqs get() = DVec4(p, s, q, s)
inline val DVec4.psqt get() = DVec4(p, s, q, t)
inline val DVec4.psqp get() = DVec4(p, s, q, p)
inline val DVec4.psqq get() = DVec4(p, s, q, q)
inline val DVec4.ptss get() = DVec4(p, t, s, s)
inline val DVec4.ptst get() = DVec4(p, t, s, t)
inline val DVec4.ptsp get() = DVec4(p, t, s, p)
inline val DVec4.ptsq get() = DVec4(p, t, s, q)
inline val DVec4.ptts get() = DVec4(p, t, t, s)
inline val DVec4.pttt get() = DVec4(p, t, t, t)
inline val DVec4.pttp get() = DVec4(p, t, t, p)
inline val DVec4.pttq get() = DVec4(p, t, t, q)
inline val DVec4.ptps get() = DVec4(p, t, p, s)
inline val DVec4.ptpt get() = DVec4(p, t, p, t)
inline val DVec4.ptpp get() = DVec4(p, t, p, p)
inline val DVec4.ptpq get() = DVec4(p, t, p, q)
inline val DVec4.ptqs get() = DVec4(p, t, q, s)
inline val DVec4.ptqt get() = DVec4(p, t, q, t)
inline val DVec4.ptqp get() = DVec4(p, t, q, p)
inline val DVec4.ptqq get() = DVec4(p, t, q, q)
inline val DVec4.ppss get() = DVec4(p, p, s, s)
inline val DVec4.ppst get() = DVec4(p, p, s, t)
inline val DVec4.ppsp get() = DVec4(p, p, s, p)
inline val DVec4.ppsq get() = DVec4(p, p, s, q)
inline val DVec4.ppts get() = DVec4(p, p, t, s)
inline val DVec4.pptt get() = DVec4(p, p, t, t)
inline val DVec4.pptp get() = DVec4(p, p, t, p)
inline val DVec4.pptq get() = DVec4(p, p, t, q)
inline val DVec4.ppps get() = DVec4(p, p, p, s)
inline val DVec4.pppt get() = DVec4(p, p, p, t)
inline val DVec4.pppp get() = DVec4(p, p, p, p)
inline val DVec4.pppq get() = DVec4(p, p, p, q)
inline val DVec4.ppqs get() = DVec4(p, p, q, s)
inline val DVec4.ppqt get() = DVec4(p, p, q, t)
inline val DVec4.ppqp get() = DVec4(p, p, q, p)
inline val DVec4.ppqq get() = DVec4(p, p, q, q)
inline val DVec4.pqss get() = DVec4(p, q, s, s)
inline val DVec4.pqst get() = DVec4(p, q, s, t)
inline val DVec4.pqsp get() = DVec4(p, q, s, p)
inline val DVec4.pqsq get() = DVec4(p, q, s, q)
inline val DVec4.pqts get() = DVec4(p, q, t, s)
inline val DVec4.pqtt get() = DVec4(p, q, t, t)
inline val DVec4.pqtp get() = DVec4(p, q, t, p)
inline val DVec4.pqtq get() = DVec4(p, q, t, q)
inline val DVec4.pqps get() = DVec4(p, q, p, s)
inline val DVec4.pqpt get() = DVec4(p, q, p, t)
inline val DVec4.pqpp get() = DVec4(p, q, p, p)
inline val DVec4.pqpq get() = DVec4(p, q, p, q)
inline val DVec4.pqqs get() = DVec4(p, q, q, s)
inline val DVec4.pqqt get() = DVec4(p, q, q, t)
inline val DVec4.pqqp get() = DVec4(p, q, q, p)
inline val DVec4.pqqq get() = DVec4(p, q, q, q)
inline val DVec4.qsss get() = DVec4(q, s, s, s)
inline val DVec4.qsst get() = DVec4(q, s, s, t)
inline val DVec4.qssp get() = DVec4(q, s, s, p)
inline val DVec4.qssq get() = DVec4(q, s, s, q)
inline val DVec4.qsts get() = DVec4(q, s, t, s)
inline val DVec4.qstt get() = DVec4(q, s, t, t)
inline val DVec4.qstp get() = DVec4(q, s, t, p)
inline val DVec4.qstq get() = DVec4(q, s, t, q)
inline val DVec4.qsps get() = DVec4(q, s, p, s)
inline val DVec4.qspt get() = DVec4(q, s, p, t)
inline val DVec4.qspp get() = DVec4(q, s, p, p)
inline val DVec4.qspq get() = DVec4(q, s, p, q)
inline val DVec4.qsqs get() = DVec4(q, s, q, s)
inline val DVec4.qsqt get() = DVec4(q, s, q, t)
inline val DVec4.qsqp get() = DVec4(q, s, q, p)
inline val DVec4.qsqq get() = DVec4(q, s, q, q)
inline val DVec4.qtss get() = DVec4(q, t, s, s)
inline val DVec4.qtst get() = DVec4(q, t, s, t)
inline val DVec4.qtsp get() = DVec4(q, t, s, p)
inline val DVec4.qtsq get() = DVec4(q, t, s, q)
inline val DVec4.qtts get() = DVec4(q, t, t, s)
inline val DVec4.qttt get() = DVec4(q, t, t, t)
inline val DVec4.qttp get() = DVec4(q, t, t, p)
inline val DVec4.qttq get() = DVec4(q, t, t, q)
inline val DVec4.qtps get() = DVec4(q, t, p, s)
inline val DVec4.qtpt get() = DVec4(q, t, p, t)
inline val DVec4.qtpp get() = DVec4(q, t, p, p)
inline val DVec4.qtpq get() = DVec4(q, t, p, q)
inline val DVec4.qtqs get() = DVec4(q, t, q, s)
inline val DVec4.qtqt get() = DVec4(q, t, q, t)
inline val DVec4.qtqp get() = DVec4(q, t, q, p)
inline val DVec4.qtqq get() = DVec4(q, t, q, q)
inline val DVec4.qpss get() = DVec4(q, p, s, s)
inline val DVec4.qpst get() = DVec4(q, p, s, t)
inline val DVec4.qpsp get() = DVec4(q, p, s, p)
inline val DVec4.qpsq get() = DVec4(q, p, s, q)
inline val DVec4.qpts get() = DVec4(q, p, t, s)
inline val DVec4.qptt get() = DVec4(q, p, t, t)
inline val DVec4.qptp get() = DVec4(q, p, t, p)
inline val DVec4.qptq get() = DVec4(q, p, t, q)
inline val DVec4.qpps get() = DVec4(q, p, p, s)
inline val DVec4.qppt get() = DVec4(q, p, p, t)
inline val DVec4.qppp get() = DVec4(q, p, p, p)
inline val DVec4.qppq get() = DVec4(q, p, p, q)
inline val DVec4.qpqs get() = DVec4(q, p, q, s)
inline val DVec4.qpqt get() = DVec4(q, p, q, t)
inline val DVec4.qpqp get() = DVec4(q, p, q, p)
inline val DVec4.qpqq get() = DVec4(q, p, q, q)
inline val DVec4.qqss get() = DVec4(q, q, s, s)
inline val DVec4.qqst get() = DVec4(q, q, s, t)
inline val DVec4.qqsp get() = DVec4(q, q, s, p)
inline val DVec4.qqsq get() = DVec4(q, q, s, q)
inline val DVec4.qqts get() = DVec4(q, q, t, s)
inline val DVec4.qqtt get() = DVec4(q, q, t, t)
inline val DVec4.qqtp get() = DVec4(q, q, t, p)
inline val DVec4.qqtq get() = DVec4(q, q, t, q)
inline val DVec4.qqps get() = DVec4(q, q, p, s)
inline val DVec4.qqpt get() = DVec4(q, q, p, t)
inline val DVec4.qqpp get() = DVec4(q, q, p, p)
inline val DVec4.qqpq get() = DVec4(q, q, p, q)
inline val DVec4.qqqs get() = DVec4(q, q, q, s)
inline val DVec4.qqqt get() = DVec4(q, q, q, t)
inline val DVec4.qqqp get() = DVec4(q, q, q, p)
inline val DVec4.qqqq get() = DVec4(q, q, q, q)
//endregion
